### ISSUE TITLE
Interrupteur double Xiaomi lumi.ctrl_ln2.aq1

### ISSUE THREAD

**Issue by daredevil-ferreira** [Jeedom-Zigate/jeedom-plugin-zigate#100]
L'interrupteur double mural (sans pile) (QBKG12LM) me semble mal reconnu.

Lorsque je l'appaire avec le Zigate, un seul des interrupteurs est commandable (on/off).

David

**Comment by llaumgui** [comment]
Même après un sync ?

**Comment by daredevil-ferreira** [comment]
Bonjour,

Oui, j'ai essayé le résumé et je ne trouve que 1 seule combinaison on,off
et onoff.

J'ai essayer de regarder la documentation fournie pas Xiaomi, ils parlent
de channel_0 et de channel_1.

Sur ce site
https://github.com/home-assistant/home-assistant/blob/master/homeassistant/components/switch/xiaomi_aqara.py

Je vois qu'effectivement pour le modèle ctrl_ln2.aq1 ils ajoutent 2
devices, un pour chaque bouton/Channel.

David

**Comment by doudz** [comment]
Il serait intéressant d'avoir le fichier zigate.json pour voir comment l'équipement est reconnu
J'ai ce modèle mais je ne l'ai pas encore branché...

**Comment by daredevil-ferreira** [comment]
Bonjour,

 

Où puis-je trouver ce fichier ?

 

Il faut que je réinstalle l’interrupteur et que je cherche à refaire la synchro sous jeedom.

 

Dans tous les cas, sous jeedom, je n’avais qu’un device identifié. 

 

David

 

De : Sébastien RAMAGE <notifications@github.com> 
Envoyé : samedi 5 janvier 2019 08:32
À : Jeedom-Zigate/jeedom-plugin-zigate <jeedom-plugin-zigate@noreply.github.com>
Cc : daredevil-ferreira <daredevil.ferreira@gmail.com>; Author <author@noreply.github.com>
Objet : Re: [Jeedom-Zigate/jeedom-plugin-zigate] Interrupteur double Xiaomi (#100)

 

Il serait intéressant d'avoir le fichier zigate.json pour voir comment l'équipement est reconnu
J'ai ce modèle mais je ne l'ai pas encore branché...

**Comment by doudz** [comment]
Vous avez débranché l'interrupteur c'est ça ?
Sous Jeedom il est normal qu'il n'y ait qu'un device mais il devrait y avoir les commandes on, off et on2 , off2 par exemple

**Comment by doudz** [comment]
Autre solution pour nous fournir des infos, mettre le plugin en debug, relancer le démon et faire la synchro de l'équipement.
Puis poster ici le log

**Comment by daredevil-ferreira** [comment]
Bonjour, le log. Pour info au moment de l'association, je me retrouve avec 2 devices, 1 faisant fonctionner 1 bouton, 1 autre dont les fonctions on/off ne font rien

[zigate.log](https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/files/2730371/zigate.log)

**Comment by daredevil-ferreira** [comment]
[zigate.json.txt](https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/files/2738277/zigate.json.txt)

I found this .zigate.json file

**Comment by daredevil-ferreira** [comment]
Bonjour,

 

Je viens de réessayer, là il n’en crée qu’une mais avec les commandes on off qui correspondent au 2ème bouton uniquement.

**Comment by daredevil-ferreira** [comment]
J'aurais envie dans le fichier zigate.class.php d'ajouter un case 'onoff2' comme à la ligne 215 et produire des commandes on2 et off2
Qu'en dites-vous ?

**Comment by daredevil-ferreira** [comment]
Je viens de modifier le fichier zigate.class.php, cela marche très bien maintenant : j'ai bien un on/off/toggle et un on2/off2/toggle2.

J'ai vu qu'il existait aussi des boutons à 3 interrupteurs. Cela devrait marcher aussi.
Je vais voir maintenant comment avoir la photo de l'interrupteur et pas le carré bleu zigate.
[zigate.class.php.zip](https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/files/2799005/zigate.class.php.zip)

**Comment by doudz** [comment]
Merci pour cette contribution, je regarderai tout ça la semaine prochaine

**Comment by daredevil-ferreira** [comment]
Il suffisait de déposer un fichier jpg portant le nom du 'type' :-) pour avoir la belle image de mon double interrupteur
![lumi ctrl_ln2 aq1](https://user-images.githubusercontent.com/46318626/51803112-87f22700-2251-11e9-9199-81cc0d61e2fc.jpg)

**Comment by doudz** [comment]
Je propose une autre modification qui devrait résoudre le problème des commandes on/off/toggle
Pourrais-tu essayer cette modification ? il faudrait modifier la fonction preSave
```php
    public function preSave()
    {
        // We check if the name is not already used
        // if yes : remove the old one if it's the same logicalId
        // else we rename the new one
        $result = zigateCmd::byEqLogicIdCmdName($this->getEqLogic_id(), $this->getName());
        if (is_object($result)) {
            if ($this->getLogicalId() != $result->getLogicalId()) {
                $this->setName($this->getName() . $this.getConfiguration('endpoint'));
            }
            else {
                $result->remove();
            }
        }
    }
```

**Comment by yann44** [comment]
Bonjour,
J'essaye de me passer de la Gateway Xiaomi. J'ai 3 interrupteurs doubles et impossible de les utiliser.
Je suis débutant dans ce domaine, mais si je peux vous aider, n'hésitez pas à demander.

Merci pour tout!

**Comment by doudz** [comment]
@yann44 peux-tu me confirmer le "type"

**Comment by yann44** [comment]
il est identifié comme:

lumi.sensor_86sw2

**Comment by yann44** [comment]
c'est un interrupteur double qui marche sur pile
ref: WXKG02LM
