### ISSUE TITLE
Hue : Pas de mise à jour sans resync

### ISSUE THREAD

**Issue by tomredhot** [Jeedom-Zigate/jeedom-plugin-zigate#101]
Tout d'abord merci pour ce plugin! Vous êtes au top.
J'ai un petit probleme que je n'arrive pas à résoudre/comprendre.
Sur toutes mes ampoules Phillips HUE (LWB010), lors d'un changement de statut ou de luminosité via interrupteur HUE, le statut de l'ampoule ne s'update automatiquement pas dans jeedom. Je suis obligé de faire "resync", attendre 30s pour qu'enfin les infos se mettent à jour. 
Sur mes ampoules je n'ai pas du tout le problème, toutes les infos s'update dans jeedom en moins de 3s.
J'ai testé plusieurs intteruteurs, plusieurs ampoules, plusieurs procédure de couplage. Je sèche. 
Avez vous déjà croisé le soucis, Avez vous une astuce?
Merci beaucoup (et la bonne année!)

**Comment by doudz** [comment]
Bonjour, malheureusement oui c'est un problème connu, apparu dans les dernières mises à jour.
Le problème concerne d'ailleurs toutes les ampoules, peu importe la marque.
Ça sera résolu très prochainement, merci de votre patience

**Comment by doudz** [comment]
Si le problème persiste lorsque nous aurons déployé la lib 0.26 il faudra prévoir un polling pour rafraichir l'état

**Comment by loic69chy** [comment]
Bonjour
Est ce que cela a été corrigé car j'ai toujours le soucis. Tout est à jour et fraichement installé ?
merci
