### ISSUE TITLE
Resynchronisation équipement impossible + Retour état télécommande

### ISSUE THREAD

**Issue by sirius210** [Jeedom-Zigate/jeedom-plugin-zigate#103]
Bonjour,

Suite à la lecture de la doc de Jeedom, il y a encore plusieurs actions que je n'arrive pas à faire ou dont le résultat est souvent aléatoire. 

Plugin : 1.1.7
Lib : 0.24.2
Firmware : 3.0e

**Resynchronisation d'équipements**
Si ma compréhension est la bonne, suite à l'inclusion d'un équipement dans le réseau, il est nécessaire de resynchroniser l'équipement afin de l'identifier et d'y associer les différents paramètres. 

J'ai eu beaucoup de mal à resynchroniser les équipements visibles sur la capture d'écran ci-dessous et je n'y arrive pas pour certains ( ampoules GU10 Tradfri).
![image](https://user-images.githubusercontent.com/16427376/50919455-26ede500-1443-11e9-9a2f-b5dc42b4f6fc.png)

Je ne sais pas vraiment comment procéder afin de bien resynchroniser un équipement et obtenir les différentes infos le caractérisants. Doit-on absolution faire une synchro (depuis la page principale) lorsque la resynchronisation d'un équipement a été lancée ? Combien de temps prends une resynchronisation d'un équipement (j'ai un peu galéré avec les autres modules) ?  Les modules ont par exemple été ajoutés hier et j'ai déjà tenté plusieurs resynchronisations, reset zigate, ... sans aucun effet. 

Est-il possible que l'équipement ait été mal inclus dans le réseau et que la seule solution réside en un reset du module + nouvelle inclusion ?

**Récupération de la dernière commande envoyée par la télécommande**
La, je ne suis pas certain que ce soit possible mais suite à la lecture de cet article :  [http://faire-ca-soi-meme.fr/domotique/2018/03/14/une-telecommande-zigbee-pour-les-controler-tous/](url) je me dis que c'est théoriquement possible mais je ne sais pas si c'est prévu au niveau du module. 

En effet, j'ai besoin de la commande envoyée par la télécommande (que ce soit la simple télécommande ON/OFF vendue avec la prise Tradfri ou la télécommande 5 boutons) car je dois réaliser un scénario mêlant du Zigbee (Tradfri et éventuellement Xiaomi si j'arrive à mes fins) et du Z-Wave (dimmers dans mes blochets). 

Est-il donc possible de récupérer la dernière commande envoyée par une télécommande Tradfri et de réaliser un scénario dans Jeedom avec comme déclencheur la commande ? 

Merci d'avance pour les réponses apportées car si je ne peux récupérer la dernière commande envoyée, la télécommande ne me sert pas à grand chose.

**Comment by llaumgui** [comment]
Bonjour,

merci de poser les question sur le forum et les bugs sur GitHub. Là j'ai un peu de mal à suivre.
