### ISSUE TITLE
Provide a button to remove missing devices

### ISSUE THREAD

**Issue by smulle48** [Jeedom-Zigate/jeedom-plugin-zigate#104]
Hi

Hos do I exclude a device from ZiGate in Jeedom?

If I delete a device and then later sync, they show up again in Jeedom.

I can’t find any exclude button or command anywhere, or can I do it from terminal?

**Comment by doudz** [comment]
Hi,

There's two ways :
 - Reset the device : For example on a XIAOMI device, push the pair button for 5 sec, the device will leave the zigate and will be removed from jeedom (notice that the device will try to pair after leaving but since the zigate is not in permit join mode it's not a problem)
- Delete the device from Jeedom : When you do this, the zigate ask the device to leave, if the device answer then it is removed. Device running on battery must be awake to answer, by pushing one or more times on the pair button for example.

**Comment by smulle48** [comment]
Hi

I will try it again.

I tried yesterday to include a IKEA round dimmer, but after inclusion I could not connect it to the bulb.

I then tried to delete the dimmer and pressed the sync button (on the dimmer) once to wake up the dimmer

**Comment by doudz** [comment]
I think the best way to remove a device from zigate is the reset method

**Comment by llaumgui** [comment]
Can close ?

**Comment by smulle48** [comment]
Okay, so I just reset the dimmer, delete the device in Jeedom and then wait for it to “forget” the device?

**Comment by doudz** [comment]
After checking, I found a little problem :
Reseting the device should remove it from zigate and Jeedom, but in some case, if the zigate doesn't receive the "leave" message, the device will be still here, like a ghost. After some time the device will be tagged as "missing" internally and there a function called `cleanup_device` to remove missing devices.
The "problem" is currently there's no way to call `cleanup_device` from Jeedom.

So we have to improve a little to add a button to remove missing device

**Comment by smulle48** [comment]
Is it not possible to call it directly in core.py as the first thing in: 

def reset(self):

So when you push the reset button in Jeedom it then first cleanup the devices and then reset the zigate? :-)

**Comment by doudz** [comment]
But sometimes you may want reset the zigate only and not cleanup missing devices
the missing tag is just a supposed information,

**Comment by smulle48** [comment]
Ahh. Okay. I see :-) my bad

**Comment by doudz** [comment]
sure, I think you could create a scenario script and call `zigate::callZiGate("cleanup_devices")`

**Comment by doudz** [comment]
J'ai ajouté la commande, ça sera dispo dans une prochaine mise à jour
