### ISSUE TITLE
Pas de contrôle de la temperature des ampoules IKEA Tradfri

### ISSUE THREAD

**Issue by doudz** [Jeedom-Zigate/jeedom-plugin-zigate#105]
Le pilotage de la température de couleur des ampoules IKEA n'est pas possible avec la lib en version 0.24.*
C'est un problème connu et corrigé dans la version 0.26.*

Je crée ce ticket juste pour info, à clôturer lorsque la mise à jour sera publiée.

**Comment by llaumgui** [comment]
Question: possible en 1.1.x ? Où il faut attendre la 1.2 ?
