### ISSUE TITLE
switch Xiaomi  lumi.sensor_switch.aq2

### ISSUE THREAD

**Issue by yann44** [Jeedom-Zigate/jeedom-plugin-zigate#107]
Bonjour à Tous

j'ai un switch Xiaomi ( https://www.aliexpress.com/item/Xiaomi-Aqara-Smart-Wireless-Switch-Key-Intelligent-Application-Remote-Control-ZigBee-Wireless-Biult-in-Gyro-for/32950471459.html?spm=a2g0s.9042311.0.0.57774c4deFUMFp )reconnu sous:

lumi.sensor_switch.aq2

Dans la liste de commande, je ne trouve pas de on-off, donc, compliqué à faire fonctionner !!

![capture d ecran 2019-01-30 a 11 38 04](https://user-images.githubusercontent.com/26790806/51975993-e7377d80-2483-11e9-9f2b-8a6d29d90090.png)

mon ZiGate:

![capture d ecran 2019-01-30 a 11 26 52](https://user-images.githubusercontent.com/26790806/51976017-f7e7f380-2483-11e9-82a5-8415fffe1bbf.png)

Est-ce que quelqu'un peu m'aider à le faire fonctionner?

Merci d'avance pour votre patience !!!

**Comment by doudz** [comment]
Merci, as-tu essayé d'appuyer sur le bouton ? ça pourrait faire apparaitre les commandes manquantes

**Comment by yann44** [comment]
je viens de le supprimer, puis recréé, et des nouvelles commandes sont apparues, dont un on-off:

![capture d ecran 2019-01-30 a 14 00 18](https://user-images.githubusercontent.com/26790806/51982888-83b74b00-2497-11e9-924b-e05f50ec12da.png)

**Comment by doudz** [comment]
C'est parfait ! 
Comme le système est basé sur la découverte, certaines commandes n'apparaissent pas tant qu'elles ne sont pas utilisées

**Comment by yann44** [comment]
je viens de relancer mon scénario, et maintenant ça marche !!!!

**Comment by yann44** [comment]
merci beaucoup !!!

**Comment by doudz** [comment]
De rien

**Comment by thetrueavatar** [comment]
Pour info, j'ai le même souci. Mes aqara wireless switch(single rocker) sont reconnu comme des lumi.sensor_86sw1 et dès lors je n'ai pas d'action on/off. J'ai dissocier/réassocier fait 
 l'identification la détection/rafraîchissement de l'équipement en appuyant manuellement sur le bouton et en maintenant enfoncer comme pour l'appairage mais rien n'y fait. J'ai le cas pour 3 interrupteurs.
J'ai eu aussi un souci de détection pour mes Aqara Wall Switch avec neutre mais le rafraîchissement+pression bouton a correctement rajouté les commandes. 
Une idée pour forcer la bonne détection ?

**Comment by thetrueavatar** [comment]
Pour info dans le terminal je reçois une erreur lors de la détection de matériel:
`RESPONSE 0x8702 - APS Data Confirm Fail : status:240, source_endpoint:1, dst_endpoint:1, dst_address_mode:2, dst_address:2a44, sequence:75, lqi:0`
