### ISSUE TITLE
Volet profalux Commande info

### ISSUE THREAD

**Issue by antfleu** [Jeedom-Zigate/jeedom-plugin-zigate#113]
Bonsoir,

**Description du bug**
Depuis une énième coupure électrique, j'ai encore perdu mes devices Xiaomi. 
Du coup j'ai essayé de passé en 3.0f et commencé par réinclure un volet.
Les commandes actions  sont bien créées et fonctionnent sans problème (On, Off, Toggle...) par contre aucune commande info (level, power source...)

J'ai réinclus plusieurs fois, rafraîchit l'équipement, synchronisé avec la zigate rien.
J'ai aussi retenté un passage en 3.0e et 3.0d même résultat.

Aucun soucis avec un thermomètre Aqara par exemple

Je joins mon fichier zigate.json si cela peut aider (device ccd6)

[zigate.json.txt](https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/files/2829749/zigate.json.txt)

**Informations:**
 - Type de l'équipement : volet profalux
 - Version Jeedom Smart en 3.2.15
 - Version Plugin 1.1.7
- Version lib zigate 0.24.2

Merci par avance

**Comment by doudz** [comment]
Il faudrait faire un "refresh" sur l'équipement, je pense que ça devrait faire remonter les valeurs manquantes

**Comment by antfleu** [comment]
Bonsoir Doudz,

J'avais déjà tenter le refresh. Cela correspond bien à 'Resynchroniser l'équipement'?
Je suis passé en debug avec:
-inclusion
[inclusion.log](https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/files/2833703/inclusion.log)

-refresh
[refresh.log](https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/files/2833704/refresh.log)

- et refresh mouvement du volet et synchro avec la zigate
[refresh avec syncro de la zigate.log](https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/files/2833707/refresh.avec.syncro.de.la.zigate.log)

Merci à toi

**Comment by doudz** [comment]
J'ai oublié de préciser qu'il faut relancer le démon après le passage en debug car là le log ne contient pas les infos de debug du démon. Désolé j'aurai dû le préciser.

**Comment by antfleu** [comment]
Pas de problème, je refais ce soir
Merci

**Comment by antfleu** [comment]
Effectivement ça cause plus :)
[refresh.log](https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/files/2838398/refresh.log)

**Comment by doudz** [comment]
Ok, je vois le problème, la lib 0.24.2 est buggé...
@llaumgui qu'est-ce qu'on fait ? Est-ce que tu penses que la mise à jour sera prête rapidement ?
Sinon il faudrait que je sorte une 0.24.3 pour corriger le problème

**Comment by llaumgui** [comment]
J'aimerais passer en stable ce WE. Pour moi seul la doc et le cube sont bloquant.

**Comment by doudz** [comment]
ok bonne nouvelle alors, je vais essayer de voir pour le cube aujourd'hui ou demain

**Comment by antfleu** [comment]
Super, merci pour ce que vous faites. 
N’hésitez pas si je peux être utile pour tests ou autres.

**Comment by llaumgui** [comment]
En beta du coup

**Comment by antfleu** [comment]
Je viens de faire un refresh et toujours pas de commandes info.
Du coup install de la 3.0f + erase complet de l'eprom et toujours pareil.
Voici les logs 
-inclusion
[inclusion.log](https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/files/2856812/inclusion.log)
-Rafraîchissement
[rafraichissement.log](https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/files/2856814/rafraichissement.log)
-Découverte
[Découverte.log](https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/files/2856815/Decouverte.log)

Zigate.json

Merci par avance

**Comment by doudz** [comment]
Pourriez-vous lancer la commande "discover" sur cet équipement ?

**Comment by doudz** [comment]
Idéalement il faudrait être en mode debug (bien relancé le démon après avoir choisi debug) et poster ici le log

**Comment by antfleu** [comment]
J'ai fait plusieurs discover. 
Redémarrer le démon, même jeedom et je ne vois pas de commande 0x0120 
[discover.log](https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/files/2860985/discover.log)

**Comment by doudz** [comment]
J'ai trouvé un moyen de contourner le problème, ça sera bon sur la prochaine mise à jour

**Comment by antfleu** [comment]
Si vous voulez que je test un truc ou autre ne pas hésiter. 
Une fois encore merci pour le travail

**Comment by doudz** [comment]
https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/commit/1dee69a9f1a4b456b839af4e9fecd42f58d03891

**Comment by antfleu** [comment]
J’ai bien récupéré les commandes info avec la dernière releasee.  
Merci beaucoup 😀

**Comment by doudz** [comment]
Bonne nouvelle, merci pour le retour.
