### ISSUE TITLE
Problème de mouvement du cube

### ISSUE THREAD

**Issue by llaumgui** [Jeedom-Zigate/jeedom-plugin-zigate#114]
**Description du bug**
Avant mon passage en _develop_, les mouvements du cube étaient des strings qui avait un sens (double_tap_x, etc.).
Depuis mon passage en bêta, c'est des integer sans réel sens.

**Informations:**
 - Type de l'équipement: Cube Xiaomi
 - Version Jeedom: 3.2.15
 - Version Plugin: 1.2.0-b1
 - Version lib zigate: 0.27.3

**Comment by doudz** [comment]
Il y a eu des modifs à ce niveau là pour supporter les interrupteurs Xiaomi mais ça ne devrait pas impacter le cube. Est-ce que ton cube est bien défini ? le type notamment ?
Peux-tu fournir ton fichier zigate.json ?

**Comment by llaumgui** [comment]
Il est noté "lumi.sensor_cube" donc pour moi c'est OK. Je regarde ça se soir car j'ai pas accès au zigate.json depuis l'interface web.

**Comment by doudz** [comment]
ah c'est peut-être ça le souci, le mien est un lumi.sensor_cube.aqgl01

**Comment by doudz** [comment]
est-ce que ton cube à l'adresse 7b9a ?

**Comment by llaumgui** [comment]
Oui ? Comment tu sais ?
Pour le cube, on a 2 références : https://jeedom-zigate.github.io/jeedom-plugin-zigate/fr_FR/xiaomi

**Comment by doudz** [comment]
Je l'ai supposé d'après les infos que j'ai, car tu as coché la case permettant l'envoi de données :)

**Comment by doudz** [comment]
Normalement le device_id du endpoint 2 devrait être 0x5f02 et chez toi c'est 0
Tu pourrais utiliser le terminal pour rafraichir les infos du endpoint 2 ?
Commande : 0x0043
Data : 7b9a02
S'il apparait que c'est bien 0x5f02, ça corrigera automatiquement ton problème et j'ajouterai un template pour faciliter les choses à l'avenir.

**Comment by doudz** [comment]
Pour aller plus vite j'ai préparé la branche dev de la lib python, si tu veux tu peux installer directement la lib python pour voir si ça corrige ton problème
sudo pip3 install https://github.com/doudz/zigate/archive/dev.zip

**Comment by llaumgui** [comment]
Pour moi c'est le seul blocker a la stable car C'est une régression. Je test ça ce soir et on est bon !

**Comment by doudz** [comment]
ok, si tout est bon, je publierai la mise à jour

**Comment by llaumgui** [comment]
juste en faisant un pip install + restart service c'est pas mieux.

**Comment by llaumgui** [comment]
> 7b9a02



> Normalement le device_id du endpoint 2 devrait être 0x5f02 et chez toi c'est 0
> Tu pourrais utiliser le terminal pour rafraichir les infos du endpoint 2 ?
> Commande : 0x0043
> Data : 7b9a02
> S'il apparait que c'est bien 0x5f02, ça corrigera automatiquement ton problème et j'ajouterai un template pour faciliter les choses à l'avenir.

RESPONSE 0x8000 - Status response : status:0, sequence:194, packet_type:67, error:b'', rssi:0

**Comment by llaumgui** [comment]
@doudz > c'est bon, j'ai fait une réassociation, il a changé d'adresse, mais pas d'IEEE. Du coup il marche. Tu fait ta release, je soumets la beta on attend 2 jours et on pousse en stable ?

**Comment by doudz** [comment]
c'est fait.
Oui on fait comme ça, sauf si des problèmes sont signalés durant la beta

**Comment by llaumgui** [comment]
Malheureusement, tout le monde ne sait pas passer en beta... Et ceux qui savent remontent pas grand chose...

**Comment by doudz** [comment]
donc on passera en stable et voilà :)

**Comment by llaumgui** [comment]
Ca permet aussi de pouvoir gueuler sur ceux qui se plaignent ;-). Je ferais le changelog et la release demain, pour le moment je pousse une beta.
