### ISSUE TITLE
Documentation plus à jour

### ISSUE THREAD

**Issue by llaumgui** [Jeedom-Zigate/jeedom-plugin-zigate#115]
Avec la 1.2.0, plein de nouvelles features arrivent ! C'est cool mais du coup la documentation est en décalage, faudrait documenter les nouvelles fonctionnalités.

Voici une liste des choses a rajouter:

- [x] Network scan
- [x] Discover
- [x] Nettoyer
- [x] Erase PDM
- [x] Terminal
- [x] MAJ screenshots

**Comment by llaumgui** [comment]
@Deepcore93 > je crois que c'est pas mal des features à toi ? Au pire colle moi un laïus ici, je m'occupe de la mise en forme et de la génération de la doc.

@doudz > il y a aussi des fonctionnalités que tu as rajouté, tu peux m'en dire plus ? PAreil, je m'occuperais de la mise en forme.

**Comment by doudz** [comment]
Network scan : Pas nouveau mais toujours pas vraiment compris le but, peut-être pas utile
Discover : Anciennement appeler refresh : permet de découvrir les capacités d'un équipement
Refresh : Permet simplement de forcer la lecture des informations auprès de l'équipement
Nettoyer : Supprimer les équipements marqués "manquant" (les fantomes)
Erase PDM : Permet d'effacer la mémoire EEProm pour repartir à 0
Terminal : Permet d'envoyer des commandes brutes à la zigate https://zigate.fr/wiki/commandes-zigate/
Exemple, je veux faire un reset : commande = 0x0011 (et rien pour data)
Autre exemple je veux ajouter le groupe "abcd" à l'équipement "1234" sur son endpoint 3 : commande =0x0060 et data=0212340103abcd

**Comment by llaumgui** [comment]
Network scan : OK, c'est une commande Zigate: https://zigate.fr/wiki/commandes-zigate/

Erase PDM : On perd tout ? Si oui faut le mettre en gras :-).

**Comment by doudz** [comment]
J'ai ajouté une petite note concernant la commande nettoyer.
Oui pour Erase PDM, on perd tout, c'est le but

**Comment by Deepcore93** [comment]
Pour info sur la nouvelle page réseau ces commandes sont commentées.

**Comment by llaumgui** [comment]
>  Oui pour Erase PDM, on perd tout, c'est le but

Mais même dans Jeedom on perd tout ?
Ou alors il faut juste faire une ré association module par module ? Car sauf erreur de ma part c'est la procédure d'upgrade de firmware...

Du coup je mettrais :
> Erase PDM : Permet d'effacer la mémoire EEProm de la Zigate et donc de repartir à 0. Attention toutes vos associations côté Zigate seront perdues mais pas les équipements Jeedom correspondant. Il faudra rafraichir tout vos équipent pour recréer l'association avec la Zigate.

J'ai un doute sur le mot raffraichir...

**Comment by Deepcore93** [comment]
"Il faudra ré-associer tous vos équipements à la Zigate"

**Comment by doudz** [comment]
@llaumgui On ne perd pas tout dans Jeedom, ça efface le contenu interne de la zigate
Ensuite il faudra ré-associer comme le dit @Deepcore93
