### ISSUE TITLE
Mise à jour de la version minimale

### ISSUE THREAD

**Issue by llaumgui** [Jeedom-Zigate/jeedom-plugin-zigate#117]
Avec la 1.2.0, la question de la version minimale va se poser...

Soit on demande une 3.0e minimum dès la 1.2.1 soit on attend la sortie de la 3.0f. Le but étant de réduire les disparités.

**Comment by doudz** [comment]
je trouve que la 3.0e ne corrige pas un gros problème qui est la perte des XIAOMI, j'attendrai plutôt la 3.0f qui devrait bientôt arriver

**Comment by llaumgui** [comment]
En phase.

**Comment by llaumgui** [comment]
De même, je me pose la question de la pertinence de laisser le code de migration, qui a un impacte AMHA dans les performances après une certaine version.

**Comment by doudz** [comment]
Idéalement il faudrait savoir s'il reste des vieilles versions en prod.
Mais comme on ne peut savoir, le plus simple est de se dire qu'à la version 1.3.0 par exemple on vire la migration.
Mais en soit ça impacte peu les performances puisque la migration est faite en live :
- Lorsqu'un équipement doit être mis à jour => On cherche l'objet Jeedom:
  - On trouve l'objet, nickel on continue
  - On le trouve pas, on cherche alors avec l'ancien LogicalID
    - si on trouve => On migre
    - si on trouve pas => on crée

**Comment by llaumgui** [comment]
Je me suis juste fait la remarque lors du démarrage du daemon... Je trouve ça plus long.

**Comment by doudz** [comment]
https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/commit/2352c0bf0e447f3c052885657f02bdd3be998b7e

**Comment by doudz** [comment]
J'ai juste mis un message pour informer les utilisateurs qu'un nouveau firmware existe mais la version mini reste la 3.0d

**Comment by doudz** [comment]
Je pense qu'on peut rester comme ça pour le moment.
La version minimale reste 3.0d, on est compatible 3.0f.
Le jour où le bug des XIAOMI qui disparaisse sera complètement résolu, on fera monter la version
