### ISSUE TITLE
Télécommande ikea (5 boutons) information Batterie

### ISSUE THREAD

**Issue by Deepcore93** [Jeedom-Zigate/jeedom-plugin-zigate#119]
L'information n'est pas identifiée comme l'information batterie du module, donc cette information ne remonte pas sur la page Analyse/Equipements/Batterie

~~~
Extrait du json : 
    "devices": [
        {
            "addr": "2e2c",
            "discovery": "auto-discovered",
            "endpoints": [
                {
                    "clusters": [
                        {
                            "attributes": [
                                {
                                    "attribute": 5,
                                    "data": "TRADFRI remote control",
                                    "name": "type",
                                    "type": "str",
                                    "value": "TRADFRI remote control"
                                }
                            ],
                            "cluster": 0
                        },
                        {
                            "attributes": [
                                {
                                    "attribute": 32,
                                    "data": 26,
                                    "name": "battery_voltage",
                                    "value": 26
                                }
                            ],
                            "cluster": 1
                        }
                    ],
                    "device": 2096,
                    "endpoint": 1,
                    "in_clusters": [
                        0,
                        1,
                        3,
                        9,
                        2821,
                        4096
                    ],
                    "out_clusters": [
                        3,
                        4,
                        5,
                        6,
                        8,
                        25,
                        4096
                    ],
                    "profile": 49246
                }
            ],
            "generictype": "",
            "info": {
                "addr": "2e2c",
                "id": 4,
                "ieee": "d0cf5efffec2f87f",
                "last_seen": "2019-02-05 06:55:08",
                "mac_capability": "10000000",
                "power_type": 0,
                "rssi": 0
            }
        },
~~~

**Comment by doudz** [comment]
Effectivement, par contre la valeur est étrange 26 ? est-ce que réellement c'est 2.6V ?

**Comment by Deepcore93** [comment]
Je ne suis pas devant, je vois ça et je fais un retour

**Comment by Deepcore93** [comment]
Je confirme, la valeur correspond bien au voltage de la batterie, donc 2,6v. j'ai changé cette batterie pour une neuve et la valeur est passée à 31 soit 3.1v

**Comment by Deepcore93** [comment]
Je viens d'associer un télécommande ikea ronde, la j'ai même pas l'attribut batterie : 

        {
            "addr": "01e8",
            "discovery": "auto-discovered",
            "endpoints": [
                {
                    "clusters": [
                        {
                            "attributes": [
                                {
                                    "attribute": 0,
                                    "data": 1,
                                    "name": "zcl_version",
                                    "value": 1
                                },
                                {
                                    "attribute": 1,
                                    "data": 17,
                                    "name": "application_version",
                                    "value": 17
                                },
                                {
                                    "attribute": 2,
                                    "data": 87,
                                    "name": "stack_version",
                                    "value": 87
                                },
                                {
                                    "attribute": 3,
                                    "data": 30,
                                    "name": "hardware_version",
                                    "value": 30
                                },
                                {
                                    "attribute": 4,
                                    "data": "IKEA of Sweden",
                                    "name": "manufacturer",
                                    "value": "IKEA of Sweden"
                                },
                                {
                                    "attribute": 5,
                                    "data": "TRADFRI wireless dimmer",
                                    "name": "type",
                                    "type": "str",
                                    "value": "TRADFRI wireless dimmer"
                                },
                                {
                                    "attribute": 6,
                                    "name": "datecode",
                                    "value": null
                                },
                                {
                                    "attribute": 7,
                                    "data": 3,
                                    "name": "power_source",
                                    "value": 3
                                },
                                {
                                    "attribute": 10
                                },
                                {
                                    "attribute": 65533,
                                    "data": 1
                                },
                                {
                                    "attribute": 16384
                                }
                            ],
                            "cluster": 0
                        },
                        {
                            "attributes": [
                                {
                                    "attribute": 0,
                                    "data": 0
                                },
                                {
                                    "attribute": 65533,
                                    "data": 1
                                }
                            ],
                            "cluster": 3
                        }
                    ],
                    "device": 2064,
                    "endpoint": 1,
                    "in_clusters": [
                        0,
                        1,
                        3,
                        9,
                        2821,
                        4096
                    ],
                    "out_clusters": [
                        3,
                        4,
                        6,
                        8,
                        25,
                        4096
                    ],
                    "profile": 49246
                }
            ],
            "generictype": "",
            "info": {
                "addr": "01e8",
                "ieee": "000b57fffe2f9566",
                "last_seen": "2019-02-08 07:52:37",
                "mac_capability": "10001100",
                "rssi": 117
            }
        },

**Comment by doudz** [comment]
Avec le nouveau terminal, peux-tu essayer la commande suivante :
commande : 0x0120
data : 0201e80101000100000000010021

c'est pour configurer la remontée automatic du pourcentage de batterie

**Comment by Deepcore93** [comment]
C'est fait, voici le retour 👍 
RESPONSE 0x8000 - Status response : status:0, sequence:62, packet_type:288, error:b'', rssi:0
RESPONSE 0x8702 - APS Data Confirm Fail : status:212, source_endpoint:1, dst_endpoint:1, dst_address_mode:2, dst_address:0x1e80, sequence:44, rssi:159
RESPONSE 0x8701 - Route Discovery Confirmation : status:208, network_status:0, rssi:0

**Comment by doudz** [comment]
Il faut penser à réveiller la télécommande

**Comment by Deepcore93** [comment]
on parle de la ronde ou de la 5 boutons ?

**Comment by doudz** [comment]
de la ronde, avec l'adresse 01e8, tu peux le faire aussi sur l'autre en changeant l'adresse dans la commande 
commande : 0x0120
data : 02**01e8**0101000100000000010020002100010e100000

**Comment by Deepcore93** [comment]
J'ai toujours le même retour :
RESPONSE 0x8000 - Status response : status:0, sequence:73, packet_type:288, error:b'', rssi:0
RESPONSE 0x8702 - APS Data Confirm Fail : status:212, source_endpoint:1, dst_endpoint:1, dst_address_mode:2, dst_address:0x1e80, sequence:55, rssi:159
RESPONSE 0x8701 - Route Discovery Confirmation : status:208, network_status:0, rssi:0

Je suis sensé avoir quel résultat ?

**Comment by doudz** [comment]
J'ai fait une petite erreur, la commande est : 0201e80101000100000000010020002100010e10000000

**Comment by Deepcore93** [comment]
Toujours pareil (nb l'adresse a changée car je suis repartie de zéro)

RESPONSE 0x8000 - Status response : status:0, sequence:100, packet_type:288, error:b'', rssi:0
RESPONSE 0x8702 - APS Data Confirm Fail : status:212, source_endpoint:1, dst_endpoint:1, dst_address_mode:2, dst_address:0x77d4, sequence:88, rssi:159
RESPONSE 0x8701 - Route Discovery Confirmation : status:208, network_status:0, rssi:0

**Comment by doudz** [comment]
corrigé en develop

**Comment by llaumgui** [comment]
Cool par contre ça ira en 1.2.1 car sinon on ne releasera jamais...

**Comment by Deepcore93** [comment]
@doudz : je regarde ça merci
