### ISSUE TITLE
Le démon crash au premier démarrage après le flashage

### ISSUE THREAD

**Issue by doudz** [Jeedom-Zigate/jeedom-plugin-zigate#126]
**Description du bug**
Le démon crash au premier démarrage après le flashage

**Pour Reproduire**
Etapes pour reproduire le problème:
1. Flasher le firmware et effacer l'EEProm
2. Démarrer
3. Crash

**Informations:**
- Version lib zigate : 0.27.7

**Comment by doudz** [comment]
Fix avec 0.27.8

**Comment by doudz** [comment]
https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/commit/9a7f99ce94eba6c967ac2f90f6f5e93bde2abd2d

**Comment by llaumgui** [comment]
La 1.2.0 est déjà out .. Du coup la 1.2.1 sera rapide 😀

**Comment by doudz** [comment]
;)

**Comment by doudz** [comment]
Je pense qu'il faudra pas trainer d'ailleurs pour sortir la 1.2.1, je dirai même que ça serait bien de la mettre en beta dès demain

**Comment by llaumgui** [comment]
En beta
