### ISSUE TITLE
Pas de synchro automatique on off TRADFRI bulb E27 opal 1000lm

### ISSUE THREAD

**Issue by nono2032** [Jeedom-Zigate/jeedom-plugin-zigate#127]
Depuis les dernières mise a jour 3.0f et plugin 1.2.0 j'ai bien pu inclure cette ampoule et la piloter par contre on ne voit plus sur le dashboard si l'ampoule est allumer ou éteinte sans appuyer sur resync, le level d'intensité se syncronise automatiquement sans resync, dans la version précédente du plugin et le firmware 3.0e cela fonctionnait.

**Comment by doudz** [comment]
idem, merci de lancer la commande discover sur l'équipement ça devrait résoudre le problème

**Comment by nono2032** [comment]
Le bouton discover à été appuyer également sans résoudre le problème,  par ailleurs si je débranche électriquement l ampoule et le remet sous tension,  je n arrive plus du tout à la piloter

**Comment by doudz** [comment]
woo.
si l'ampoule est pilotable et ne l'ai plus après l'avoir juste débrancher/rebrancher, sans rien toucher côté zigate/jeedom alors je vous invite à ouvrir un issue sur https://github.com/fairecasoimeme/ZiGate/issues car ça ressemble à un problème de firmware zigate

**Comment by nono2032** [comment]
Ok j ai ouvert un issue.

**Comment by nono2032** [comment]
Alors j'ai retenter l'inclusion de cette ampoule et cette fois c'est bon, même après coupure de courant je peux à nouveau la piloter, par contre le problème de la mise a jour du statut on off et maintenant également le level de l'intensité ne se synchronise pas sans appuyer sur la touche resync.  la touche discover n'a pas régler le problème dans mon cas.  je vais mettre le log en debug pour cette equipement aussi

**Comment by nono2032** [comment]
`[2019-02-13 21:15:28][DEBUG] : callZiGate discover_device Array (     [0] => 6cd8 ) 
[2019-02-13 21:15:28][DEBUG][root](Thread-4) : Message received in socket
[2019-02-13 21:15:28][DEBUG][root](Thread-4) : {'action': 'discover_device', 'args': ['6cd8']}
[2019-02-13 21:15:28][DEBUG][root](Thread-4) : {'result': None, 'success': True}
[2019-02-13 21:15:28][DEBUG] : result callZiGate Array (     [result] =>      [success] => 1 ) 
`

**Comment by doudz** [comment]
log trop court, il faut la suite

**Comment by nono2032** [comment]
pourtant cela m'affiche que cela après l’appuie sur discover, bon je retente

**Comment by nono2032** [comment]
voila je viens de retenter et j'ai toujours exactement ces même lignes,  ou je fais faux la manipulation ?

**Comment by doudz** [comment]
ok je viens de voir un bug sur cette fonction.
En attendant il faudrait créer un scénario script et placer la commande suivante :
`zigate::callZiGate('discover_device', ['6cd8', true]);`
où 6cd8 est l'adresse de l'équipement, à adapter si besoin

**Comment by nono2032** [comment]
c'est un bug du plugin ? cela va être corriger dans les prochaines version ? D'ailleurs maintenant l 'ampoule est à nouveau plus pilotable et je n'ai pas eu de coupure de courant, a nouveau perdu et rien y fait même en discover et rafraichissement.

**Comment by doudz** [comment]
oui la commande discover du plugin est buggé, ça sera corrigé rapidement

**Comment by nono2032** [comment]
du coup je vais attendre pour continuer mes inclusions. par contre est-ce que on sait pourquoi l'équipement est perdu par la suite ?

**Comment by nono2032** [comment]
j'ai rebrancher l'ampoule et je l'ai retrouver dans mes équipement à nouveau sans devoir l'inclure... je précise que je l'avais effacer entre temps pour tenter justement de la ré inclure.  et la je la retrouve sans nom et elle est pilotable pour le moment ;-) (sans retour d'état automatique)

**Comment by doudz** [comment]
https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/commit/1dee69a9f1a4b456b839af4e9fecd42f58d03891

**Comment by nono2032** [comment]
je rouvre ce ticket car la sychro ne se fais toujours pas de manière automatique.

**Comment by nono2032** [comment]
[discover.txt](https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/files/2868983/discover.txt)

**Comment by nono2032** [comment]
pareil ici, les logs de découvrir l'équipement.

**Comment by nono2032** [comment]
stop, cet équipement est ok maintenant !  je viens de réessayer et il se synchronise en direct donc cale fonctionne !!!
