### ISSUE TITLE
[FR] Ajouter la possibilité d'afficher le contenu du fichier zigate.json

### ISSUE THREAD

**Issue by doudz** [jeedom-zigate/jeedom-plugin-zigate#128]
tout est dans le titre :)
c'est pour faciliter les échanges avec les utilisateurs en cas de problème
il ne s'agit pas d'avoir un editeur de texte, juste une fenêtre modal qui afficherait le contenu du fichier

**Comment by llaumgui** [comment]
J'y avait pensé aussi :-)

**Comment by Deepcore93** [comment]
Je m'y colle
