### ISSUE TITLE
La fonction discover ne fonctionne pas

### ISSUE THREAD

**Issue by doudz** [Jeedom-Zigate/jeedom-plugin-zigate#130]
déjà corrigé en develop, mais à mettre en prod rapidement, désolé...

**Comment by llaumgui** [comment]
Le truc c'est que ça requière la 3.0f sans laisser trop de temps au gens... Soit on revert ça soit je cherry pick.

**Comment by nono2032** [comment]
je suis en 3.0f  pour info

**Comment by doudz** [comment]
pourquoi tu dis que ça requiert la 3.0f ?

**Comment by llaumgui** [comment]
La branche develop requière la 3.0f... Du coup si on pousse en master sans faire gaffe on va embarquer un peu tôt à mon goût cette exigence.

**Comment by doudz** [comment]
Si tu fais référence à https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/commit/2352c0bf0e447f3c052885657f02bdd3be998b7e c'est juste un message, ça n’empêche pas l'utilisation des précédents firmware

**Comment by doudz** [comment]
https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/commit/1384a7749c91201c10d679ea72290603fa87bf37
