### ISSUE TITLE
Même matériel mais pas les mêmes commandes

### ISSUE THREAD

**Issue by Amigagame** [Jeedom-Zigate/jeedom-plugin-zigate#131]
J'ai plusieurs capteurs LUMI SENS (température / Humité), les ronds, acheté tous en  même Temp chez le même vendeur.

Lorsque je fais les inclusions, je n'ai pas toujours les mêmes commandes (dans le cas ci dessous c'est ROTATION qui apparait sur le second et pas le premier)

Exemple avec deux matériels

le premier

Type : lumi.sens
Manufacturer : LUMI

Commandes

#		Nom		
1008	application_version
2474	discover
1019	humidity 
1014	battery
1017	temperature
1013	datecode
1016	description
1010	hardware_version
1011	manufacturer 
_1018	movement
1020	movement2_
1015	power_source
992		resync	 
1009	stack_version
1012	type
1007	zcl_version

Le second

Type : lumi.sens
Manufacturer : LUMI

Commandes

#		Nom
2285 	application_version
2494	discover
2296	humidity
2291	battery
2294	temperature
2290	datecode 
2293	description
2287	hardware_version
2288	manufacturer
2295	movement
2297	movement2
2292	power_source
2299	resync
**2298	rotation**
2286	stack_version
2289	type
2284	zcl_version

De plus, les commandes ROTATION / RESYNC / MOVEMENT et MOVEMENT2 sont mis en 'afficher' alors que je n'ai jamais de modification de valeurs ici (est ce un bug du plugin/firmware ou ce sont des valeurs qui doivent changer sur ce type de capteur ?

**Fonctionnement attendu**
Pour moi, par défaut, seules les commandes Humidity et Temperature devraient être en 'afficher', par défaut lors de l'inclusion

**Informations:**
- Type de l'équipement : lumi.sensor
- Version Jeedom : 3.2.16
- Version Plugin : 1.2.0
- Version lib zigate : 0.27.5
- Version du firmware : 3.0e

**Comment by doudz** [comment]
ça sera amélioré dans la lib 0.28 https://github.com/doudz/zigate/commit/385eea4bfcbe3fd053304333197869a9a4d7b14d

**Comment by Amigagame** [comment]
@doudz : Désolé, je pensais que c'était déjà résolu en 0.27 vu le ticket https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/issues/96

Une réinclusion hier m'a refait les mêmes commandes 'inutiles'

**Comment by doudz** [comment]
On est pas sur le même matériel, là c'est lumi.sens et l'autre lumi.sensor_ht
Xiaomi aime bien mettre plusieurs variantes...
