### ISSUE TITLE
Ampoules lumi.light.aqcn02

### ISSUE THREAD

**Issue by Amigagame** [Jeedom-Zigate/jeedom-plugin-zigate#133]
**Description du bug**
Difficulté à linker les ampoules avec la Zigate
Commandes manquantes
Identification manquante
Icone manquant

**Pour Reproduire**
J'essaye d'inclure mes deux ampoules à la ZIGATE
Passage en mode inclusion
Allumage / Extinction 5 fois de l'ampoule (l'ampoule clignote indiquant la mise en inclusion)
Certains fois le périphérique est reconnu mais le manufacturer est vide. Par contre il arrive (pas tout le temps) que  le type soit bien renseigné (lumi.light.aqcn02). Certaines fois les deux manques.

Les commandes redescendent bien (quand le type est présent) mais certaines avec des noms étranges

1_6_61440
1_768_61440
1_8_61440

là encore, certaine fois le bouton identifier fait bien clignoter l'ampoule, des fois non (ca depend là encore si le type est présent ou pas)
Quand le bouton identifier fonctionne, et que je vais sur la tuile

on / off fonctionnent
Toggle fonctionne
intensité fonctionne
Température, elle fonctionne UNE seule FOIS et ensuite le fait de bouger le slide ne change plus la temperature du tout.

J'ai un link qualité de 81 (est ce mauvais pour l'inclusion et générateur de ce type de problème ?)

L'image de l'équipement reste sur ZIGATE (mais vu que le constructeur n'est pas renseigné, je pense que cela vient de là, à me confirme)

**Informations:**
- Type de l'équipement : lumi.light.aqcn02
- Version Jeedom : 3.2.16
- Version Plugin : 1.2.1
- Version lib zigate : 0.27.8
- Version du firmware : 3.0e

**Comment by nono2032** [comment]
@llaumgui c'est du Xiaomi comme matériel il me semble

**Comment by doudz** [comment]
Il est fort probable que le problème soit résolu dans la version 1.2.2

**Comment by llaumgui** [comment]
Version qui doit être dispo sur le marcket.

**Comment by Amigagame** [comment]
ok je contrôle ce soir et je vous confirme la résolution (ou pas) :)
Merci pour votre boulot et votre réactivité en tout cas.

**Comment by Amigagame** [comment]
> Version qui doit être dispo sur le marcket.

Par défaut, si je n'ai pas de consigne, je considère que je n'ai ni besoin de faire une nouvelle inclusion, ni de modifier ou supprimer l'équipe existant. Est ce bien cela ?

**Comment by doudz** [comment]
Éventuellement il faudra juste cliquer sur le bouton découverte

**Comment by Amigagame** [comment]
@doudz  : Merci pour votre retour. 

Je vais peut être être chiant et j'en suis désolé mais que dois je constater avec la 1.2.2 ?

La disparition des commandes 1_6_61440, 1_768_61440, 1_8_61440 ?
Le bon fonctionnement du slider de température ?
L'apparition du manufacturer ?

Parceque pour l'instant je ne sais pas quoi tester pour vous faire une véritable remontée pertinente.

**Comment by doudz** [comment]
Les commandes 1_6_61440, 1_768_61440, 1_8_61440 sont là simplement parce qu'elles ont été découvertes mais comme elles ne sont pas gérées elles n'ont pas de nom, car je ne sais pas ce que c'est, il ne faut pas en tenir compte, sauf si les infos contenues sont utiles.
Le manufacturer vide, ce n'est pas important, c'est juste une info.
Pour que l'image, il faut qu'on l'ajoute, là encore c'est juste une info.
Le slider température est supposé fonctionner oui

Donc si je résume les problèmes :
- Pas d'image
- ON / OFF / TOGGLE : OK
- Remontée de l'état onoff : OK
- Level : OK
- Remontée Level : OK
- Température : fonctionnement aléatoire
- Remontée température : ?

A tout hasard, est-ce que le réglage de la température fonctionne si on reste dans la zone centrale, c'est à dire sans aller à fond à droite ou à gauche ? Il est possible que certaines valeurs ne soient pas supportées et fasse "planter" l'ampoule. (ou bug dans les valeurs envoyés à l'ampoule)

**Comment by doudz** [comment]
Par ailleurs il y a peut être un problème avec la gestion de la température en général, peut-être en lien avec https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/issues/68

**Comment by Amigagame** [comment]
@doudz 

Pour l'instant je suis à distance, donc je ne peux pas contrôler le bon fonctionnement en visuel.

Pour l'image je peux fournir, j'en ai fait plusieurs sur un Widget (on / off et plusieurs pour la température)

Pour les 3 commandes étranges, (ici je vais parler que de la première) j'ai ceci dans les infos

{"addr":"80e5","ieee":"00158d0002d71b48","endpoint":1,"cluster":6,"attribute":61440,"minValue":"","maxValue":""}

Impossible de savoir à quoi ells sert. 

Pour la température, c'est étrange, hier soir quand j'allais à gauche ou à droite, la température en retour passait bien de 1700 (à gauche) à 6500 (à droite)

La première manip a bien changé la température, la seconde non (mais juste physiquement) ... car la valeur retour continue à bien changer.

**Comment by Amigagame** [comment]
@doudz 

Le slider de temperature ne change rien

ON OFF : OK
Slider intensité : OK
Les valeurs retours intensite et temperature : OK (et changent quand je slide l'intensité ou la temperature)
Le slider Temperature : KO physiquement (la temperature ne change pas)

**Comment by doudz** [comment]
Serait-il possible de mettre le démon en debug (bien penser à relancer le démon après le changement) et de tenter de changer la température puis de poster ici le contenu du log ?
ça pourrait me permettre de voir ce qui cloche

pour info la même commande fonctionne sur les ampoules IKEA

**Comment by Amigagame** [comment]
Voici le contenu du log

Le device est 

Device 00158d0002d71b48(80e5)
lumi.light.aqcn02

J'ai fait un TOGGLE puis une baisse d'intensité, une montée d'intensité (les deux au max) ensuite j'ai modifié la température à environ 80% du slide et à 20% du slide, aucune modification physique mais le retour a bien pris les valeurs correspondantes.
 
[logszigate.txt](https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/files/2871937/logszigate.txt)

**Comment by Amigagame** [comment]
@doudz : Je viens de remarquer qqchose. Quand on associe l'ampoule, le slider va de 1700 à 6500, hors je vois sur le site de Xiaomi que l'ampoule va de 2700K à 6500K

Est ce problématique pour toi ?

**Comment by doudz** [comment]
ça ne pose aucun problème, simplement le slider ne fera rien sur une petite portion car la valeur sera en dessous de 2700K
Par ailleurs la valeur de 1700 est plus ou moins arbitraire, il faudrait vérifier si aucune ampoule du marché ne descend si bas on pourra remonter la limite.
Les philips HUE vont de 2000 à 6536 par exemple

**Comment by Amigagame** [comment]
Je viens de passer en beta 1.2.3b2.

Detection ampoule ok
Image ok
Commandes ok
La tuile avait bien les bonnes commandes, la température et l'intensité ont fonctionné plusieurs fois puis ... plus rien (comme si l'ampoule ne réagissait plus), plus possible de faire de modification, ni de on, ni de off. QQchose à faire @doudz ??

**Comment by Amigagame** [comment]
Suppression de l'équipement, reassignation, l'ampoule fonctionne. Je l'éteint par le off, je la rallume. Je l'éteint de nouveau. Ce matin la lampe ne s'allume plus sauf à l'interrupteur, Zigate a 'perdu' la connexion ? cc @doudz 

dois je ouvrir un nouveau bug ?

**Comment by doudz** [comment]
Il serait intéressant d'avoir les log en mode debug quand ça marche et quand ça marche

**Comment by doudz** [comment]
Attention ne pas oublier de relancer le démon lorsqu'on change le niveau de log

**Comment by doudz** [comment]
Quelle est la version du firmware zigate ?

**Comment by Amigagame** [comment]
Bonjour @doudz, je suis en version 3.0e pour l'instant car j'ai compris qu'il fallait ensuite que je refasse tous mes équipements (donc mes thermostats etc ...), j'ai pas encore eu le temps.

Pour les logs en debug, j'ai tout, par contre y a tout tout tout :) je le post ici ?

**Comment by doudz** [comment]
On s'arrêté là pour le moment.
Le firmware 3.0e est connu pour perdre des équipements de façon aléatoire à cause d'un problème mémoire. Je pense que c'est ce qu'il se passe ici puisque subitement l'ampoule ne semble plus appairé avec la ZiGate.

Il faudrait donc passé en 3.0f et voir si le problème persiste.

**Comment by Amigagame** [comment]
Ok pas de soucis, si le FW 3.0f est nécessaire pour qu'on puisse vous aider, je le fais demain dans la journée. Merci à vous :)

**Comment by Amigagame** [comment]
Allez je viens donner des nouvelles :) 

La bonne c'est que l'intensité et la température, ca fonctionne ! Merci :)
La mauvaise (enfin bon) c'est que la valeur de la colorimétrie n'est plus remontée (j'ai bien l'intensité mais pas le retour avec la température)

**Comment by doudz** [comment]
Plus remontée, donc ça marchait avant ? Il faut recliquer sur découverte ça devrait corriger le pb

**Comment by Amigagame** [comment]
@doudz Oui autant le slider de la température était ko, autant les retours de valeurs fonctionnaient bien. Celui du retour de l'intensité fonctionne, pas celui de la température (la jauge). Je vais essayer une nouvelle découverte. Par contre le reste de mes équipements fonctionnement parfaitement que ce soit les capteurs de température, les boutons, les ampoules. J'attends mes detecteurs de portes / fenetres

**Comment by Amigagame** [comment]
Bon j'ai ressayé, toujours KO

Pas de date de collecte ou de date de valeur, la jauge reste à zéro.

**Comment by doudz** [comment]
Je suis pas sûr suivre, si je résume tout fonctionne sauf la rémontée de la température qui n'a **jamais** fonctionné ?

**Comment by Amigagame** [comment]
Tout fonctionne, sauf la remontée de température qui fonctionnait AVANT la beta en 1.2.2

**Comment by doudz** [comment]
Je viens de vérifier le code et tout semble ok, le seul bug que je constate est que l'unité de valeur qui doit remonter dans colour_temperature est en mired, donc qui varie de 153 à 500 alors que la commande est en kelvin variant de 2000 à 6535.

Il faudrait:
- lancer le démon en mode debug
- modifier la température de la couleur
- poster ici le log

**Comment by doudz** [comment]
En écrivant ces lignes, je pense avoir trouvé le problème, sur colour_temperature le mini était fixé à 1700 car supposé des kelvin mais comme la valeur remontée est en mired soit entre 153 et 500, la jauge reste à 0.
Je corrige la beta dans ce sens, à tester.

**Comment by Amigagame** [comment]
Super :) Tu me dis quand est ce que je peux updater la beta ! 
Bravo pour le travail fourni en tout cas, je pensais virer la Zigate, tu m'as fait changer d'avis :)
J'ai mes détecteurs de portes et d'intensité lumineuse qui arrive bientôt ;)

**Comment by doudz** [comment]
La beta est dispo sur github donc en théorie demain sur le market jeedom

**Comment by Amigagame** [comment]
Ok parfait !

**Comment by Amigagame** [comment]
J'ai mis à jour en beta, pas de changement (j'ai toujours une valeur min et max de 1700 et 6500 dans les commandes sur la ligne temperature), dois je reassocier (plutôt embettant car c'est super chiant sur ces ampoules), redecouvrir ? raffraichir ?

**Comment by doudz** [comment]
Il faudrait supprimer la commande colour_temperature (attention juste cette commande, pas l'objet entier) et refaire une synchro, tout devrait rentrer dans l'ordre, la commande sera recréée correctement

**Comment by Amigagame** [comment]
j'ai supprimé, j'ai fait un "rafraichir"
La commande revient, toujours avec 1700 et 6500 dans les valeurs min et max
Sur la tuile, tout fonctionne, mais la temperature ne remonte toujours pas (je n'ai ni valeur ni date de collecte)

**Comment by doudz** [comment]
Petite erreur, c'est la commande info "temperature" qu'il faut supprimer, désolé

**Comment by doudz** [comment]
Je vois pas comment c'est possible, ces valeurs n'existent plus dans la dernière beta
Elles sont définies dans le fichier zigate.class.php aux lignes 442 à 445
https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/blob/beta/core/class/zigate.class.php#L442-L445

**Comment by doudz** [comment]
Est-ce que je peux avoir des captures d'écran ?

**Comment by Amigagame** [comment]
la derniére beta pour toi c'est la version combien ? j'ai un doute maintenant

**Comment by doudz** [comment]
La dernière est celle présente sur le market Jeedom soit 1.2.3-b4

**Comment by Amigagame** [comment]
it works ! Effectivement le plugin n'était pas à jour. 
Bon c'est un peu troublant d'avoir un retour qui n'est pas en kelvin mais ca marche et c'est super !

Pi je n'ai pas eu à supprimer la commande juste après la maj en 1.2.3b4, les valeurs min et max étaient bien à jour

**Comment by doudz** [comment]
Parfait, on va pouvoir passer la 1.2.3 en prod, merci :)

**Comment by Amigagame** [comment]
Merci à toi !!!
