### ISSUE TITLE
Update 1.2.2 & Upgrade .3.0f - nothing working

### ISSUE THREAD

**Issue by elarochejoubert** [Jeedom-Zigate/jeedom-plugin-zigate#138]
**Description du bug**
I'm not sure if the problem is from the plugin or the zigate key itself.
I updated the plugin which after installation asked me to upgrade my zigate firmware. 
So I removed the zigate key, upgrade the zigate to 3.0f which went very well.
Replugged the zigate key, restarted everything and everything looked perfect !!
BUT when I use the actions, nothing happens.
I tried removing & reassociating and nothing happens (so I don't see my devices anymore).
So I tryied a new device that I justed received today and it is impossible to include it with jeedom :(

I have osram smart+ plugs and xiaomi switches or sensors.
I went to "santé zigate" and I can see that all devices stopped communicating at the time of the update & upgrade.

I don't know what to do..........

**Informations:**
- Type de l'équipement : OSRAM Smart+ Plug 01, lumi.sensor_switch, lumi.sensor_magnet
- Version Jeedom : 3.2.16
- Version Plugin : 1.2.2 (2019-02-15 02:13:15)
- Version lib zigate : 0.27.9
- Version du firmware : 3.0f

**Comment by smulle48** [comment]
As the readme states, you have to erase the EEPROM or PDM = You have to setup everything from scratch again

https://github.com/fairecasoimeme/ZiGate/releases/tag/Release

**Comment by elarochejoubert** [comment]
Yes I did try that without any success.
I finally found the workaround. The bug look like beeing the sync between the plugin and the key.
I had to reinstall the plugin from scratch. That solved everything. Worth documentation ;)
