### ISSUE TITLE
Hue E27 Color pas de changement de couleur

### ISSUE THREAD

**Issue by Deepcore93** [Jeedom-Zigate/jeedom-plugin-zigate#142]
Tout semble fonctionner sauf le changement de couleur.
retour sur le log : 
callZiGate action_move_hue_hex Array (     [0] => c52e     [1] => 11     [2] => #fc141a )

Zigate.json : 

        {
            "addr": "c52e",
            "discovery": "",
            "endpoints": [
                {
                    "clusters": [],
                    "device": 97,
                    "endpoint": 242,
                    "in_clusters": [
                        33
                    ],
                    "out_clusters": [
                        33
                    ],
                    "profile": 41440
                },
                {
                    "clusters": [
                        {
                            "attributes": [
                                {
                                    "attribute": 5,
                                    "data": "LCT010",
                                    "name": "type",
                                    "type": "str",
                                    "value": "LCT010"
                                }
                            ],
                            "cluster": 0
                        },
                        {
                            "attributes": [
                                {
                                    "attribute": 0,
                                    "data": true,
                                    "name": "onoff",
                                    "type": "bool",
                                    "value": true
                                }
                            ],
                            "cluster": 6
                        }
                    ],
                    "device": 528,
                    "endpoint": 11,
                    "in_clusters": [
                        0,
                        3,
                        4,
                        5,
                        6,
                        8,
                        768,
                        4096,
                        64513
                    ],
                    "out_clusters": [
                        25
                    ],
                    "profile": 49246
                }
            ],
            "generictype": "",
            "info": {
                "addr": "c52e",
                "ieee": "00178801027aaada",
                "last_seen": "2019-02-21 21:00:29",
                "mac_capability": "10001110",
                "rssi": 132
            }
        },

**Comment by doudz** [comment]
il y a quoi dans le log ?

**Comment by Deepcore93** [comment]
Comme dit plus haut, pas grand chose : 
2019-02-21 21:43:26][DEBUG] : callZiGate action_move_colour_hex Array (     [0] => c52e     [1] => 11     [2] => #ff0000 )
[2019-02-21 21:43:26][DEBUG] : result callZiGate

**Comment by doudz** [comment]
ok, ça sera corrigé avec la lib 0.28.2

**Comment by Deepcore93** [comment]
Juste pour confirmer que ca marche ! :D 👍
