### ISSUE TITLE
Pas de mesure de puissance Prise Xiaomi smart plug ZNCZ02LM

### ISSUE THREAD

**Issue by nono2032** [Jeedom-Zigate/jeedom-plugin-zigate#145]
Version plugin
1.2.2
Version lib
0.27.9
Version firmware
3.0f 

![image](https://user-images.githubusercontent.com/47389767/53292669-c0d8d980-37c6-11e9-85f0-40b6918b4fc3.png)

je n'ai aucune donnée de consommation en watt.  

le reste fonctionne très bien.

Quel log dois-je te fournir ?

**Comment by doudz** [comment]
Est-ce que ça fonctionne avec la 1.2.3 en beta ?

**Comment by nono2032** [comment]
Je vais tenter tout à l'heure et te redis.

**Comment by nono2032** [comment]
Hello, alors j'ai passer en bêta 
Version plugin
1.2.3
Version lib
0.28.2
Version firmware
3.0f 

J'ai tenter un découvrir l'équipement, puis identifier et pour terminer un refresh.

Malheureusement cela n'a ajouter aucune commande affichant la consommation.

**Comment by doudz** [comment]
Est-ce que je pourrais avoir des captures d'écrans des commandes créées pour cet objet ?

**Comment by doudz** [comment]
à tout hasard, la consommation serait pas dans la valeur "rotation"  ?

**Comment by nono2032** [comment]
Alors j avoue que les commandes rotations je ne vois pas à quoi elles servent,  les seules fois ou elle affiches quelques chose c est en faisant on ou off ou refresh,  par contre cela affiche quelque chose et reviens a zéro immédiatement

**Comment by nono2032** [comment]
Il y a une commande power_source qui est présente mais non afficher,   en l affichant c est just écris power_source

**Comment by nono2032** [comment]
Est ce qu il te faut quand même des captures d écrans ?  Je pourrais en envoyer plus tout à l'heure si nécessaire

**Comment by doudz** [comment]
Je pense que la consommation est à la place de rotation, la version actuel remet la valeur à 0 au bout de 2 sec (car utilisé aussi par le cube xiaomi)
mais il faudrait si la valeur qui s'affiche est cohérente pour être une puissance

**Comment by nono2032** [comment]
En appuyant refresh j ai sur les 2 rotation une valeur qui s affiche,  je vais tenter tout a l'heure quand je serai sur place de brancher un appareil dont je connaît la consommation pour vérifier si il y a une cohérence et donnerai un feedback

**Comment by nono2032** [comment]
j'ai brancher une ampoule de 20w , j'appuie sur refresh et j ai ces donnée qui apparaissent 2 seconde 👍 
![image](https://user-images.githubusercontent.com/47389767/53513231-fa5e5d00-3ac4-11e9-8b11-fdaff947cb65.png)

**Comment by nono2032** [comment]
puis un chauffage electrique 1500w 
![image](https://user-images.githubusercontent.com/47389767/53513460-91c3b000-3ac5-11e9-8453-26539393b351.png)

**Comment by nono2032** [comment]
donc oui c'est cohérent,  la valeur de rotation est le puissance en watt.
l'équipement est détecter en tant que lumi.plug

**Comment by doudz** [comment]
Parfait, merci pour le retour.
Est ce que la valeur apparaît aussi quand on fait un ON ? Ou uniquement sur un refresh ?

**Comment by nono2032** [comment]
Alors effectivement c est seulement en appuyant sur refresh,  rotation = puissance en watt et rotation 3 doit être la consommation en kwh j imagine depuis la création de l équipements,  d ailleurs cela serait bien d avoir l option de remise à zéro de la conso total

**Comment by nono2032** [comment]
@doudz est-ce que je dois faire encore un test ? Quelle est la prochaine étape ?

**Comment by doudz** [comment]
C'est bon j'ai pris en compte la modif, je vais mettre à jour la lib python

**Comment by nono2032** [comment]
Super merci à toi,  la grande classe

**Comment by doudz** [comment]
Corrigé dans la beta 1.2.3-b3 (disponible demain)

**Comment by nono2032** [comment]
Excellent, je testerai et donnerai un feedback

**Comment by nono2032** [comment]
@doudz je ne vois pas encore le version 1.2.3-b3 disponible

**Comment by doudz** [comment]
Effectivement la manip n'a pas fonctionné, je m'en occupe ça sera bon demain

**Comment by nono2032** [comment]
alors bonne nouvelle , ça a l'air de fonctionner, mis à part que power 3 est indiqué en watt par contre je pense qu'il s'agit plutot de la conso total en kw/h
![image](https://user-images.githubusercontent.com/47389767/53730786-36087680-3e79-11e9-9dd4-1ba1c3d1f8eb.png)

**Comment by nono2032** [comment]
avec cette mise a jour je retrouve tous mes équipements par contre ils on perdu tous leur nom et du coup association au scenario etc.... je restaure un sauvegarde en espérant que tu arrives faire quelque chose ?  car c'est un peu laborieux de tout renommer et associer à chaque fois

![image](https://user-images.githubusercontent.com/47389767/53730938-9a2b3a80-3e79-11e9-80c9-657dbd9269d4.png)

**Comment by doudz** [comment]
Oh, on a pas supposé tout perdre. Je dirais qu'il faut remonter la sauvegarde, et refaire la manip en debug pour comprendre ce qu'il se passe

**Comment by doudz** [comment]
Pour l'unité, le plus simple est de la changer manuellement dans Jeedom

**Comment by nono2032** [comment]
Ok je retente tout à l'heure et tranmettrai les logs

**Comment by nono2032** [comment]
[zigate(1).txt](https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/files/2927722/zigate.1.txt)

voila le log en debug avant et après mise a jour, j'ai à nouveau perdu  tout mes noms d'équipements.

**Comment by doudz** [comment]
Merci pour le retour.
Malheureusement je ne trouve pas le problème...
est-ce que l'ID de l'objet Jeedom change ? je pense que oui
Dans tous les cas, je pense qu'on va continuer comme ça, car tu sembles être le seul affecté... peut-être que le problème reviendra par ailleurs et que nous comprendrons ce qu'il se passe

**Comment by nono2032** [comment]
Oui c est bizzare, j ai pas eu ce soucis lors des dernières update.  Je vais retenter et vérifier si les id change ou pas.  Je te redis.

**Comment by doudz** [comment]
je cloture quand même le ticket car le problème de base est résolu.
Pour l'unité, il faudra la changer dans Jeedom directement.
Actuellement elle est forcée mais je vais la débloquer dans la prochaine update

**Comment by nono2032** [comment]
cette fois c'est passé avec la dernière version 1.2.3-b4 / je sais pas si c'est lier mais je suis sur auto avec le port usb de la zigate,  avec la mise a jour precedent b3 le deamon ne redemmarrait pas sur auto je devait choisir le bon port et tout mes équipement n'avait plus de nom, avec la dernière update pas ce problème ce redemmare sans problème sur auto !

**Comment by nono2032** [comment]
Et merci pour avoir résolu le problème des puissances. La classe
