### ISSUE TITLE
Question process

### ISSUE THREAD

**Issue by Amigagame** [Jeedom-Zigate/jeedom-plugin-zigate#147]
Bonjour, ceci n'est pas un bug mais une question sur le fonctionnement

Quand nous remontons des bugs (ou ce que nous pensons être des bugs), le ticket passent plusieurs états.

Sur mes deux dernières remontées, j'ai vu les états changer jusqu'à passer en 'closed' ce matin sans qu'on nous demande de tester ou vérifier la correction. Je n'ai même pas vu de 1.2.3 disponibe (celle qui embarquerait les corrections)

Je trouve cela étrange car si la prochaine mise à jour du plugin ne corrige pas, nous devrons réouvrir ou une autre personne risque de faire un nouveau ticket (mais après tout pourquoi pas)

Ne serait il pas plus efficace de nous proposer de tester les corrections des problèmes que nous remontons AVANT de fermer les tickets ?

Très belle semaine à vous :)

**Comment by doudz** [comment]
L'organisation n'est pas tout à fait carré sur ce point, c'est vrai.
Je viens de mettre la version 1.2.3 en beta, j'aurai pu attendre de passer en stable avant de clôturer les tickets mais tout le monde n'utilise pas la beta donc je n'aurai pas eu forcément tous les retours.

**Comment by Amigagame** [comment]
Pas de soucis, je ferais comme cela vous arrange le mieux. Par contre je ne sais pas comment passer en béta si cela peut aider à vous confirmer les corrections ou les nouveaux bugs AVANT de passer en stable :)

**Comment by doudz** [comment]
Attention la beta ne sera disponible sur le market Jeedom que demain (il me semble que Jeedom ne met à jour le market qu'une fois la nuit)
Il me semble que pour installer la beta il suffit d'utiliser le market

**Comment by Amigagame** [comment]
Ok, merci :)

**Comment by Deepcore93** [comment]
Salut,

Pour profiter des version beta, il faut aller sur ta page profile du market et cocher l'option.

**Comment by doudz** [comment]
effectivement, merci @Deepcore93 
![image](https://user-images.githubusercontent.com/1262548/53329863-65edd200-38ed-11e9-86a2-5197f1664d34.png)

**Comment by doudz** [comment]
Je ferme car ça ne concerne pas un problème
