### ISSUE TITLE
Traduction anglais

### ISSUE THREAD

**Issue by doudz** [Jeedom-Zigate/jeedom-plugin-zigate#149]
Traduire le plugin en anglais

**Comment by Deepcore93** [comment]
J'ai commencé à travailler dessus.
Je pensais dans un 1er temps tout franciser : 
- Reset Zigate -> Redémarrage
- Erase PDM -> Remise à zéro
- etc ...
C'est ok pour vous ?

**Comment by doudz** [comment]
Oui si ça ne pose pas de problème technique (lié aux accents par exemple)

**Comment by Deepcore93** [comment]
Non ça ne pose pas de problème, ça tourne sur ma vm de dev déjà

**Comment by Deepcore93** [comment]
J'ai fini l'implémentation de la traduction, je te fais un PR en beta ? Si je te le fais en dev le PR en attente fout le bazar :)

**Comment by doudz** [comment]
Pousse en dev plutôt, je valide le PR en attente

**Comment by Deepcore93** [comment]
Ok, je fais ça dans la soirée

**Comment by Deepcore93** [comment]
C'est en PR. 
A tester, normalement j'ai tout traduit.

**Comment by Deepcore93** [comment]
Pour info : le moteur Jeedom ne traduit pas tout, il peut avoir des non traductions et des '{{' ou '}}" qui apparaissent.
Je laisse comme ça pour le moment, en espérant que cela soit corrigé sur la prochaine mise à jour Jeedom.

**Comment by doudz** [comment]
? Sérieusement ? en version 3.* Jeedom ne gère pas correctement les traductions ?
ça me parait très surprenant mais si c'est le cas ça démontre la mauvaise qualité du code Jeedom...

**Comment by Deepcore93** [comment]
Ouaip c'est pas beau :D

**Comment by Deepcore93** [comment]
Tu valide le PR ?
