### ISSUE TITLE
lumi.sensor_86sw2Un, commande onoff3 ?

### ISSUE THREAD

**Issue by Amigagame** [Jeedom-Zigate/jeedom-plugin-zigate#156]
J'ai reçu et lié un interrupteur double commande simple switch Aqara

L'association s'est correctement déroulée, les actions onoff et onoff2 fonctionnement parfaitement dans un scénario pour commander une ampoule Aqara

Quelques heures après l'association, j'ai vu une commande onoff3 s'ajouter

Savez vous à quoi elle sert, est ce un bug ?

**Informations:**
- Type de l'équipement : lumi.sensor_86sw2Un
- Version Jeedom : 3.2.16
- Version plugin : 1.2.3-b2
- Version lib : 0.28.2
- Version firmware : 3.0f

**Comment by Amigagame** [comment]
![capture](https://user-images.githubusercontent.com/14044648/53744261-ecca1e00-3e9c-11e9-9e72-cc0cb94d7b24.PNG)

**Comment by doudz** [comment]
Le 3 est utilisé lorsqu'on appuie sur les deux interrupteurs en même temps

**Comment by Amigagame** [comment]
Ok je ferme le ticket, merci !
