### ISSUE TITLE
Association avec les capteurs pluzzy

### ISSUE THREAD

**Issue by rockynox** [Jeedom-Zigate/jeedom-plugin-zigate#158]
**Description du bug**

Impossible d'associer des prises pluzzy via la Zigate.
J'ai vu plusieurs message sur le forum (datant de Mars 2018) ainsi qu'une issue ouverte sur le repo du zigate (https://github.com/fairecasoimeme/ZiGate/issues/30) mais pas vraiment de piste de résolution. Du coup je poste ce message comme une bouteille à la mer pour avoir des infos.

(et ayant récupérer un plein d'objets pluzzy, je suis partant pour aider à developper cette feature !)

**Pour Reproduire**
Etapes pour reproduire le problème:
1. Procédure nominal de pairing avec le mode inclusion + appuis long sur le bouton de la prise pour initier le pairing.

**Fonctionnement attendu**
Apparition de la prise dans Jeedom.

**Informations:**
- Type de l'équipement : Jeedom sur RasberryPi

**Comment by doudz** [comment]
Je ne sais pas si c'est toujours d'actualité mais les pluzzy requiert un firmware zigate spécifique
https://github.com/fairecasoimeme/ZiGate_HA1.2

**Comment by Breton18** [comment]
Bonjour,
Je suis aussi à la recherche d'une solution pour utiliser des objets pluzzy Ijenko avec jeedom.
Avez-vous trouver une solution ?
merci.

**Comment by pipiche38** [comment]
Je pense que vous devriez poser la question sur le forum zigate.fr <http://zigate.fr/> 

Aujourd’hui le firmware ZHA2.1 pour Zigate supporte parfaitement le Temp/Humi Pluzzy (fonctionnel sur Domotciz)
Pour ce qui est de la prise, il y a une adaptation à faire coté firmware

**Comment by Breton18** [comment]
Bonjour.
J'essaye d'utiliser une prise Ijenko avec wjeedom et le plugin zigate.
La fontion affiche on/off fonctionne

Par contre est-il possible de faire une action allumer  eteindre ?
Merci.
En pièce jointe une copie d'écran.

Merci.
Bien cordialement.
Pierrick ALLÉE
06 06 57 15 56
