### ISSUE TITLE
[DEV] Information réseau

### ISSUE THREAD

**Issue by Deepcore93** [jeedom-zigate/jeedom-plugin-zigate#162]
Un petit aperçu ...
![video_reseau](https://user-images.githubusercontent.com/42214914/53909847-d665c300-4052-11e9-8da2-3a18bf0950f5.gif)

PR : https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/pull/168

**Comment by jlagrut01** [comment]
bonjour,

j'ai le plugin 1.3.5 sous jeedom.
comment peut on afficher le reseau zigbee s'il vous plait ?
j'ai des problèmes de maillage et j'aimerais bien pourvoir améliorer mon installation.

merci pour votre aide,
jérôme

**Comment by didius62** [comment]
Bonjour

Pouvez vous svp nous dire comment acceder a cette fonctionnalité importante.

Merci

Didier
