### ISSUE TITLE
Support du Heartbeat (Jeedom 3.3)

### ISSUE THREAD

**Issue by llaumgui** [Jeedom-Zigate/jeedom-plugin-zigate#170]
**Description du bug**
Le daemon Zigate est relancé toute les heure par le Heartbeat de Jeedom 3.3. J'ai l'impression que le Heartbeat ne fonctionne pas avec Zigate.

**Pour Reproduire**
Etapes pour reproduire le problème:
1. Go to configuration plugin
2. Activer le Heartbeat.

```
[2019-03-12 13:25:11][ERROR][zigate](MainThread) : Traceback (most recent call last):
File "/usr/local/lib/python3.5/dist-packages/zigate/clusters.py", line 107, in update
'self': self})
File "<string>", line 1, in <module>
TypeError: type str doesn't define __round__ method
```

**Fonctionnement attendu**
Un daemon qui fonctionne n'estp as relancé.

**Informations:**
- Version Jeedom : 3.3
- Version Plugin : 1.2.3
- Version lib zigate : 0.28.4
- Version du firmware : 3.0f

**Comment by llaumgui** [comment]
@doudz > dans l'espace développeur tu as pas un doc sur comment l'intégrer ?

**Comment by doudz** [comment]
Le traceback fournit n'est pas en relation avec le heartbeat, c'est lié à un changement de type sur l'un des clusters, str avant et float maintenant. En théorie ça disparait lorsque l'équipement en question se met à jour.

**Comment by doudz** [comment]
sinon Ya un espace développeur ? :D

**Comment by llaumgui** [comment]
Tu dois y accéder toi comme tu es identifié comme le proprio du plugin.

**Comment by llaumgui** [comment]
Je pense qu'il dois y avoir un stockage de la dernière remontée. Et si pas de remonté en x seconde alors restart.

**Comment by llaumgui** [comment]
https://www.jeedom.com/site/fr/dev.html

**Comment by llaumgui** [comment]
J'ai posté un message sur le forum:
https://www.jeedom.com/forum/viewtopic.php?f=27&t=43908

**Comment by Deepcore93** [comment]
Moi j'attends avant de passer dessus j'ai constaté pas mal de bug sur ma vm de test.

@llaumgui : tu peux essayer de passer en anglais pour voir si les plug-in sont traduit.

**Comment by llaumgui** [comment]
pas sur ma prod :-)

**Comment by llaumgui** [comment]
Apparemment, lorsque la tempête mes Xiaomi se met à jour, la date de dernière remontée de l'équipement ne l'ai pas. Et de ce que je comprends le heartbeat fait un select des équipements par date de mise a jour. Du coup c'est de la que viendrai le problème.

**Comment by doudz** [comment]
Je suis pas sûr de piger, c'est quoi cette histoire de tempête ?

**Comment by doudz** [comment]
D'après la documentation
Heartbeat : toute les 5 mins, Jeedom regarde si au moins un équipement du plugin a communiqué dans les X dernières minutes (si vous voulez désactiver la fonctionnalité, il suffit de mettre 0)

Redemarrer démon : si le hertbeat tombe en erreur alors Jeedom va redémarrer le démon

**Comment by doudz** [comment]
Sachant que de base les Xiaomi remonte leur état toutes les 50min je dirais qu'il faut mettre le heartbeat sur 60 ou même 120min

**Comment by llaumgui** [comment]
Température :-). La correction d’Android est fatale :-).

Mais j'ai l'impression que des fois ma température est plus à jour que la date de dernière mise à jour de l'équipement.

**Comment by doudz** [comment]
Est-ce que ça serait pas la même chose (encore) https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/issues/46

**Comment by llaumgui** [comment]
Ok, 2h c'est bien 😀.

**Comment by llaumgui** [comment]
Je réouvre pour mettre une phrase dans la FAQ.
