### ISSUE TITLE
Question reconnaissance bouton switch Mi (version Mija)

### ISSUE THREAD

**Issue by jcharmetton** [jeedom-zigate/jeedom-plugin-zigate#171]
Bonjour,
J'ai ajouté un bouton switch Mi sur mon plugin zigate.
Par contre, je suis surpris sur les commandes proposées. Je ne comprends pas comment capter le click, le double click et l'appui long...
![image](https://user-images.githubusercontent.com/12799273/54430962-611a8200-4725-11e9-8a92-1cd2eea18370.png)
![image](https://user-images.githubusercontent.com/12799273/54431009-8909e580-4725-11e9-84de-70f40807f4eb.png)
J'ai essayé de travailler avec "multiclick" et "onoff" mais sans succès.
Est-ce que mon bouton est correctement reconnu?
Cordialement
Julien.

**Comment by smulle48** [comment]
Try this :-)

https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/issues/165#issuecomment-472584321
