### ISSUE TITLE
Question sur mon log Zigate

### ISSUE THREAD

**Issue by Amigagame** [Jeedom-Zigate/jeedom-plugin-zigate#172]
Dans mes logs, en mode debug sur Zigate, je vois qu'a intervals réguliers, le plugin va récreer l'ensemble des commandes d'un périphérique (sans que je le demande car je suis à distance et qu'il n'y a personne chez moi). C'est la remontée de valeurs qui fait ça ?

Normal ?
[zigate (2).txt](https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/files/2996946/zigate.2.txt)

**Comment by Amigagame** [comment]
ok, à priori c'est bien l'update des commandes, c'est la ligne command create qui me trouble mais à priori ca semble normal :)

**Comment by doudz** [comment]
C'est normal, le log indique create c'est vrai en réalité c'est création ou mise à jour
