### ISSUE TITLE
Bouton on/off n'apparaisse pas pour Xiaomi aqara wireless switch

### ISSUE THREAD

**Issue by thetrueavatar** [Jeedom-Zigate/jeedom-plugin-zigate#174]
**Description du bug**
Comme indiqué dans le titre, après association d'interrupteur Xiaomi aqara wireless switch(sur pile donc) je constate qu'il n'y a aucune commande d'allumage créée. J'ai le cas pour les 3 interrupteurs. J'utilise la version beta du zigate
**Pour Reproduire**
Etapes pour reproduire le problème:
1. Appui sur inclusion
2. Appui prolongé sur interrupteur jusqu'à ce que les 2 led clignotes bleu
3. Détection du device par le zigate avec redirection vers la page de la configuration du device
4. Action dans commande ne contient pas on/off

**Fonctionnement attendu**
Après appairage par mode inclusion, le device créé devrait contenir des commandes on ou off.
**Screenshots**

[Lien vers image](https://drive.google.com/file/d/1uCbb07rOIXiTB80mIplqTR-mEd554IM0/view?usp=sharing)
**Informations:**
- Type de l'équipement : lumi.sensor_86sw1lu
- Version Jeedom : 3.3.19 
- Version Plugin : 1.2.3
- Version lib zigate : 0.28.4
- Version du firmware : 3.0e
- log d'erreur dans terminal après demande de refresh:
RESPONSE 0x8702 - APS Data Confirm Fail : status:240, source_endpoint:1, dst_endpoint:1, dst_address_mode:2, dst_address:**2a44**, sequence:219, lqi:0
- log détaillé après passage en debug et demande de refresh du device:
[zigate.log](https://drive.google.com/file/d/1rscqEUWzP-cvdDtBvhKmZgbVAmPRby8r/view?usp=sharing)
- zigate.json: extrait concernant le device
`{
      "addr": "2a44",
      "discovery": "auto-discovered",
      "endpoints": [
        {
          "clusters": [
            {
              "attributes": [
                {
                  "attribute": 1,
                  "data": 4,
                  "name": "application_version",
                  "value": 4
                },
                {
                  "attribute": 5,
                  "data": "lumi.sensor_86sw1\u0000lu",
                  "name": "type",
                  "type": "str",
                  "value": "lumi.sensor_86sw1lu"
                },
                {
                  "attribute": 65281,
                  "data": "0121c70b0328180421a8130521d700062401000000000a21000020",
                  "name": "battery_voltage",
                  "type": "float",
                  "unit": "V",
                  "value": 3.015
                }
              ],
              "cluster": 0
            },
            {
              "attributes": [
                {
                  "attribute": 0,
                  "data": false,
                  "name": "onoff",
                  "type": "bool",
                  "value": false
                }
              ],
              "cluster": 6
            }
          ],
          "device": 24321,
          "endpoint": 1,
          "in_clusters": [
            0,
            3,
            25,
            65535,
            18
          ],
          "out_clusters": [
            0,
            4,
            3,
            5,
            25,
            65535,
            18
          ],
          "profile": 260
        },
        {
          "clusters": [],
          "device": 24322,
          "endpoint": 2,
          "in_clusters": [
            3,
            18
          ],
          "out_clusters": [
            4,
            3,
            5,
            18
          ],
          "profile": 260
        },
        {
          "clusters": [],
          "device": 24323,
          "endpoint": 3,
          "in_clusters": [
            3,
            12
          ],
          "out_clusters": [
            4,
            3,
            5,
            12
          ],
          "profile": 260
        }
      ],
      "generictype": "",
      "info": {
        "addr": "2a44",
        "id": 1,
        "ieee": "00158d000183c217",
        "last_seen": "2019-03-29 18:36:18",
        "lqi": 177,
        "mac_capability": "10000000",
        "power_type": 0
      }
    }`

**Comment by thetrueavatar** [comment]
Pour info, j'ai pullé le code et vais sans doute debugé avec ma zigate pour voir ce qui cloche lors du parsing de la response. Si jamais je trouve je ferai un fork+pull request;

**Comment by doudz** [comment]
Il n'y a pas la commande "onoff" permettant de connaitre l'état du bouton c'est bien ça ?

**Comment by thetrueavatar** [comment]
En effet. Néanmoins ta question ma fait réfléchir et en fait c'est sans doute normal. Je voyais ça comme des interrupteurs et m'attendait à avoir un état on/off mais en pratique c'est juste un bouton cliquable façon aqara wireless button. Je vois qu'il y a un status et une valeur potentiele à "click" comme pour les petits bouton. J'imagine que dans mon scénario je dois plutôt tester le fait que status="click" et ça devrait passer. Je valide et reviens vers toi.

**Comment by elarochejoubert** [comment]
Je confirme le dernier message. C'est normal.
