### ISSUE TITLE
Pas d'intégration du switch On/Off 3A Smart ZigBee 3.0HGZB-01A

### ISSUE THREAD

**Issue by phyllox** [jeedom-zigate/jeedom-plugin-zigate#175]
Bonjour
J'ai essayé d'intégrer aujourd'hui un switch On/off HGZB-01A, marque 3A, nom complet Smart ZigBee 3.0 Light Controller (acheté sur Amazon)

Je voulais remplacer le même type de switch que je possède qui sont aujourd'huii en Wifi, et me passer d'IFTTT.

Zigate l'intègre comme matériel inconnu, mais ne trouve que 3 éléments 
- Manufacturer : Info : 3A SMart Home DE
- Type - Info - LXN56-LC27LX1.1
- Refresh - Action

Donc pas de On, pas de Off, pas de Toggle, pas de retour d'état.

Bien entendu, j'ai lancé plusieurs fois "Découvrir l'équipement" et "Rafraîchir l'équipement", sans résultat aucun.

Dans un pont Hue, l'équipement s'intègre comme une lumière, avec un On et un Off, mais pas d'état ni d etoggle. En fait j'espérais beaucoup l'intégration dans Zigate pour récupérer le Toggle et le retour d'état et commander l'ensemble avec un bouton bascule + Alexa (via Ha-Bridge puisque le plugin Alexa ne fonctionne pas chez moi).

Une chance d'avoir cet équipement fonctionnel ?
Merci

**Fonctionnement attendu**
Comme pour les prises INNR intégrées aujourd'jui, j'espérais le toggle et le retour d'état (et le On / Off bien entendu pour piloter Alexa).

**Informations:**
- Type de l'équipement : HGZB-01A
- Version Jeedom : 3.3.19
- Version Plugin : 1.2.3
- Version lib zigate : 0.28.4
- Version du firmware : 3.0f

**Comment by doudz** [comment]
Il faudrait le contenu du fichier zigate.json pour voir comment est reconnu le switch.

**Comment by phyllox** [comment]
Bonjour, merci de la réponse.
Vu que je sur nul avec Jeedom, où est-ce que je trouve le zigate.json ?
(NB sur sur sur un NUC avec Debian Stretch).
Merci

**Comment by phyllox** [comment]
Hello
Bon, je pense avoir trouvé le fichier, j'espère que c'est le bon.
Comme je suis aussi incompétent avec Debian qu'avec Jeedom, je ne sais pas copier l'intégralité d'un fichier dans le presse papier pour le récupérer dans Windows, alors j'ai réassemblé les bouts d'un copier tout dans Putty. j'espère que je n'ai rien oublié. J'ai copié seulement la fin du ficjier où l'équipement apparaît.
A noter que depuis mon premier post, il a rajouté au hasard d'une découverte un état OnOff, mais toujours pas de commande.

Merci d'avance

                _"ieee": "00158d0002e69031",
                "last_seen": "2019-04-04 11:38:58",
                "lqi": 78,
                "mac_capability": "10000000",
                "manufacturer_code": "1037",
                "power_type": 0,
                "server_mask": 0
            }
        },
        {
            "addr": "a71b",
            "discovery": "auto-discovered",
            "endpoints": [
                {
                    "clusters": [
                        {
                            "attributes": [
                                {
                                    "attribute": 4,

                                    "data": "3A SMart Home DE",
                                    "name": "manufacturer",
                                    "value": "3A SMart Home DE"
                                },
                                {
                                    "attribute": 5,
                                    "data": "LXN56-LC27LX1.1",
                                    "name": "type",
                                    "type": "str",
                                    "value": "LXN56-LC27LX1.1"

                                    "name": "manufacturer",
                                    "value": "3A SMart Home DE"
                                },
                            ],
                            "cluster": 0
                        },
                        {
                            "attributes": [
                                {
                                    "attribute": 0,
                                    "data": true,
                                    "name": "onoff",
                                    "type": "bool",
                                    "value": true
                                }
                            ],
                            "cluster": 6
                        }
                    ],
                    "device": 0,
                    "endpoint": 11,
                    "in_clusters": [
                        0,
                        4,
                        3,
                        6,
                        5,
                        4096,
                        8
                    ],
                    "out_clusters": [
                        25
                    ],
                    "profile": 49246
                }
            ],
            "generictype": "",
            "info": {
                "addr": "a71b",
                "ieee": "00158d0002b78d93",
                "last_seen": "2019-04-04 11:58:47",
                "lqi": 147,
                "mac_capability": "10001110"
            }
        },
        {
            "addr": "0245",
            "discovery": "",
            "endpoints": [
                {
                    "clusters": [
                        {
                            "attributes": [
                                {
                                    "attribute": 65520,
                                    "data": "aa100541870a011001"
                                }
                            ],
                            "cluster": 0
                        },
                        {
                            "attributes": [
                                {
                                    "attribute": 85,
                                    "data": "",
                                    "expire": 2,
                                    "name": "multiclick",
                                    "type": "str",
                                    "value": ""
                                }
                            ],
                            "cluster": 18
                        }
                    ],
                    "device": 0,
                    "endpoint": 1,
                    "in_clusters": [],
                    "out_clusters": [],
                    "profile": 0
                }
            ],
            "generictype": "",
            "info": {
                "addr": "0245",
                "last_seen": "2019-03-30 14:52:22",
                "lqi": 156
            }
        }
    ],
    "groups": {},
    "scenes": {}_

**Comment by doudz** [comment]
Le problème vient du fait que la valeur "device" = 0 , ce n'est pas normal, en théorie en relançant une découverte la valeur devrait arriver

**Comment by phyllox** [comment]
Hello, merci pour le retour.
Malheureusement des découvertes, j'en ai lancé au moins 10...
Je viens de supprimer l'équipement et de le recréer, mais même combat, même après à nouveau plusieurs découvertes...
Dans le fichier le device est toujours à 0.

Quelque chose que je peux essayer ?
Merci

**Comment by phyllox** [comment]
Bonjour
Des nouvelles ?
J'ai encore 1 ou 2 jours pour le retourner s'il ne peut pas être utilisé, parce que ainsi, il ne m'est d'aucune utilité. En plus il est assez encombrant et bien plus cher que ses collègues WiFi.

Merci d'avance et bonne journée.

**Comment by rroblik** [comment]
Bonjour

Peut-on espérer une intégration ? Je demande avant d’acheter ce module très bon marché...

Merci!

**Comment by doudz** [comment]
La dernière version du plugin devrait le prendre en charge (attention Jeedom V4)

**Comment by rroblik** [comment]
Ok bonne nouvelle. La version actuelle donc? Ou la prochaine ?

**Comment by doudz** [comment]
La version actuelle

**Comment by rroblik** [comment]
Super j’achète et ferais un feedback !
