### ISSUE TITLE
Lancement des dépendances impossible et version de clef pas visible

### ISSUE THREAD

**Issue by advence87** [Jeedom-Zigate/jeedom-plugin-zigate#177]
Bonjour à tous,
Ma clef fraichement reçu avant-hier fait des siennes à moins que le probleme vienne du plugin. 
Impossible d'installer les dépendances pas de version lib et pas de version de version firmware au-dessus de la clef et le probléme persiste avec la version beta du plugin zigate. 
Si une âme charitable à un debut de solution cela m 'interresse et bien entendu j'ai ouvert un ticket sur jeedom avec une jolie réponse de m'adresser au developpeur du plugin.
Configuration:
Jeedom smart 3.3.20
plugin Zigate 1.2.3
Clef Zigate USB TTL toute neuve avec dernier firmware
pip2 -V
pip 18.0 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7)
pip3 -V
sh: 1: pip3: not found
pip -V
pip 18.0 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7)
Je suppose que le probleme vient du pip3, mais comment résoudre le probleme sur la smart?

[zigate_update.txt](https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/files/3075752/zigate_update.txt)
[zigate2.log](https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/files/3075753/zigate2.log)

**Comment by llaumgui** [comment]
Pas un bug. Merci d'utiliser le forum de support.

**Comment by llaumgui** [comment]
Et en plus tu as posté le même message dessus.

**Comment by doudz** [comment]
De plus je ne comprends pas les log fournis ne collent pas, le zigate_update semble parler d'une vielle version du plugin (lib 0.22) et l'autre log indique que le plugin fonctionne

**Comment by advence87** [comment]
Désolé pour le double post je ne trouvais plus le premier !
J'ai eu Sebastien par mail qui m'annonce que le système Apt de debiane ne fonctionne plus sur la Smart. version se debiane en fin de vie.
Pour les logs ci-joint la ré-installation du plugin zigate de ce matin 
[zigate.TXT](https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/files/3077111/zigate.TXT)
[zigate_update.TXT](https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/files/3077112/zigate_update.TXT)
