### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by smulle48** [Jeedom-Zigate/jeedom-plugin-zigate#178]
**Description du bug**
Une description claire et précise du problème.

**Pour Reproduire**
Etapes pour reproduire le problème:

**Fonctionnement attendu**
Une description claire et précise du fonctionnement attendu.

**Screenshots**
Des captures d'écrans du problème (si applicable).

**Informations:**
- Type de l'équipement : [lumi.sensor, ....]
- Version Jeedom :
- Version Plugin :
- Version lib zigate :
- Version du firmware :

**Comment by doudz** [comment]
The project is not dead. Personally I have no time to work on it these days.
But it's an open source project so anybody is free to contribute.
