### ISSUE TITLE
Interrupteur simple Aqara Xiaomi WXKG03LM

### ISSUE THREAD

**Issue by mattwarend** [jeedom-zigate/jeedom-plugin-zigate#180]
Bonjour,

Je n'arrive pas à obtenir une bonne intégration de l'interrupteur Aqara Xiaomi WXKG03LM.
Il est reconnu comme lumi.remote.b186acn01 et du coup les commandes ne sont pas bonne.
Pas de On/Off par exemple.
https://ibb.co/1TpPVW2
https://ibb.co/Gt0xWzs

**Comment by doudz** [comment]
Est ce toujours d'actualité ?
