### ISSUE TITLE
Problème avec la prise Osram smart+ Exterieur

### ISSUE THREAD

**Issue by pacopad** [Jeedom-Zigate/jeedom-plugin-zigate#183]
**Description du bug**
La prise est détectée et identifiée comme le modèle d’intérieur. Les commandes sont créés mais elles ne fonctionne pas.

**Pour Reproduire**
Associer la prise à la Zigate

**Informations:**
- Type de l'équipement : Prise Osram Smart+ étanche.
- Version Jeedom :3.3.24
- Version Plugin : celui dispo sur le market
- Version lib zigate : 0.28
- Version du firmware :3.0f

**Comment by doudz** [comment]
Bonjour,

Dans quelques jours une petite mise à jour sortira, elle est actuellement
en beta.
Cela résoudra peut-être le problème.

Cordialement

Sébastien

**Comment by pacopad** [comment]
Merci pour le retour, 

si y a moyen de tester la béta , je suis preneur :) 

Pascal

**Comment by doudz** [comment]
Il suffit d'installer d'autoriser l'installation des plugins en beta dans
les paramètres de Jeedom

**Comment by pacopad** [comment]
Parfait je testerai ce soir 

Merci

**Comment by pacopad** [comment]
L'install des dépendances de la beta se passe bien 
Requirement already satisfied: zigate==0.29.5 in /usr/local/lib/python3.5/site-packages (0.29.5)
Requirement already satisfied: bottle in /usr/local/lib/python3.5/site-packages (from zigate==0.29.5) (0.12.16)
Requirement already satisfied: pydispatcher in /usr/local/lib/python3.5/site-packages (from zigate==0.29.5) (2.0.5)
Requirement already satisfied: pyserial in /usr/local/lib/python3.5/site-packages (from zigate==0.29.5) (3.4)
Requirement already satisfied: RPi.GPIO in /usr/local/lib/python3.5/site-packages (from zigate==0.29.5) (0.6.5)
Installation des dépendances terminé !
mais le plugin me redemande de les installer :(

un conseil ?

**Comment by doudz** [comment]
Il me faudrait le détail des log (zigate et zigate_update)

**Comment by pacopad** [comment]
C'est le détail de zigate_update lorsque je lance l'install des dépendances, j'ai juste coupé la partie apt-get update et la partie ou il ne télécharge rien car les packages demandés sont à jour.

rien de particulier dans le log zigate. A quelle condition determine t il que les dépendances sont installées ? 

Merci

**Comment by doudz** [comment]
Le plugin teste la version de la lib installée, si elle correspond à celle demandée alors c'est ok
Dans notre cas 0.29.5.
Est-ce que je pourrai avoir une capture d'écran de la page de config du plugin ?

**Comment by pacopad** [comment]
Je te fais ca ce soir, j'ai plusieurs version de python d'installé (2.7 3.4 et 3.5.7) le problème pourrait il venir de la ?

**Comment by doudz** [comment]
Ah c'est possible
Pour l'installation le système utilise pip3 et pour le test /usr/bin/python3
si dans les 2 cas ce n'est pas la même version de python3 ça ne fonctionnera pas

**Comment by pacopad** [comment]
C'est bon ca fonctionne , la beta et la prise

J'avais bien un pb de melange de version de python. Il a fallu que je rajoute le module requests et que je commente le --gpio 0 dans la ligne de lancement et dans la lecture des arguments

Sinon tout roule

Merci

**Comment by doudz** [comment]
Pourquoi commenté la ligne "--gpio 0" ?

**Comment by pacopad** [comment]
Parceque ca  me provoquait un message d'erreur au lancement du démon me disant que c'était une option inconnue.

**Comment by doudz** [comment]
Effectivement, c'est corrigé, merci

**Comment by pacopad** [comment]
avec plaisir :)
