### ISSUE TITLE
Prise Connectée Smart Plug Extérieur  et équipement à pile

### ISSUE THREAD

**Issue by paulnux** [Jeedom-Zigate/jeedom-plugin-zigate#188]
**Description du bug**
Apres inclusion d'une prise Osram  SMART+ - Prise Connectée Smart Plug Extérieur
compatible zigate : https://zigate.fr/le-materiel-compatible-zigate/compatible/osramsmart-priseconnectesmartplugextrieur/

tout les équipements sur pile ne fonctionne plus (Les équipements sur pile sont de marques Xiaomi) au bout de 30 minutes à 1 heure.

Les équipements sur secteur fonctionne

La page santé dit que tout va bien

Si on redémarre le démon cela refonctionne entre 30 minutes et 1 heure après cela ne refonctionne plus

Si on débranche physiquement la prise Osram cela fonctionne

Si je supprime l'équipement Osram et quelle est toujours branché ,la prise se reinclue toute seul après 30 minutes à 1 heure et refait tomber les équipements sur pile

Meme si on désactive l’équipement de la prise Osram les équipements sur piles cesse de fonctionner au bout d'un moment 

**Pour Reproduire**
Etapes pour reproduire le problème:
1. Inclusion de la prise
2. Attente de 30 minutes à 1 heure
3. Les équipements sur piles ne fonctionne plus
4. Les équipements sur secteur fonctionne

**Fonctionnement attendu**
Que les équipements sur pile fonctionne

**Informations:**
- Type de l'équipement : Plug 01
- Version Jeedom : 3.3.26
- Version Plugin : 1.2.3
- Version lib zigate : 0.28.4
- Version du firmware : 3.0f

Doudz, pour info tu a toujours accès à ma box si tu veux
La prise est détectée et identifiée comme le modèle d’intérieur mais cela n'est pas grave, elle fonctionne
Problème de routage ?

**Comment by doudz** [comment]
> tout les équipements sur pile ne fonctionne plus

c'est à dire ?

**Comment by paulnux** [comment]
les ouvertures de porte ne remonte plus l'info si elle sont fermé ou ouverte
les détecteurs de mouvement  ne remonte plus si il a un mouvement
Les sondes de températures ne remonte plus la température

Je viens de vider la LOG et de redémarrer le démon et je test avec un capteur de mouvement pour voir le moment précis ou sa va plus

**Comment by paulnux** [comment]
Vider LOG  16:22 :45
Redémarrage démon  16 :23
Test équipement sur pile ADDR 78bb IEEE 00158d0002e2dfd8 à 16h25 = OK
Test équipement sur pile ADDR 78bb IEEE 00158d0002e2dfd8 à 16h33 = OK
Test équipement sur pile ADDR 78bb IEEE 00158d0002e2dfd8 à 16h42 =  KO
Test équipement secteur ADDR eea3 IEEE 90fd9ffffe29a942 = OK

**Comment by paulnux** [comment]
LOG DEBUG ZIGATE
[DEBUG-ZIGATE.txt](https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/files/3335328/DEBUG-ZIGATE.txt)

**Comment by paulnux** [comment]
La prise Osram est désactivé dans le plugin mais elle apparaît dans la LOG normal ?
ADDR 8a71
IEEE 7cb03eaa00afdb86

**Comment by doudz** [comment]
`[2019-06-27 16:35:11][DEBUG][zigate](ZiGate-Listen) : Raw packet received, b'\x01\x81\x02\x12\x02\x10\x02\x1f\x9c{\xae\xba\x02\x11\x02\x14\x02\x12\x02\x10\x02\x10\x02\x10)\x02\x10\x02\x12\x02\x14\xd6\x81\x03\x01\x81\x02\x12\x02\x10\x02\x1f\xad|\xae\xba\x02\x11\x02\x14'`

On voit que la dernière trame reçu est incomplète, elle devrait se terminer par \x03 
Normalement c'est géré mais peut-être pas dans cette version de la lib
je vais vérifier

**Comment by paulnux** [comment]
Le test de l'equipement secteur est une ampoule ADDR eea3
Quand je test je fait un on et off sur le dashboard ce qui a pour effet d'allumer et d’éteindre l'ampoule.
Sa fonctionne mais il n'y a pas de remonté d’état sur le dashboard après le souci, je ne sais pas si c'est lié

**Comment by doudz** [comment]
Je n'ai pas encore trouvé la raison, mais ça confirme ce que je pense à savoir, les données reçues de la zigate ne sont plus lues mais on peut toujours envoyer des commandes
Reste à savoir si c'est un bug du plugin ou un bug de la zigate

**Comment by paulnux** [comment]
Merci pour ton énorme travail
Je reste à disponibilité pour faire avancer les choses

**Comment by doudz** [comment]
Il semblerait qu'un problème similaire se pose aussi pour quelqu'un d'autre sur Home Assistant
https://community.home-assistant.io/t/another-component-for-zigate/58417/378
ça exclue le plugin Jeedom donc reste la lib zigate ou la zigate elle même.
L'utilisateur pense à un problème de température trop élevé, est-ce que ça pourrait être le cas aussi pour toi ?

**Comment by doudz** [comment]
J'ai trouvé un possible blocage, difficile à reproduire, j'ai apporté une correction dans la version Béta (lib 0.30.1) , à tester

**Comment by paulnux** [comment]
Je fais un test en plaçant un gros ventilateur sur pied en direction de la clé Zigate.
Pour l'instant 1h30 de test et tout fonctionne nickel en stable (Je n'ai pas encore installé la beta)
A suivre

**Comment by paulnux** [comment]
4H15 de test avec le ventilateur, toujours OK
Donc ce n’était pas un problème avec la prise Osram mais bien à première vue de température

Doudz veux tu que je refasse un test demain sans ventilateur pour confirmer que c'est la température ?
Et/ou que je fasse un test avec la beta ?

**Comment by biau** [comment]
Hello désolé de m'incruster, de mon coté ça a tendance a se confirmer que la zigate surchauffe également alors que au toucher pas du tout.
J'ai un moment pensé que la nouvelle méthode de poll automatique d'état sur home assistant était la cause mais après vérification le problème est apparu la première fois avant que je mette a jour.
Paulnux quelle est la t° dans la pièce ou tu utilises la zigate ?
Chez moi la beta n'a rien changé, au contraire l'augmentation d'activité de la zigate avec le poll automatique a accélerer l'apparition du problème.

**Comment by paulnux** [comment]
Hier je n'ai pas regardé, mais cette après midi il faisait 33.5°, j'ai mis le ventilateur en route, attendu 15 minutes, redémarré le démon à 14H50 et sa tourne toujours impeccable  à 23H15

**Comment by biau** [comment]
Ok, bon bin je me suis permis de référencer ce report sur le forum zigate: https://zigate.fr/forum/topic/surchauffe-de-la-zigate/#postid-378

**Comment by doudz** [comment]
Est ce toujours d'actualité ?

**Comment by paulnux** [comment]
Bonjour,
Avec le nouveau convertisseur USB, plus de soucis , c'était bien un problème de convertisseur qui chauffait

**Comment by doudz** [comment]
Super nouvelle, je clôture le ticket, merci pour le retour
