### ISSUE TITLE
Perte communication Jeedom<->Zigate wifi apres coupure secteur Zigate alors que Jeedom toujours alimenté

### ISSUE THREAD

**Issue by MbaGlub** [Jeedom-Zigate/jeedom-plugin-zigate#193]
**Description du bug**
Jeedom installée sur Raspberry alimentée par un UPS donc toujours sous tension.
Clé USB Zigate Wifi alimentée via un adaptateur USB non sécurité
Lors d'une coupure de courant, la clé Zigate n'est plus alimentée => Perte de communication avec Jeedom : Jusqu'ici tout est normal.
Lorsque le courant revient, la clé USB Zigate se rallume mais ne communique plus avec Jeedom ne se rétablie pas.
Vérification faite dans "santé" aucun module ne communique après la coupure de courant.
Seule solution pour rétablir la communication : Redémarrer le deamon Zigate

**Pour Reproduire**
Débrancher Zigate Wifi
Rebrancher Zigate Wifi
=> Perte de communication définitive

**Fonctionnement attendu**
Retrouver la communication avec les modules Zigbee automatiquement

**Screenshots**
NA

**Informations:**
- Type de l'équipement : ZiGate-WiFi v2.00 with esp-link v3.2.50-gfe4f565-dirty
- Version Jeedom : 3.3.27
- Version Plugin : 1.2.3
- Version lib zigate : 0.28.4
- Version du firmware :3.0f

**Comment by doudz** [comment]
merci de mettre à jour le plugin en dernière version

**Comment by MbaGlub** [comment]
Bonjour,

Tout d'abord, merci de vous préoccuper de mon problème.
Désolé pour le délai, je ne voulais pas mettre à jour mon système avant de partir en vacances.
Je viens de mettre à jour l'ensemble des composants Jeedom dont le plugin Zigate.
Je reproduis le problème et voici le mode opératoire:
23h20 Redémarrage du Demon Zigate via IHM du plugin Jeedom
23h22 Click sur Xiaomi bouton poussoir (Bp Entree = lumi.sensor_switch, IEEE=00158d0001e8019d, ADDR=df73)
	==> La commande est bien reçue
23h23 Coupure alimentation de la clé USB Zigate/Wifi uniquement. Jeedom Raspbery reste actif sur onduleur.
23h26 Retour alimentation de la clé USB Zigate
23h28 Click sur Xiaomi bouton poussoir
	==> Aucune action : Aucun log
23h31 Click sur Xiaomi bouton poussoir
	==> Aucune action : Aucun log
23h32 Redémarrage du Demon
23h33 Click sur Xiaomi bouton poussoir
	==> Commande reçue OK

Voici 2 logs:
zigate_Test1 pour la séquence de 23h20 à 23h31 (Avant second redémarrage)
zigate_Test2 après redémarrage de 23h32

[zigate_Test2.txt](https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/files/3469516/zigate_Test2.txt)
[zigate_Test1.txt](https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/files/3469517/zigate_Test1.txt)

**Comment by doudz** [comment]
Merci pour les infos, je vais faire des tests

**Comment by doudz** [comment]
Problème corrigé dans la prochaine version 1.3.4, disponible demain sur le market
En cas de perte de connexion, elle est automatiquement rétabli.
Dans certains cas, la perte de connexion n'est pas détectable rapidement, aussi le plugin fait une vérification toutes les 5 minutes et se reconnecte si la zigate ne répond plus
