### ISSUE TITLE
dépendances bloquées à 70%

### ISSUE THREAD

**Issue by Woualy** [Jeedom-Zigate/jeedom-plugin-zigate#196]
J'ai fait la mise à jour de ma clé Zigate (bleue) en 3.0.f. Pas de soucis, redémarrage de la Jeedom. Ce matin, mise à jour du plugin Ziagte. 

Je fais la mise à jour, relance des dépendances : Ca monte jusqu'a 70% - 1 min et après plus rien, pas de bouton de démarrage de Démon, plus de clé (pourtant bien en USB), plus de périphérique, Bref PLUS RIEN !

J'ai même desinstallé, reinstallé le plug in ZIgate , pas mieux.

Mise à jour du Firmware en 3.1a avec erase de l'eeprom, toujours le même problème

Plugin 1.3.0, clé en 3.1a , pas d'installation de dépendances.

`Installation des dépendances
Hit:1 http://security.debian.org stretch/updates InRelease
Ign:2 http://ftp.debian.org/debian stretch InRelease
Hit:3 http://www.deb-multimedia.org stretch InRelease
Hit:4 http://repo.jeedom.com/odroid stable InRelease
Hit:5 http://ftp.debian.org/debian stretch-updates InRelease
Hit:6 http://ftp.debian.org/debian stretch-backports InRelease
Hit:7 http://ftp.debian.org/debian stretch-proposed-updates InRelease
Hit:8 http://ftp.debian.org/debian stretch Release
Hit:9 https://oph.mdrjr.net/meveric all InRelease
Hit:10 https://oph.mdrjr.net/meveric stretch InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
python3 is already the newest version (3.5.3-1).
The following packages were automatically installed and are no longer required:
libmemcached11 libmemcachedutil2 libmysqlclient18 libonig2 libopts25
libpng12-0 libqdbm14 libvpx1 linux-image-3.14.29+
linux-image-arm64-odroid-c2 u-boot-tools
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 162 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
python3-pip is already the newest version (9.0.1-2+deb9u1).
The following packages were automatically installed and are no longer required:
libmemcached11 libmemcachedutil2 libmysqlclient18 libonig2 libopts25
libpng12-0 libqdbm14 libvpx1 linux-image-3.14.29+
linux-image-arm64-odroid-c2 u-boot-tools
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 162 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
python3-requests is already the newest version (2.12.4-1).
The following packages were automatically installed and are no longer required:
libmemcached11 libmemcachedutil2 libmysqlclient18 libonig2 libopts25
libpng12-0 libqdbm14 libvpx1 linux-image-3.14.29+
linux-image-arm64-odroid-c2 u-boot-tools
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 162 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
python3-setuptools is already the newest version (33.1.1-1).
The following packages were automatically installed and are no longer required:
libmemcached11 libmemcachedutil2 libmysqlclient18 libonig2 libopts25
libpng12-0 libqdbm14 libvpx1 linux-image-3.14.29+
linux-image-arm64-odroid-c2 u-boot-tools
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 162 not upgraded.
Collecting zigate==0.31.0
Using cached https://files.pythonhosted.org/packages/08/59/11f5fa73c373cdc37cc8cad6bf08aa5041fa4dc345f7cc825f2c44a83a14/zigate-0.31.0-py3-none-any.whl
Requirement already satisfied: pyserial in /usr/local/lib/python3.5/dist-packages (from zigate==0.31.0)
Collecting RPi.GPIO (from zigate==0.31.0)
Using cached https://files.pythonhosted.org/packages/af/2f/407b6e4cc8a0bdf434825a160bba1807991886b63cce16a5f1a6e1f24cdf/RPi.GPIO-0.6.5.tar.gz
Requirement already satisfied: bottle in /usr/local/lib/python3.5/dist-packages (from zigate==0.31.0)
Requirement already satisfied: pydispatcher in /usr/local/lib/python3.5/dist-packages (from zigate==0.31.0)
Building wheels for collected packages: RPi.GPIO
Running setup.py bdist_wheel for RPi.GPIO: started
Running setup.py bdist_wheel for RPi.GPIO: finished with status 'error'
Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-lz0hiv0m/RPi.GPIO/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('
', '
');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp9ulep_jzpip-wheel- --python-tag cp35:
usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
or: -c --help [cmd1 cmd2 ...]
or: -c --help-commands
or: -c cmd --help
error: invalid command 'bdist_wheel'
----------------------------------------
Failed building wheel for RPi.GPIO
Running setup.py clean for RPi.GPIO
Failed to build RPi.GPIO
Installing collected packages: RPi.GPIO, zigate
Running setup.py install for RPi.GPIO: started
Running setup.py install for RPi.GPIO: finished with status 'error'
Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-lz0hiv0m/RPi.GPIO/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('
', '
');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ldlcs6lw-record/install-record.txt --single-version-externally-managed --compile:
running install
running build
running build_py
creating build
creating build/lib.linux-aarch64-3.5
creating build/lib.linux-aarch64-3.5/RPi
copying RPi/__init__.py -> build/lib.linux-aarch64-3.5/RPi
creating build/lib.linux-aarch64-3.5/RPi/GPIO
copying RPi/GPIO/__init__.py -> build/lib.linux-aarch64-3.5/RPi/GPIO
running build_ext
building 'RPi._GPIO' extension
creating build/temp.linux-aarch64-3.5
creating build/temp.linux-aarch64-3.5/source
aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.5-kWxB2e/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c source/py_gpio.c -o build/temp.linux-aarch64-3.5/source/py_gpio.o
source/py_gpio.c:23:20: fatal error: Python.h: No such file or directory
#include "Python.h"
^
compilation terminated.
error: command 'aarch64-linux-gnu-gcc' failed with exit status 1
----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-lz0hiv0m/RPi.GPIO/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('
', '
');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ldlcs6lw-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-lz0hiv0m/RPi.GPIO/
Installation des dépendances terminé !`

Il y'a 2 messages d'erreurs sur la fin, des erreurs de compile : 

> compilation terminated.
> error: command 'aarch64-linux-gnu-gcc' failed with exit status 1

> compile" failed with error code 1 in /tmp/pip-build-lz0hiv0m/RPi.GPIO/

bref c'est un peu la panade :o)

**Comment by egmaf** [comment]
+1

**Comment by doudz** [comment]
Je vais corriger ça.
Si vous avec quelques connaissances en ligne de commande linux vous pouvez lancer la commande suivante avant de relancer l'installation des dépendances:
`sudo apt-get install python3-dev
`

**Comment by doudz** [comment]
Une mise à jour sera dispo demain, à tester
