### ISSUE TITLE
Problème détection port USB

### ISSUE THREAD

**Issue by Hwoahwoa** [Jeedom-Zigate/jeedom-plugin-zigate#199]
Hello,

J'ai rencontré un petit problème avec le plugin pour détecter le port USB, pour résoudre le problème j'ai modifier le code de : /var/www/html/plugins/zigate/plugin_info/configuration.php

- Après le 'foreach getUsbMapping' (ligne : 63), j'ai ajouter ça :
```
foreach (ls('/dev/', 'tty*') as $value) {
        echo '<option value="/dev/' . $value . '">/dev/' . $value . '</option>';
}
# Code récupéré du plugin SMS
```
Car apriori dans certain cas, le getUsbMapping ne fonctionne pas. 

Si vous pouviez accéder à ma demande, ça m'éviterai de devoir rechanger le code après chaque update 👍 

Merci :)

**Comment by doudz** [comment]
C'est une bonne idée, je vais mixer les 2 solutions ainsi on aura toujours les valeurs fournies par getUsbMapping en premier puis la liste /dev/tty*** au cas où

**Comment by doudz** [comment]
C'est fait !
