### ISSUE TITLE
Page de gestion du plugin vide

### ISSUE THREAD

**Issue by sbernardfr** [Jeedom-Zigate/jeedom-plugin-zigate#205]
Bonjour,
Je viens de recevoir ma ZiGate et installé le plugin ZiGate dans Jeedom sous Debian.
Malheureusement la page de gestion du plugin reste vide.

**Pour Reproduire**
Etapes pour reproduire le problème dans Jeedom:
1. Cliquer sur 'Plugins/Protocole domotique/Zigate'

**Fonctionnement attendu**
L'installation s'est bien déroulée et le démon a démarré.
Lorsque je rafraichis la page, les menus apparaissent avec des accolades {{ }} et rien ne se passe

**Screenshots**
<img width="458" alt="Capture" src="https://user-images.githubusercontent.com/10796055/62698381-4b13a380-b9dd-11e9-974c-6b2d96462316.png">

**Informations:**
- Version Debian : bullseye/sid
- Version Jeedom : 3.3.29
- Version Plugin : 1.3.3
- Version lib zigate : 0.32.0
- Version du firmware : 3.1a

**Comment by doudz** [comment]
Est-ce que les autres pages de Jeedom fonctionnent ?
Le fait de voir les accolades {{}} dans le menu indique que la traduction n'a pas été chargé, et ça c'est du ressort du fonctionnement interne de Jeedom, pas du plugin Zigate

**Comment by sbernardfr** [comment]
Les autres pages de Jeedom fonctionnent mais comme vous le voyez sur le screenshot les traductions apparaissent également entre accolades. Y aurait-il un terme manquant dans le dictionnaire?

**Comment by doudz** [comment]
Ce problème d'accolade est surement un bug de Jeedom.
Par ailleurs, la page de gestion n'est pas vide, je vois sur la capture d'écran les bouton "Inclusion" etc
quel est vraiment le problème avec le plugin ?

**Comment by doudz** [comment]
Par ailleurs vous utilisez bullseye/sid, êtes-vous certains que Jeedom supporte cette version ? (notamment la version de PHP)

**Comment by doudz** [comment]
Je confirme que le bug, j'ai reproduit le même problème sur buster
Le plugin semble générer une erreur 500 qui met le bazard, je cherche pourquoi car je ne trouve aucune erreur dans les logs pour le moment

**Comment by doudz** [comment]
C'est corrigé, dispo demain sur le market.
Je ne sais pas depuis quand ce bug existe, il semblerait que la dernière version de Jeedom couplé à la dernière version de php ait enfin fait remonté le problème.

**Comment by sbernardfr** [comment]
Merci, je vérifie demain...

Le ven. 9 août 2019 à 14:37, Sébastien RAMAGE <notifications@github.com> a
écrit :
