### ISSUE TITLE
Plus de remontée de données modules Xiaomi

### ISSUE THREAD

**Issue by ChristopherLF30** [jeedom-zigate/jeedom-plugin-zigate#206]
**Description du bug**
Bonjour,

Au bout d’un certain temps, les modules Xiaomi ne remontent plus leurs informations. 

La solution est de relancer le demon et cela fonctionne à nouveau mais jusqu’au prochain bug. 

Est-il possible d’avoir de l’aide SVP ?

**Informations:**
- Type de l'équipement : Tous les modules Xiaomi [lumi.sensor, ....]
- Version Jeedom : 3.3.29
- Version Plugin : 1.3.4
- Version lib zigate : 0.32.1
- Version du firmware : 3.0d

**Comment by doudz** [comment]
Bonjour,
Il s'agit probablement d'une défaillance du module USB-TLL, est-ce qu'il s'agit du modèle "Prolific" ?
Si oui je vous invite à vous rapprocher de zigate.fr afin de faire un diagnostique plus poussé
A noter quand même que la version 0.32.1 peut avoir améliorer les choses car il y a un système de reconnexion automatique au bout de 5 minutes

**Comment by ChristopherLF30** [comment]
Il s’agIt effectivement du modèle Prolific. 

Le problème viendrait de la clé Zigate en elle même ?

**Comment by doudz** [comment]
La clé zigate est en réalité composé de 2 modules :
- La zigate, c'est à dire le module qui communique avec les appareils zigbee
- Un adaptateur USB-TTL pour que la zigate dialogue avec Jeedom (ou autre),  c'est cet adaptateur qui peut être défaillant (il y a eu qq problème chez certains utilisateurs avec le modèle Prolific)

**Comment by doudz** [comment]
Le problème est exposé ici
https://github.com/fairecasoimeme/ZiGate/issues/199

**Comment by ChristopherLF30** [comment]
D’accord, je vais essayer de les contacter. 

Depuis la MaJ de ce matin, j’ai cette notification Jeedom qui se répète :

Failed to connect, retry in 1 sec...

C’est lié à ce même soucis de clé ?

**Comment by ChristopherLF30** [comment]
Merci pour le lien, bon l’anglais et moi ça fait 8 mais je vais essayer de voir ça.

**Comment by doudz** [comment]
Est-ce que le compteur "retry" augmente ?
par exemple 
Failed to connect, retry in 1 sec...
Failed to connect, retry in 3 sec...
Failed to connect, retry in 5 sec...

ou juste de temps en temps "Failed to connect, retry in 1 sec..."

**Comment by ChristopherLF30** [comment]
Non juste 1 sec

**Comment by doudz** [comment]
C'est donc que la reconnexion automatique fonctionne
je pourrais avoir un extrait des heures où ça se produit ? pour voir quel est l'interval entre deux reconnexion

**Comment by doudz** [comment]
Oh je viens de voir que le firmware est 3.0d, il faut vraiment passer à une version supérieure, la dernière étant 3.1a.
La version 3.0d va faire se déclencher la reconnexion systématiquement au bout de 5min

**Comment by ChristopherLF30** [comment]
10h01min47sec
12h01min48sec

Il semblerait que ce soit toutes les 2 heures. 

Je sais qu’il faudrait que je passe en 3.1a mais là perte de mes modules me fait peur puis le passage à la nouvelle version me paraît assez compliqué pour le newbie que je suis.

**Comment by doudz** [comment]
La version 3.1a ne perd rien, il y a un système de migration interne. Il n'est plus nécessaire de faire un reset complet de la zigate après le flashage.

**Comment by ChristopherLF30** [comment]
Bien, je vois que je ne vais pas avoir le choix alors. 

Merci en tout cas pour vos retours et votre réactivité.

**Comment by doudz** [comment]
Dans tous les cas la reconnexion automatique devrait compenser le dysfonctionnement de l'adaptateur et donc "résoudre" le problème de remontée

**Comment by ChristopherLF30** [comment]
Ok. 

Du coup le message : Failed to connect, retry in 1 sec... ne pose pas de problème particulier ?

**Comment by doudz** [comment]
Non, Ça indique juste que la clé n'est plus connecté et que la première tentative de reconnexion a échoué mais comme ça s'arrête là ça signifie que la 2e tentative a fonctionné et que la clé est à nouveau connecté

**Comment by ChristopherLF30** [comment]
Je m’en doutais. 

Bon du coup il va sérieusement falloir que je me penche sur la MAJ de la Zigate alors. 

Encore merci en tout cas.

**Comment by ChristopherLF30** [comment]
Après avoir passé en revu le lien https://github.com/fairecasoimeme/ZiGate/issues/199 #MerciGoogleTraduction 😅

Si je comprends bien, l’idéal serait de remplacer le module USB PL2303 de la Zigate par un CP2102.  

Le remplacement du module couplé à la MaJ Zigate 3.1a devrait donc résoudre les soucis de remontée de données.
