### ISSUE TITLE
Probleme installation dépendances

### ISSUE THREAD

**Issue by Cyril25000** [jeedom-zigate/jeedom-plugin-zigate#215]
Bonjour,

Je remet à jour ce post car j'ai ré-installer l'ensemble raspberry + jeedom.

Il n'y a aucune erreur dans le log d'installation des dépendances pour le plugin Zigate, pourtant ca ne met statut NOK à la fin.

Voici les versions : 
Zigate : 1.3.5 (2019-08-10 02:22:24)
Jeedom : 3.3.29
Raspberry : Pi3b+.

Voici le log : 

> 

Installation des dépendances
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
python3 is already the newest version (3.7.3-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
python3-pip is already the newest version (18.1-5+rpt1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
python3-requests is already the newest version (2.21.0-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
python3-setuptools is already the newest version (40.8.0-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
python3-rpi.gpio is already the newest version (0.7.0~buster-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
python3-dev is already the newest version (3.7.3-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: zigate==0.32.2 in /usr/local/lib/python3.7/dist-packages (0.32.2)
Installation des dépendances terminé !

> 
Dans le plugin zigate est toujours marqué : 
dépendances >> local >>statut : NOK
Du coup le daemon a le même état.

Merci pour votre aide.
Cyril

**Comment by doudz** [comment]
Le problème est-il toujours là avec la dernière version ?

**Comment by Cyril25000** [comment]
Oui j'ai toujours le problème. Je ne sais vraiment pas comment faire.

**Comment by doudz** [comment]
pourrais-je avoir le log de l'installation des dépendances avec la dernière version ?

**Comment by Cyril25000** [comment]
Oui bien sûr, je l'envoi vers 18h.

**Comment by Cyril25000** [comment]
Voici le log (zigate_update) en mode debug quand je relance l'installation des dépendances avec la version Zigate 2019-10-31 02:30:33

Installation des dépendances
Atteint :1 http://raspbian.raspberrypi.org/raspbian buster InRelease
Atteint :2 http://archive.raspberrypi.org/debian buster InRelease
Lecture des listes de paquets…
Lecture des listes de paquets…
Construction de l'arbre des dépendances…
Lecture des informations d'état…
python3 est déjà la version la plus récente (3.7.3-1).
0 mis à jour, 0 nouvellement installés, 0 à enlever et 110 non mis à jour.
Lecture des listes de paquets…
Construction de l'arbre des dépendances…
Lecture des informations d'état…
python3-pip est déjà la version la plus récente (18.1-5+rpt1).
0 mis à jour, 0 nouvellement installés, 0 à enlever et 110 non mis à jour.
Lecture des listes de paquets…
Construction de l'arbre des dépendances…
Lecture des informations d'état…
python3-requests est déjà la version la plus récente (2.21.0-1).
0 mis à jour, 0 nouvellement installés, 0 à enlever et 110 non mis à jour.
Lecture des listes de paquets…
Construction de l'arbre des dépendances…
Lecture des informations d'état…
python3-setuptools est déjà la version la plus récente (40.8.0-1).
0 mis à jour, 0 nouvellement installés, 0 à enlever et 110 non mis à jour.
Lecture des listes de paquets…
Construction de l'arbre des dépendances…
Lecture des informations d'état…
python3-rpi.gpio est déjà la version la plus récente (0.7.0~buster-1).
0 mis à jour, 0 nouvellement installés, 0 à enlever et 110 non mis à jour.
Lecture des listes de paquets…
Construction de l'arbre des dépendances…
Lecture des informations d'état…
python3-dev est déjà la version la plus récente (3.7.3-1).
0 mis à jour, 0 nouvellement installés, 0 à enlever et 110 non mis à jour.
Requirement already satisfied: zigate==0.33.1 in /usr/local/lib/python3.7/dist-packages (0.33.1)
Requirement already satisfied: pyserial in /usr/lib/python3/dist-packages (from zigate==0.33.1) (3.4)
Requirement already satisfied: bottle in /usr/local/lib/python3.7/dist-packages (from zigate==0.33.1) (0.12.17)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from zigate==0.33.1) (2.21.0)
Requirement already satisfied: pydispatcher in /usr/local/lib/python3.7/dist-packages (from zigate==0.33.1) (2.0.5)
Installation des dépendances terminé !

(Pas de log dispo dans log : Zigate)

Cyril

**Comment by doudz** [comment]
Ok merci .
Est-ce que jeedom est virtualisé?

**Comment by Cyril25000** [comment]
Si ça peut aider, voici une capture de la config : 
![config zigate](https://user-images.githubusercontent.com/39560781/68136775-1eacec00-ff26-11e9-891c-86e0846af2ca.png)

**Comment by Cyril25000** [comment]
non il est sur un Raspberry 3b+

**Comment by doudz** [comment]
Est-ce qu'il y a plusieurs version de python 3 d'installé?

**Comment by Cyril25000** [comment]
oui 3 versions différentes de mémoire. je me connecte dessus pour voir

**Comment by Cyril25000** [comment]
dans /usr/lib il y a les versions de Pythons :
2.7
3
3.7

**Comment by Cyril25000** [comment]
l'arborescence à l'interieur n'est pas la même  :
Pour python3 il y a un dossier dist-package qui n'existe pas dans Python 3.7. 
Voir photo
![20191104_172610_resized](https://user-images.githubusercontent.com/39560781/68138106-4dc45d00-ff28-11e9-99f6-43eabaacfb95.jpg)

**Comment by Cyril25000** [comment]
je viens de vous envoyer un email avec mon adresse perso si Teamviewer et putty peuvent aider....

**Comment by doudz** [comment]
Dsl par reçu d'email...
Effectivement un accès en console via putty serait parfait ou à défaut un accès à Jeedom
Envoiyer en PM

**Comment by Cyril25000** [comment]
Bonjour,

Est-ce ici votre email perso (MP) ?

J suis prêt pour Teamviewer, putty et jeedom quand vous voulez.

Merci

Cyril
________________________________

**Comment by Cyril25000** [comment]
Je ne sais pas comment vous écrire en MP :-/.

**Comment by Cyril25000** [comment]
Je ne sais pas comment vous écrire en MP.

Cyril

________________________________

**Comment by Ngawang67** [comment]
J'ai exactement le même problème...
Voici mon log :

Installation des dépendances
Hit:1 http://raspbian.raspberrypi.org/raspbian stretch InRelease
Hit:2 http://archive.raspberrypi.org/debian stretch InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
python3 is already the newest version (3.5.3-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
python3-pip is already the newest version (9.0.1-2+rpt2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
python3-requests is already the newest version (2.12.4-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
python3-setuptools is already the newest version (33.1.1-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
python3-rpi.gpio is already the newest version (0.6.5~stretch-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
python3-dev is already the newest version (3.5.3-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: zigate==0.33.1 in /usr/local/lib/python3.5/dist-packages
Installation des dépendances terminé !

**Comment by doudz** [comment]
Je pense qu'il faudrait migrer vers Jeedom 4

**Comment by Cyril25000** [comment]
Je confirme : passez en Jeedom 4 à solutionné ce problème.

**Comment by Ngawang67** [comment]
Ok, je vais tenter la migration, et je vous dis si ça a marché.

Question : mes sauvegardes marcheront encore sous jeedom 4 ?

**Comment by doudz** [comment]
Aucune idée, il faut se tourner vers Jeedom pour avoir des informations, via le forum par exemple

**Comment by Ngawang67** [comment]
J'ai fait la mise à jour. 
Pas d'bol, c'est tout pareil qu'avant... sauf le mode sombre.

**Comment by doudz** [comment]
@Ngawang67 assez étrange... est-ce que je pourrais avoir un accès distant à Jeedom pour comprendre ce qu'il se passe ?

**Comment by Ngawang67** [comment]
Oui, bien sûr. Comment veux-tu procéder ?

**Comment by Ngawang67** [comment]
Je t'envoie un mail...

**Comment by doudz** [comment]
@Ngawang67 un message via https://community.jeedom.com/ fonctionne également

**Comment by Ngawang67** [comment]
Je précise à tout hasard que le bluetooth du Raspberry est bien arrêté.
Je ne vois pas quoi faire de plus.
