### ISSUE TITLE
Pas de mémorisation de l'extinction de la led bleue

### ISSUE THREAD

**Issue by OUARZA** [jeedom-zigate/jeedom-plugin-zigate#216]
**Description du bug**
Si on redémarre Jeedom, la led bleue de la clé va se rallumer alors qu'on a configuré l'extinction.

**Fonctionnement attendu**
Le paramètre d'extinction de la led bleue soit mémorisée.

**Pour Reproduire**
Etapes pour reproduire le problème:
1. Se rendre dans le plugin Zigate
2. Cliquer sur Terminal
3. Saisir 0x0018 dans dans Commande et 00 dans Data puis cliquer sur Envoyer
4. Redémarrer Jeedom

**Informations:**
- Type de l'équipement : [lumi.sensor, ....] NC
- Version Jeedom : 3.3.32
- Version Plugin : 1.3.5
- Version lib zigate : 0.32.2
- Version du firmware : 3.0f

**Comment by doudz** [comment]
corrigé en v1.5.0
