### ISSUE TITLE
Rafraichissement feignant

### ISSUE THREAD

**Issue by sifus** [jeedom-zigate/jeedom-plugin-zigate#217]
Hello,

Il est 22h47 et j'ai encore les températures de 19h53 su mon Jeedom. De plus l'heure affichée semble être H-1.

Comparativement, mes sondes EnOcean se mettent à jour toutes les 20 minutes.

Jeedom 3.3.33

clé et plugin Zigate :
Version plugin 1.3.5
Version lib 0.32.2
Version firmware 3.1a

Sonde temp Xiaomi

**Comment by sifus** [comment]
Hello,

j'ai acheté la clé Zigate et donc je dépend pour certain appareil de cette clé. Pouvez vous répondre s'il vous plait. Sinon je dois vous retourner la clé pour remboursement.

GIT est le seul endroit ou vous contacter.

**Comment by doudz** [comment]
Le problème est-il toujours là avec la dernière version ?

**Comment by sifus** [comment]
Yes, toujours. Hier soir mes modules remontaient toujours la température de 19h alors qu'il était 00h...

**Comment by doudz** [comment]
Quel est le lqi du capteur ? 
Est-ce que je pourrais avoir une capture d'écran de l'historique des valeurs ?

**Comment by sifus** [comment]
J'ai trois capteurs : LQI = 141, 106, 57

Un des capteurs :
<img width="1251" alt="Capture d’écran 2019-11-04 à 13 12 14" src="https://user-images.githubusercontent.com/2979258/68120076-bc8fbf00-ff04-11e9-99c9-8ef2eb140c9d.png">

**Comment by doudz** [comment]
Je pourrais avoir le même graph mais du capteur enocean pour comparer sur la même période ?

**Comment by sifus** [comment]
Yes, voila
<img width="1253" alt="Capture d’écran 2019-11-04 à 13 24 14" src="https://user-images.githubusercontent.com/2979258/68120740-6ae83400-ff06-11e9-8d50-9783dfe7ee67.png">

**Comment by sifus** [comment]
...et d’ailleurs je viens de voir que j'ai souvent un problème de "retry connextion".
A qui je dois m'adresser pour changer le module USB ?
<img width="1492" alt="Capture d’écran 2019-11-04 à 13 23 10" src="https://user-images.githubusercontent.com/2979258/68120830-979c4b80-ff06-11e9-9304-b2dab8e875d0.png">

**Comment by doudz** [comment]
Merci.
Est-ce que le problème de rafraichissement n'est pas simplement une question de sensibilité du capteur xiaomi ? d'après le graph il semblerait que la température change par palier de 0.4 ou 0.5°  alors que le capteur enocean semble plus sensible.
le delta de température est peut-être réglable dans la sonde.
il y a peut-être un filtre dans Jeedom ?

Par ailleurs les problèmes de déconnexion peuvent aussi être un souci
pour le remplacement du module TTL il faut voir avec @akila de zigate.fr

**Comment by doudz** [comment]
@sifus si je compare avec mes capteur xiaomi, je note que les "carrés" sont assez sensible, delta d'environ 0.1°C alors que les modèles rond ont un delta de 0.5°C

**Comment by pipiche38** [comment]
@doudz , si je peu me permettre les Xiaomi envoient une trame toutes les 50 minutes avec les infos - qu'il y ait ou pas variation - Cluster: 0x0000, Attribut: 0xff01 ou 0xff02 (suivant le modèle). On y trouve l'etat de la batterie et d'autres information tel que Temp, Press, Humi ..

**Comment by sifus** [comment]
Oh mince j'avais pourtant regardé pleins de tests sur les deux versions du capteur et personne ne parlait de cet écart de sensibilité !
Je suis triste :(

Bon par contre je viens passer le plugin zigate en bêta et j'ai refais l'association de tous les capteurs (sans les supprimer dans Jeedom) et là, ca va... les capteurs remontent les infos régulièrement.

Il ne reste plus qu'à corriger le problème de fuseau horaire (décalage d'une heure).

**Comment by doudz** [comment]
@pipiche38 oui effectivement, mais pour le moment je n'extrait que les informations de batterie de ces attributs

**Comment by doudz** [comment]
@sifus pour le fuseau horaire, l'explication est la suivante :
Le plugin utilise le fuseau horaire du système alors que Jeedom semble avoir son propre réglage
Il faut donc modifier le fuseau horaire du système Linux.
Sous raspbian par exemple:
`sudo dpkg-reconfigure tzdata`

**Comment by sifus** [comment]
> @sifus pour le fuseau horaire, l'explication est la suivante :
> Le plugin utilise le fuseau horaire du système alors que Jeedom semble avoir son propre réglage
> Il faut donc modifier le fuseau horaire du système Linux.
> Sous raspbian par exemple:
> `sudo dpkg-reconfigure tzdata`

Ah cool, bien vu !
J'ai changé la timezone dans raspi-config et c'est bon :)
