### ISSUE TITLE
Ajout d’une commande pourcentage de batterie en plus de la commande voltage

### ISSUE THREAD

**Issue by ThomasMillochau** [jeedom-zigate/jeedom-plugin-zigate#219]
Bonjour,

Je viens d’installer le plugin zigate avec ma clé zigate usb-ttl v3.1a et j’ai inclus deux capteurs xiaomi (Open Sensor et Temperature sensor)
Le plugin zigate reconnait correctement le capteur et affiche un pourcentage de batterie dans la fiche Equipement mais dans la fiche Commandes il n’y a que la commande battery_voltage qui est disponible.

Serait-il possible de rajouter une commande battery_level en plus de battery_voltage dans la liste des commandes pour les capteurs sur pile? Sans ça il n’est pas possible de récupérer cette valeur de pourcentage de batterie en tant qu’objet jeedom…

Merci d’avance,

Thomas

**Comment by smulle48** [comment]
Any news on this?

I'm looking for the same. Can't really use voltage in homebridge

**Comment by ThomasMillochau** [comment]
Bonjour, même en version 1.3.3 du plugin je n'ai pas la commande battery_level. Existe-t-il un moyen de rajouter cette commande? 

Merci d'avance, 

Thomas

**Comment by ThomasMillochau** [comment]
Une simple aide pour rajoute manuellement une commande serait top déjà.

Merci d'avance, 

Thomas

**Comment by doudz** [comment]
ok j'ajoute la fonction dans la prochaine version
Par contre attention, compatible Jeedom V4 uniquement (pour le moment)

**Comment by doudz** [comment]
Fix in 1.5.1
