### ISSUE TITLE
Impossible d'appareiller mes capteurs Xiaomi (nouvelle installation)

### ISSUE THREAD

**Issue by sirpapy** [Jeedom-Zigate/jeedom-plugin-zigate#220]
Bonjour,

Je viens de recevoir ma clé Zigate USB et je l'ai mis à jour au Firmware 3a.1
J'ai un HP Proliant dans lequel j'ai installé un Jeedom en Docker avec le plugin Zigate.
La clé est bien reconnu par Jeedom (je vois les informations de version etc). Mais quand je passe en mode inclusion pour ajouter un nouveau Device Xiaomi il y a que la lumière bleu qui clignote et après plus rien ne se passe. J'ai beau refaire l'opération(reset Capteur, repassage en mode inclusion) mais j'ai aucun ajout.

Pouvez vous m'aidez svp?

Merci beaucoup

**Comment by xbo45** [comment]
Bonjour,
j'ai le même pb sur un nas Synology (916+) avec Docker quand la zigate est branchée sur un port USB3.
Sur un USB2 ça fonctionne.
Sur un hub USB3, pourtant branché sur la même prise USB2 du NAS, ca ne fonctionne pas non plus.
Pour l'instant la seule solution que j'ai trouvée est de brancher la zigate seule sur cette prise USB2.

**Comment by sirpapy** [comment]
Bonjour Xbo45, 
Je pense que vous méritez une médaille. C'est exactement ça le problème. Je vous remercie vraiment.
Merci
