### ISSUE TITLE
sirene Heiman

### ISSUE THREAD

**Issue by jlagrut01** [jeedom-zigate/jeedom-plugin-zigate#223]
bonjour,

je viens d'installer la sirène Heiman : installation sans problème.

par contre, lorsque je créé un scénario, je n'ai que l'action Refresh de disponible. Est ce normal ?

merci pour votre aide,
Jerome

**Informations:**
- Type de l'équipement : sirene Heiman
- Version Jeedom : 3.3.35
- Version Plugin : 1.4.0
- Version lib zigate : 0.33.1
- Version du firmware : 3.1a

**Comment by doudz** [comment]
c'est "normal" pour le moment, je dois ajouter les actions prochainement

**Comment by jlagrut01** [comment]
bonjour,
je viens de tester aujourd'hui avec la v1.4.1 mais je n'arrive pas à faire fonctionner la sirène.
je n'ai que Refresh dans les actions.
que faut il faire ?
merci
Jerome

**Comment by doudz** [comment]
Les sirènes sont compatibles à partir de la version 1.5, donc Jeedom V4.
Pas de support pour Jeedom v3 je suis désolé

**Comment by jlagrut01** [comment]
Ok, merci pour l'info, je vais passer en V4.
Si je suis en V4, le plugin 1.5 est dispo ?
Merci pour ton aide,
Jerome

Le jeu. 5 déc. 2019 à 19:41, Sébastien RAMAGE <notifications@github.com> a
écrit :

**Comment by doudz** [comment]
Oui, Jeedom V4 va proposer automatiquement la version v1.5

**Comment by jlagrut01** [comment]
Merci bien, installation V4 bien passée, je pense que ma v1.5 va bientôt
redescendre

Le jeu. 5 déc. 2019 à 20:47, Sébastien RAMAGE <notifications@github.com> a
écrit :

**Comment by jlagrut01** [comment]
Est ce que je peux forcer la redescente de la v1.5 car Jeedom V4 ne me la
propose toujours pas ?
(Ma config accepte les beta)

Merci,
Jérôme

**Comment by doudz** [comment]
Étrange d'autant que la beta est en 1.5.1

**Comment by jlagrut01** [comment]
bonjour Doudz
les sirenes sont bien installées.
j'ai tout de même un problème : elles sonnent 2 sec puis s'arrêtent ! je n'arrive pas à les faire sonner en continue.
est ce normal ?
merci,
Jérôme
