### ISSUE TITLE
Rafraichissement imposible "selectionnez un zigate"

### ISSUE THREAD

**Issue by sifus** [jeedom-zigate/jeedom-plugin-zigate#224]
Lorsque l'on clique sur rafraichir un module un message d'erreur apparait et nous demande "Veuillez d'abord sélectionner un zigate"

<img width="1678" alt="Capture d’écran 2019-11-04 à 15 02 16" src="https://user-images.githubusercontent.com/2979258/68126526-4bf09e80-ff14-11e9-876f-382e757414c3.png">

Informations:
- Type de l'équipement : lumi.sensor_magnet
- Version Jeedom : 3.3.35
- Version plugin 1.4.0
- Version lib 0.33.1
- Version firmware 3.1a

**Comment by nlhomme** [comment]
Bonsoir,

Je confirme rencontrer la même difficulté sur le même écran, qu'il s'agisse de rafraîchir un équipement, le découvrir ou l'identifier.


    Type de l'équipement : tous
    Version Jeedom : 3.3.35
    Version plugin 1.4.0
    Version lib 0.33.1
    Version firmware 3.1a

Cordialement

**Comment by 0k1745** [comment]
Bonjour,

Je rencontre la même difficulté, rien de spécial dans les logs. Cela n'empêche pas la récupération d'information.

Type de l'équipement : tous
Version Jeedom : v4.0.26 Jeedom Delta
Version plugin 1.4.0
Version lib 0.33.1
Version firmware 3.1a

**Comment by YohannsMonnier** [comment]
Bonjour même soucis et même difficulté à récupérer les commandes complètes des nouveaux appareils ajoutés à la Zigate.

**Comment by Fabsky** [comment]
Pareil .. J'ai des composants qui se font éjecter, et plus moyen de les ré-inclure. Du coup ma domotique est en train de tomber petit à petit ...

**Comment by fairecasoimeme** [comment]
Je pense que le problème vient de la nouvelle mise à jour Jeedom. 
La classe utilisé avant a changé :

Dans le fichier: 
zigate\desktop\js\zigate.js
--> la classe li_eqLogic n'existe plus

chez moi, elle est remplacé par : eqLogicDisplayCard

En remplaçant à la main, ça remarche.

@doudz peux-tu confirmer / infirmer ?

Fred

**Comment by Fabsky** [comment]
De mon côté j'ai modifié le fichier et remplacé "li_eqLogic" par "eqLogicDisplayCard" (de mémoire 6 remplacements)
Ça a en effet  l'air de remarcher complètement !!
Merci

**Comment by doudz** [comment]
Je confirme que c'est la modification à faire, je la met en beta.
Par ailleurs, je me demande depuis quand ça a changé car ça doit faire un bon moment que ça ne fonctionne plus...

**Comment by fairecasoimeme** [comment]
voici ma modif au cas où pour pas perdre la retro compatibilité :

`$('.eqLogicAction[data-action=refresh_device]').on('click', function () {
    if ($('.li_eqLogic.active').attr('data-eqLogic_id') != undefined) {
		id = $('.li_eqLogic.active').attr('data-eqLogic_id');
        refresh_eqlogic(id);
	}else if ($('.eqLogicDisplayCard.active').attr('data-eqLogic_id') != undefined) {
        id = $('.eqLogicDisplayCard.active').attr('data-eqLogic_id');
        refresh_eqlogic(id);
	}else {
        $('#div_alert').showAlert({message: '{{Veuillez d\'abord sélectionner un}} ' + eqType, level: 'danger'});
    }
});

$('.eqLogicAction[data-action=discover_device]').on('click', function () {
    if (($('.li_eqLogic.active').attr('data-eqLogic_id') != undefined) || ($('.eqLogicDisplayCard.active').attr('data-eqLogic_id') != undefined) ) {
        id = $('.eqLogicDisplayCard.active').attr('data-eqLogic_id');
        discover_eqlogic(id);
    }else if ($('.eqLogicDisplayCard.active').attr('data-eqLogic_id') != undefined) {
        id = $('.eqLogicDisplayCard.active').attr('data-eqLogic_id');
        discover_eqlogic(id);
	} else {
        $('#div_alert').showAlert({message: '{{Veuillez d\'abord sélectionner un}} ' + eqType, level: 'danger'});
    }
});

$('.eqLogicAction[data-action=identify_device]').on('click', function () {
    if (($('.li_eqLogic.active').attr('data-eqLogic_id') != undefined) || ($('.eqLogicDisplayCard.active').attr('data-eqLogic_id') != undefined) ) {
        id = $('.eqLogicDisplayCard.active').attr('data-eqLogic_id');
        identify_device(id);
    }else if ($('.eqLogicDisplayCard.active').attr('data-eqLogic_id') != undefined) {
        id = $('.eqLogicDisplayCard.active').attr('data-eqLogic_id');
        identify_device(id);
	} else {
        $('#div_alert').showAlert({message: '{{Veuillez d\'abord sélectionner un}} ' + eqType, level: 'danger'});
    }
});`

**Comment by ludo1227** [comment]
Bonjour,
Tout novice dans le domaine, j'ai les mêmes problèmes.
Comment faites vous pour trouver le fichier et le modifier?
En faisant un "find" sur mon rpi, il ne trouve pas le fichier à modifier...
Merci d'avance

**Comment by doudz** [comment]
Le plus simple serait peut-être de passer le plugin en beta dès demain pour avoir la modification

**Comment by ludo1227** [comment]
Merci @doudz 
Je dois mettre à jour le plugin directement via Jeedom ou il faut passer en lignes de commandes (si oui, lesquelles?)?
Merci encore

**Comment by doudz** [comment]
Via jeedom en autorisant les versions bêta dans les paramètres

**Comment by ludo1227** [comment]
Merci beaucoup! Cela fonctionne!

**Comment by Kazfr** [comment]
J'ai aussi eu la moitié de mes équipements désactivés subitement avec l'impossibilité de pouvoir les réactiver pour la deuxième fois. C'est arrivé ou du moins ça a démarré avec la dernière maj de jeedom. Me concernant, je vais simplement modifier avec le fix de Doudz et reset l'ensemble par manque de temps pour débugger ça.

Pour information ma configuration est la suivante:
- Zigate usb
- Jeedom 4.0.28
- Version plugin 1.4.0
- Version lib 0.33.1
- Version firmware 3.1a

**Comment by Kenderv** [comment]
> Via jeedom en autorisant les versions bêta dans les paramètres  

> 

Bonjour,
J'aile même problème et je voudrais simplement savoir où et comment on autorise les versions beta dans les paramètres.
Merci

**Comment by jiquem** [comment]
Regression sur la maj de hier 

jeedom@jeedom:/var/www/html/plugins/zigate/desktop/js$ ls -l zigate.js 
-rwxrwxr-x 1 www-data www-data 11177 Nov 29 10:58 zigate.js
jeedom@jeedom:/var/www/html/plugins/zigate/desktop/js$ grep li_eqLogic zigate.js 
    if ($('.li_eqLogic.active').attr('data-eqLogic_id') != undefined) {
        id = $('.li_eqLogic.active').attr('data-eqLogic_id');
    if ($('.li_eqLogic.active').attr('data-eqLogic_id') != undefined) {
        id = $('.li_eqLogic.active').attr('data-eqLogic_id');
    if ($('.li_eqLogic.active').attr('data-eqLogic_id') != undefined) {
        id = $('.li_eqLogic.active').attr('data-eqLogic_id');

**Comment by doudz** [comment]
Je ne vois pas cette régression sur la dernière version
https://github.com/jeedom-zigate/jeedom-plugin-zigate/blob/master/desktop/js/zigate.js#L115

@jiquem est-ce que tu utilises Jeedom v3 ?
Désormais les nouvelles versions du plugin seront uniquement compatible V4...

**Comment by jiquem** [comment]
Oui, je suis en v3... j'hésite à passer en v4

**Comment by FrosT6969** [comment]
Bonjour,
Je suis aussi novice: y a t-il moyen de le faire encore fonctionner sur une V3 et si oui comment ? Merci à vous

**Comment by doudz** [comment]
Je viens de porter la modification pour Jeedom v3, vous aurez une mise à jour du plugin en v1.4.1

**Comment by Fabsky** [comment]
> Désormais les nouvelles versions du plugin seront uniquement compatible V4...

Oula ... alors même que la V4 est pas sortie ? c'est gros ça...
En tout cas c'est bon à savoir, j'appliquerais plus aucune màj du plugin.

**Comment by doudz** [comment]
hum, la V4 est pas encore sortie ? ça fait tellement longtemps que Jeedom envoie des emails à ce sujet que je pensais que c'était sortie... désolé, n'utilisant pas Jeedom moi même je ne suis pas vraiment au courant de ces choses là.

Si vous êtes en stable, il y a 2 versions du plugin, les versions 1.4.* compatibles V3 et les versions 1.5 et supérieures pour la V4
Normalement Jeedom propose la bonne version, 1.4 pour la V3 et 1.5 pour la V4

Par contre pour la version béta, il n'y a qu'une version, celle compatible V4

**Comment by doudz** [comment]
Ceci dit, je veux bien laisser la compatibilité avec la V3 mais il faut savoir que je ne pourrais pas la tester donc en cas de problème, soit qqn peut proposer la solution, soit vous aurez des réponses du genre "il faut d'abord migrer Jeedom en V4"
Je suis navré mais étant seul (ou pratiquement) à développer le plugin je ne peux être sur tous les fronts

**Comment by Fabsky** [comment]
Non la v4 est en RC, sauf erreur de ma part.
Pour la compatibilité, en fait c'est juste que si on a une V3 il ne faudrait pas se prendre une update v4 et que plus rien ne marche. Je sais pas si c'est possible avec les plugins jeedom. 
Sinon au pire avoir l'info. La page changelog a été mise à jour, donc je pense que c'est bon, juste que je suppose que certaines personnes font la mise à jour sans lire le changelog (pas bien).
Mais en tout cas merci pour le correctif.

**Comment by doudz** [comment]
@Fabsky D'après https://community.jeedom.com/t/rtex-debian-10-buster-netinst-amd64-jeedom-v4/2510 
et comme on peut le vérifier ici : https://github.com/jeedom/core/blob/master/install/install.sh#L339
c'est bien la version V4 qui s'intalle par défaut maintenant lorsqu'on installe Jeedom

Je considère donc que la V4 est la version officielle

**Comment by Fabsky** [comment]
@doudz  En effet tu as raison, dans les scripts c'est mis en stable. Par contre aucune comm sur [leur blog](https://www.jeedom.com/blog/) depuis l'annonce de la RC (ça date quand même de fin août), et aucune màj dispo dans l'interface utilisateur, donc màj possible uniquement via script. Pour moi ça ressemble quand même à du RC :)
De toute façon la v4 même en RC est probablement utilisable sans problème. Faudrait que je me mette dessus un moment pour màj, mais trop de chose à faire :s
