### ISSUE TITLE
Problème lors de l'ajout d'un détecteur de fumée xiaomi

### ISSUE THREAD

**Issue by Kazfr** [Jeedom-Zigate/jeedom-plugin-zigate#225]
Je me permet un rapide retour concernant le détecteur de fumée Honeywell/xiaomi que je viens d'intégrer dans Jeedom.

Je ne vois aucun retour d'état sur les alarmes déclenchées (Par un coup de vapotage bien dense...) :) Idem pour les tests. Graphiquement le device est assez incompréhensible.

Est-il correctement géré par la Zigate ?

**Screenshots**
https://framapic.org/Z78F3WA7lLNZ/AIzHpIniyenr.png

**Informations:**
- Type de l'équipement : lumi.sensor_smoke
- Version Jeedom : 4
- Version Plugin : 1.4.0
- Version lib zigate : 0.33.1
- Version du firmware : 3.1a

**Comment by sifus** [comment]
Hello moi de min coté ça fonctionne j'ai bien un retour d'alarme sous Jeedom avec le plugin alarme.

Jeedom version 3.3.35
Zigate 3.1a

**Comment by Kazfr** [comment]
Hello et depuis les différents éléments historisés, je pense que ça doit apparaître dans alarme1 ou 2... Tu vois un évènement quand tu déclenche le détecteur  ?

**Comment by Kazfr** [comment]
Après une nouvelle exclusion/inclusion. Tous semble ok !
