### ISSUE TITLE
Plantage régulier deamon

### ISSUE THREAD

**Issue by djsyl** [jeedom-zigate/jeedom-plugin-zigate#226]
Bonjour a tous,

 Je constate un :
Plantage régulier deamon zigate dans jeedom 4 
que je soit zigate USB
ou zigate sur plug wifi 

Pret a aider si il le faut ...

**Informations:**
- Type de l'équipement :5 capteur xiaomi 2 decteteur de mouvement 2 contact d'ouverture 1 bouton
- Version Jeedom : 4
- Version plugin 1.4.1beta
- Version lib 0.33.1
- Version firmware 3.1a

Pour avoir une idée en moins d'une heure  ...
[zigate.log](https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/files/3864420/zigate.log)

Date et heure | Source | Description | Action | Occurrences
  | 2019-11-19 15:54:59 | zigate | Failed to connect, retry in 38 sec... |   | 40
  | 2019-11-19 15:45:37 | zigate | Failed to connect, retry in 25 sec... |   | 2
  | 2019-11-19 15:45:13 | zigate | Failed to connect, retry in 17 sec... |   | 2
  | 2019-11-19 15:44:56 | zigate | Failed to connect, retry in 11 sec... |   | 2
  | 2019-11-19 15:44:43 | zigate | Failed to connect, retry in 7 sec... |   | 2
  | 2019-11-19 15:44:31 | zigate | Failed to connect, retry in 5 sec... |   | 2
  | 2019-11-19 15:44:25 | zigate | Failed to connect, retry in 3 sec... |   | 2
  | 2019-11-19 15:44:19 | zigate | Failed to connect, retry in 2 sec... |   | 2
  | 2019-11-19 15:44:13 | zigate | Failed to connect, retry in 1 sec... |   | 4

**Comment by doudz** [comment]
Est-ce que je pourrais avoir les logs avec des déconnexions en USB et un autre en Wifi ?

**Comment by djsyl** [comment]
Désolé doudz vue le manque réactivité je suis passé sur le plugin abeille qui semble lui ne pas planté au niveau du demon les erreur dans le log en version USB étaient presque identique.
je ne manquerai pas de tester a nouveau le plugin zigate lorsqu'il aura avancé un peut plus.

a bientôt courage

**Comment by doudz** [comment]
Pas de pb
