### ISSUE TITLE
Erreurs lors du dernier lancement des dépendances

### ISSUE THREAD

**Issue by Kenderv** [jeedom-zigate/jeedom-plugin-zigate#228]
Bonjour,
Voici les logs du dernier lancement des dépendances :
Installation des dépendances
Get:1 http://archive.raspberrypi.org/debian stretch InRelease [25.4 kB]
Get:2 http://raspbian.raspberrypi.org/raspbian stretch InRelease [15.0 kB]
Get:3 http://raspbian.raspberrypi.org/raspbian stretch/main armhf Packages [11.7 MB]
Get:4 http://archive.raspberrypi.org/debian stretch/main armhf Packages [220 kB]
Fetched 11.9 MB in 29s (398 kB/s)
Reading package lists...
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: zigate==0.33.1 in /usr/local/lib/python3.5/dist-packages (0.33.1)
Requirement already satisfied: pyserial in /usr/local/lib/python3.5/dist-packages (from zigate==0.33.1) (3.4)
Requirement already satisfied: pydispatcher in /usr/local/lib/python3.5/dist-packages (from zigate==0.33.1) (2.0.5)
Requirement already satisfied: bottle in /usr/local/lib/python3.5/dist-packages (from zigate==0.33.1) (0.12.16)
Requirement already satisfied: requests in /usr/local/lib/python3.5/dist-packages (from zigate==0.33.1) (2.21.0)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.5/dist-packages (from requests->zigate==0.33.1) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.5/dist-packages (from requests->zigate==0.33.1) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.5/dist-packages (from requests->zigate==0.33.1) (2018.11.29)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/local/lib/python3.5/dist-packages (from requests->zigate==0.33.1) (1.24.1)
WARNING: You are using pip version 19.1.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Installation des dépendances terminé !

Est-ce normal et sinon que dois-je faire pour régler le problème ?
Merci de ton aide

**Comment by doudz** [comment]
Il y a effectivement des erreurs présentent dans le log mais elles n'ont a priori pas empêché l'installation des dépendances.
Le plugin fonctionne normalement non ?

Le problème concerne le gestionnaire de paquet apt, pour résoudre le souci il suffit de faire ce qui est indiqué, c'est à dire lancer la commande suivante sudo dpkg --configure -a

**Comment by Kenderv** [comment]
Merci de ta réponse. Oui, le plugin semble fonctionner normalement.
J'ai lancé la commande indiquée mais il semble qu'il y ait des différences entre le package installé et le nouveau.
 A new version (/usr/lib/php/7.0/php.ini-production.cli) of configuration  │
 │ file /etc/php/7.0/cli/php.ini is available, but the version installed     │
 │ currently has been locally modified.                                      │
 │                                                                           │
 Line by line differences between versions
 │
 │ --- /etc/php/7.0/cli/php.ini root.root 0644 2018-04-24 15:59:11
 │ +++ /usr/lib/php/7.0/php.ini-production.cli root.root 0644 2019-09-18
 │ 11:55:34
 │ @@ -356,7 +356,7 @@
 │  ; threat in any way, but it makes it possible to determine whether you
 │ use PHP
 │  ; on your server or not.
 │  ; http://php.net/expose-php
 │ -expose_php = Off
 │ +expose_php = On
 │
 │  ;;;;;;;;;;;;;;;;;;;
│  ; Resource Limits ;
 │ @@ -365,7 +365,7 @@
 │  ; Maximum execution time of each script, in seconds
 │  ; http://php.net/max-execution-time
 │  ; Note: This directive is hardcoded to 0 for the CLI SAPI
 │ -max_execution_time = 300
 │ +max_execution_time = 30
 │
 │  ; Maximum amount of time each script may spend parsing request data.
 │ It's a good
 │  ; idea to limit this time on productions servers in order to eliminate
 │ unexpectedly
 │ @@ -653,7 +653,7 @@
 │  ; Its value may be 0 to disable the limit. It is ignored if POST data
 reading
 │  ; is disabled through enable_post_data_reading.
 │  ; http://php.net/post-max-size
 │ -post_max_size = 1G
 │ +post_max_size = 8M
 │
 │  ; Automatically add files before PHP document.
 │  ; http://php.net/auto-prepend-file
 │ @@ -806,7 +806,7 @@
 │
 │  ; Maximum allowed size for uploaded files.
 │  ; http://php.net/upload-max-filesize
 │ -upload_max_filesize = 1G
 │ +upload_max_filesize = 2M
 ; Maximum number of files that can be uploaded via a single request
 │  max_file_uploads = 20
 │ @@ -969,8 +969,19 @@
 │  ;intl.use_exceptions = 0
 │
 │  [sqlite3]
 │ +; Directory pointing to SQLite3 extensions
 │ +; http://php.net/sqlite3.extension-dir
 │  ;sqlite3.extension_dir =
 │
 │ +; SQLite defensive mode flag (only available from SQLite 3.26+)
 │ +; When the defensive flag is enabled, language features that allow
 │ ordinary
 │ +; SQL to deliberately corrupt the database file are disabled. This
 forbids
 │ +; writing directly to the schema, shadow tables (eg. FTS data tables),
 │ or
 │ +; the sqlite_dbpage virtual table.
 │ +; https://www.sqlite.org/c3ref/c_dbconfig_defensive.html
 │ +; (for older SQLite versions, this flag has no use)
 │ +sqlite3.defensive = 1
 │ +
 │  [Pcre]
 │  ;PCRE library backtracking limit.
 │  ; http://php.net/pcre.backtrack-limit
 │ @@ -1764,10 +1775,10 @@
 │
 │  [opcache]
│  ; Determines if Zend OPCache is enabled
 │ -opcache.enable=1
 │ +;opcache.enable=0
 │
 │  ; Determines if Zend OPCache is enabled for the CLI version of PHP
 │ -opcache.enable_cli=1
 │ +;opcache.enable_cli=0
 │
 │  ; The OPcache shared memory storage size.
 │  ;opcache.memory_consumption=64

Dois-je répondre OK ?
Merci

**Comment by doudz** [comment]
Je dirais qu'il faut choisir l'option permettant de conserver/garder l'existant (je ne sais pas s'il faut répondre oui ou non car je n'ai pas la question sous les yeux)
Il ne faut pas installer la nouvelle version du paquet
On évitera ainsi des problèmes
