### ISSUE TITLE
Mise à jour du 20/11/2019

### ISSUE THREAD

**Issue by lmangone** [jeedom-zigate/jeedom-plugin-zigate#229]
La dernière  mise à jour du plugin semble faire passer de la v1.4.0 en v1.3.3 normal ?

**Comment by doudz** [comment]
C'est normal si vous utilisez Jeedom v3, la version 1.4 requiert la version 4 de Jeedom

**Comment by lmangone** [comment]
Le problème c'est que post mise à jour en v1.3.3 la page des équipements ne s'affiche plus du tout... je suis bien en v3.3.37 pour jeedom.

**Comment by doudz** [comment]
La v1.4.0 fonctionnait sur jeedom v3?

**Comment by lmangone** [comment]
Oui c'est la seule version qui fonctionne pour l'instant. J'ai un firmware update de la lib en attente cependant.

**Comment by doudz** [comment]
Ok merci, je vais porter la v1.4.0 sur Jeedom 3

**Comment by lmangone** [comment]
J'avais le même soucis avec le plugin CloudSync pro et j'ai dû prendre la version bêta faite pour Buster. Je ne suis pas certain par exemple que la v1.4.0 fonctionne sous une Stretch.

**Comment by doudz** [comment]
En principe le plugin fonctionne avec Stretch

**Comment by lmangone** [comment]
Alors tout devrais aller.
