### ISSUE TITLE
Zigate HS

### ISSUE THREAD

**Issue by Kazfr** [jeedom-zigate/jeedom-plugin-zigate#230]
Bonsoir, 

Je me permet un rapide message concernant les problèmes que je rencontre avec la Zigate depuis quelques jours (Je me demande si ce n'est pas la dernière maj de Jeedom qui provoque ça). Concrètement, j'ai ce genre d'erreur et par la suite, l'ensemble des équipements zigbee est HS:

> [2019-11-24 19:50:45][ERROR][zigate](ZiGate-Decode data) : RESPONSE 0x8702 - APS Data Confirm Fail : status:240, source_endpoint:1, dst_endpoint:1, dst_address_mode:2, dst_address:c7e7, sequence:218, lqi:0
> [2019-11-24 20:00:58][ERROR][zigate](ZiGate-Decode data) : RESPONSE 0x8702 - APS Data Confirm Fail : status:240, source_endpoint:1, dst_endpoint:1, dst_address_mode:2, dst_address:1f1d, sequence:219, lqi:0
> [2019-11-24 20:01:13][ERROR][zigate](ZiGate-Decode data) : RESPONSE 0x8702 - APS Data Confirm Fail : status:240, source_endpoint:1, dst_endpoint:1, dst_address_mode:2, dst_address:8c8f, sequence:220, lqi:0
> [2019-11-24 20:04:10][ERROR][zigate](ZiGate-Decode data) : RESPONSE 0x8702 - APS Data Confirm Fail : status:240, source_endpoint:1, dst_endpoint:1, dst_address_mode:2, dst_address:734f, sequence:221, lqi:0
> [2019-11-24 20:11:23][ERROR][zigate](ZiGate-Decode data) : RESPONSE 0x8702 - APS Data Confirm Fail : status:233, source_endpoint:1, dst_endpoint:1, dst_address_mode:2, dst_address:30cb, sequence:226, lqi:0
> [2019-11-24 20:14:56][ERROR][zigate](ZiGate-Decode data) : RESPONSE 0x8702 - APS Data Confirm Fail : status:240, source_endpoint:1, dst_endpoint:1, dst_address_mode:2, dst_address:83a0, sequence:228, lqi:0
> [2019-11-24 20:34:55][ERROR][zigate](ZiGate-Decode data) : RESPONSE 0x8702 - APS Data Confirm Fail : status:240, source_endpoint:1, dst_endpoint:1, dst_address_mode:2, dst_address:82da, sequence:230, lqi:0
> [2019-11-24 20:43:28][ERROR][zigate](ZiGate-Decode data) : RESPONSE 0x8702 - APS Data Confirm Fail : status:240, source_endpoint:1, dst_endpoint:1, dst_address_mode:2, dst_address:c7e7, sequence:231, lqi:0
> [2019-11-24 20:44:50][ERROR][zigate](ZiGate-Decode data) : RESPONSE 0x8702 - APS Data Confirm Fail : status:240, source_endpoint:1, dst_endpoint:1, dst_address_mode:2, dst_address:9452, sequence:232, lqi:0
> [2019-11-24 21:01:14][ERROR][zigate](ZiGate-Decode data) : RESPONSE 0x8702 - APS Data Confirm Fail : status:240, source_endpoint:1, dst_endpoint:1, dst_address_mode:2, dst_address:1f1d, sequence:233, lqi:0
> [2019-11-24 21:01:32][ERROR][zigate](ZiGate-Decode data) : RESPONSE 0x8702 - APS Data Confirm Fail : status:240, source_endpoint:1, dst_endpoint:1, dst_address_mode:2, dst_address:8c8f, sequence:234, lqi:0
> [2019-11-24 21:04:31][ERROR][zigate](ZiGate-Decode data) : RESPONSE 0x8702 - APS Data Confirm Fail : status:240, source_endpoint:1, dst_endpoint:1, dst_address_mode:2, dst_address:734f, sequence:235, lqi:0
> [2019-11-24 21:10:03][ERROR][zigate](ZiGate-Decode data) : RESPONSE 0x8702 - APS Data Confirm Fail : status:212, source_endpoint:1, dst_endpoint:3, dst_address_mode:2, dst_address:2498, sequence:238, lqi:218
> [2019-11-24 21:11:09][ERROR][zigate](ZiGate-Decode data) : RESPONSE 0x8702 - APS Data Confirm Fail : status:240, source_endpoint:1, dst_endpoint:1, dst_address_mode:2, dst_address:83a0, sequence:239, lqi:0
> [2019-11-24 21:35:23][ERROR][zigate](ZiGate-Decode data) : RESPONSE 0x8702 - APS Data Confirm Fail : status:240, source_endpoint:1, dst_endpoint:1, dst_address_mode:2, dst_address:82da, sequence:242, lqi:0
> [2019-11-24 21:43:50][ERROR][zigate](ZiGate-Decode data) : RESPONSE 0x8702 - APS Data Confirm Fail : status:240, source_endpoint:1, dst_endpoint:1, dst_address_mode:2, dst_address:c7e7, sequence:243, lqi:0
> [2019-11-24 21:45:11][ERROR][zigate](ZiGate-Decode data) : RESPONSE 0x8702 - APS Data Confirm Fail : status:240, source_endpoint:1, dst_endpoint:1, dst_address_mode:2, dst_address:9452, sequence:244, lqi:0
> [2019-11-24 21:56:03][ERROR][zigate](ZiGate-Decode data) : RESPONSE 0x8702 - APS Data Confirm Fail : status:240, source_endpoint:1, dst_endpoint:1, dst_address_mode:2, dst_address:83a0, sequence:245, lqi:0
> [2019-11-24 22:01:31][ERROR][zigate](ZiGate-Decode data) : RESPONSE 0x8702 - APS Data Confirm Fail : status:240, source_endpoint:1, dst_endpoint:1, dst_address_mode:2, dst_address:1f1d, sequence:246, lqi:0
> [2019-11-24 22:01:51][ERROR][zigate](ZiGate-Decode data) : RESPONSE 0x8702 - APS Data Confirm Fail : status:240, source_endpoint:1, dst_endpoint:1, dst_address_mode:2, dst_address:8c8f, sequence:247, lqi:0
> [2019-11-24 22:04:50][ERROR][zigate](ZiGate-Decode data) : RESPONSE 0x8702 - APS Data Confirm Fail : status:240, source_endpoint:1, dst_endpoint:1, dst_address_mode:2, dst_address:734f, sequence:248, lqi:0
> [2019-11-24 22:10:03][ERROR][zigate](ZiGate-Decode data) : RESPONSE 0x8702 - APS Data Confirm Fail : status:212, source_endpoint:1, dst_endpoint:3, dst_address_mode:2, dst_address:2498, sequence:251, lqi:218
> [2019-11-24 22:35:49][ERROR][zigate](ZiGate-Decode data) : RESPONSE 0x8702 - APS Data Confirm Fail : status:240, source_endpoint:1, dst_endpoint:1, dst_address_mode:2, dst_address:82da, sequence:254, lqi:0
> [2019-11-24 22:44:13][ERROR][zigate](ZiGate-Decode data) : RESPONSE 0x8702 - APS Data Confirm Fail : status:240, source_endpoint:1, dst_endpoint:1, dst_address_mode:2, dst_address:c7e7, sequence:255, lqi:0
> [2019-11-24 22:45:37][ERROR][zigate](ZiGate-Decode data) : RESPONSE 0x8702 - APS Data Confirm Fail : status:240, source_endpoint:1, dst_endpoint:1, dst_address_mode:2, dst_address:9452, sequence:0, lqi:0
> [2019-11-24 22:50:35][ERROR][zigate](ZiGate-Decode data) : RESPONSE 0x8702 - APS Data Confirm Fail : status:240, source_endpoint:1, dst_endpoint:1, dst_address_mode:2, dst_address:83a0, sequence:1, lqi:0

Rien n'a changé dans la configuration des pièces, rien n'a été ajouté et il n'y a aucun vecteur à perturbation radio. Si je redémarre Jeedom, les devices Zigbee refonctionnent un temps et ça recommence.

Concernant la configuration:

    Zigate usb (Quasi neuve)
    Jeedom 4.0.28
    Version plugin 1.4.0
    Version lib 0.33.1
    Version firmware 3.1a

Avez vous une idée ce qui peut provoquer ça ?

**Comment by nlhomme** [comment]
Je confirme rencontrer le même problème avec la même configuration que mon voisin (à part que j'ai jeedom 3.3.38).

De mon côté j'ai ces logs:
```[2019-11-25 18:39:49][ERROR][zigate](ZiGate-Decode data) : RESPONSE 0x8702 - APS Data Confirm Fail : status:233, source_endpoint:1, dst_endpoint:1, dst_address_mode:2, dst_address:c6ef, sequence:75, lqi:0
[2019-11-25 18:41:05][ERROR][zigate](ZiGate-Decode data) : RESPONSE 0x8702 - APS Data Confirm Fail : status:212, source_endpoint:1, dst_endpoint:1, dst_address_mode:2, dst_address:ddc6, sequence:77, lqi:249
[2019-11-25 18:41:05][ERROR] : L'IEEE de l'équipement ac8a est absent, vous devriez refaire l'association
[2019-11-25 18:41:05][ERROR] : L'IEEE de l'équipement af1f est absent, vous devriez refaire l'association```

J'ai beau parcourir tous mes équipements installé, aucun n'ont "ac8a" ou "af1f" comme identifiant, je pense que ce sont des appareils que j'ai supprimé de jeedom mais qui sont resté dans la mémoire du zigate...

**Comment by doudz** [comment]
> Je confirme rencontrer le même problème avec la même configuration que mon voisin (à part que j'ai jeedom 3.3.38).
> 
> De mon côté j'ai ces logs:
> 
> ```
> [2019-11-25 18:41:05][ERROR][zigate](ZiGate-Decode data) : RESPONSE 0x8702 - APS Data Confirm Fail : status:212, source_endpoint:1, dst_endpoint:1, dst_address_mode:2, dst_address:ddc6, sequence:77, lqi:249
> [2019-11-25 18:41:05][ERROR] : L'IEEE de l'équipement ac8a est absent, vous devriez refaire l'association
> [2019-11-25 18:41:05][ERROR] : L'IEEE de l'équipement af1f est absent, vous devriez refaire l'association```
> 
> J'ai beau parcourir tous mes équipements installé, aucun n'ont "ac8a" ou "af1f" comme identifiant, je pense que ce sont des appareils que j'ai supprimé de jeedom mais qui sont resté dans la mémoire du zigate...
> ```

dans ce cas il faudrait essayer la fonction Nettoyer
![image](https://user-images.githubusercontent.com/1262548/69574522-ac7d7380-0fc8-11ea-8f47-1b106d698340.png)

**Comment by Kazfr** [comment]
Merci Doudz, en effet il semble que ça permette de clean un peu les logs etc dans la console.
De mon côté, il semblerait après une vue d'ensemble que ce soit principalement les prises IKEA qui merdouille.

Je suis aussi tombé la dessus: https://doc.eedomus.com/view/Tradfri_-_Prise_connect%C3%A9e
Je suis en train de faire l'essai.

**Comment by Kazfr** [comment]
Alors, je confirme que le problème venait principalement des prises Ikea. Je viens de faire un appui 3 sec sans activer le mode inclusion, puis de nouveau 3 sec en inclusion. Bilan, l'ADDR a changé et désormais la prise est parfaitement reconnue.

Bon j'ai pas vraiment de solution car j'ai été feignant (souhaitant que ça marche sans passer mon weekend dans les logs et les tests....) à la base et ça a été contre-productif pour bien comprendre l'ensemble :) Ce jour:

- Reflash de la zigate + eeprom
- Suppression/installation du plugin
- Réintégration de l'ensemble des capteurs (Il semble finalement que d'après mes logs ce soit seulement les IKEA qui merdouillaient...C'est aussi les plus important, du moins les plus emmerdant si ça marche pas).

Le bouton nettoyer est en effet important ici pour y voir plus clair après y inclusions etc ...Encore merci
