### ISSUE TITLE
erreur javascript

### ISSUE THREAD

**Issue by kristobal62** [jeedom-zigate/jeedom-plugin-zigate#232]
**Description du bug**
Bonjour,
Depuis la dernière j'ai supprimé un équipement puis je l'ai réinclu et depuis je n'ai plus le graphique réseau ! c'est vide et le message suivant qui s'affiche.
voici l'erreur:  ligne 87    Uncaught TypeError: Cannot read property 'id' of undefined

Sinon tout fonctionne parfaitement

**Fonctionnement attendu**
affiche du graphique réseau

**Informations:**
- Version Jeedom : V4
- Version Plugin : 1.5
- Version lib zigate : 0.34.1
- Version du firmware : 3.1a

**Comment by kristobal62** [comment]
Pour info mise à jour faite ce midi. 
Le pb est toujours là.

**Comment by kristobal62** [comment]
Pour info mise à jour en 1.5.1
Toujours la même erreur et pas de graphique réseau.

**Comment by doudz** [comment]
Avec la 1.5.1 il y a un Panneau Admin supplémentaire, qui comporte une carte du réseau, est-ce qu'elle fonctionne ?

**Comment by kristobal62** [comment]
Effectivement j'avais bien vu le nouveau panneau Admin et je viens juste de voir le network map.
Je vois bien mon réseau ;) 
D'ailleurs je constate que mon ampoule ikéa est reliée à rien !  Et pourtant elle fonctionne.
