### ISSUE TITLE
Équipement non rattachés

### ISSUE THREAD

**Issue by Flo2201** [jeedom-zigate/jeedom-plugin-zigate#234]
**Description du bug**
À la suite des différentes mise à jour, d'associations etc. J'ai 8 équipements fantômes.
J'aimerais les supprimer sans devoir remettre à zéro.

Mais cela ne fonctionne pas avec le bouton prévu à cet effet.

![Screenshot_20191203-204741_Samsung Internet](https://user-images.githubusercontent.com/58487455/70084267-47e89700-160e-11ea-8f56-8590d286b430.jpg)

**Comment by doudz** [comment]
As-tu utilisé le bouton "Nettoyage" ?

**Comment by Flo2201** [comment]
Oui, c'est bien cela le problème.


-------- Message d'origine --------
De : Sébastien RAMAGE <notifications@github.com>
Date : 04/12/2019 10:18 (GMT+01:00)
À : jeedom-zigate/jeedom-plugin-zigate <jeedom-plugin-zigate@noreply.github.com>
Cc : Flo2201 <Flo2201@live.fr>, Author <author@noreply.github.com>
Objet : Re: [jeedom-zigate/jeedom-plugin-zigate] Équipement non rattachés (#234)


As-tu utilisé le bouton "Nettoyage" ?

**Comment by doudz** [comment]
Merci d'essayer le nouveau Panneau Admin qui comporte aussi un graph

**Comment by llaumgui** [comment]
Pas de retours, on clos.
