### ISSUE TITLE
Volet Profalux

### ISSUE THREAD

**Issue by dams74** [Jeedom-Zigate/jeedom-plugin-zigate#24]
Salut j'ai testé ton pulgin ce jour.
L'inclusion fonctionne bien. Cependant j'ai plusieurs device qui ce sont crée, 4 de mémoire.
Après un reset zigate il m'en reste plus que 2.
Sur les 2 il y en a un qui marche plutôt bien:
monté 
descente
set level
current level
Par contre le set level et current level ne sont pas calibré
N'hésite pas si tu as besoin de plus d'information
Damien

**Comment by doudz** [comment]
Bizarre cette création multiple... 
Merci pour le retour en tout cas.
Est-ce que la commande toggle ajouté récemment permet de faire un stop ?
Que veux tu dire par non calibré ?

**Comment by dams74** [comment]
J'avais eu le même problème de création multiple sur abeille.
Je n'ai pas testé toggle, je ferai le test.
Je veux dire pas non calibré que lorsque je demande 50%, le volet ne se positionne pas à la moitié

**Comment by doudz** [comment]
Ok merci.
Et que se passe-t-il quand tu demandes 50% ? Est-ce que tu peux faire qq essais à différentes positions et me dire ce qu'il se passe ?
Merci d'avance

**Comment by dams74** [comment]
voilà

ouverture volet en   % | valeur en decimal
0 | 1
10 | 62
20 | 92
30 | 116
40 | 140
50 | 162
60 | 183
70 | 201
80 | 219
90 | 238
100 | 254

**Comment by doudz** [comment]
D'où sortent les valeurs en décimal ? Le pourcentage est il la position réelle du volet ?

**Comment by doudz** [comment]
Ok. 
Effectivement le déplacement n'est pas linéaire mais quel fonctionnement souhaiterais tu ?
Il est normal que la valeur level varie de 0 à 254.

Est-ce qu'il serait mieux de varier de 0 à 100 ?

**Comment by dams74** [comment]
Dans l'idéal un fonctionnement linéaire de 0 à 100% de façon que le volet s'ouvre de moitié lorsque l'on demande 50 %.
Qu'en penses-tu?

**Comment by doudz** [comment]
Éventuellement je peux faire en sorte que la valeur varie de 0 à 100 mais je ne pourrai pas faire de fonctionnement linéaire tout simplement parce que cette fonctionnalité est aussi utilisée par les ampoules.
Sauf à dire que les ampoules est le même fonctionnement non linéaire.

**Comment by doudz** [comment]
Le problème de création multiple sera résolu dans la prochaine mise à jour

**Comment by mylR42** [comment]
Bonjour,

De mon coté j'essaye d'inclure un volet PROFALUX mais cela ne fonctionne pas (1 click R puis flèche "Monter". Comment as-tu fait ?

Merci

**Comment by dams74** [comment]
Il faut d'abord faire une réinitialisation du volet par 5 appui sur R puis Stop. Ensuite la manipulation que tu as fais. Cette procédure est indiqué dans la doc profalux ou sur zigate.fr 
https://zigate.fr/2018/02/03/association-des-volets-profalux-a-la-zigate/

**Comment by doudz** [comment]
Est-ce que qqn pourrait me dire la commande Toggle permet de faire un stop du volet (étant donné que on fait la montée et off la descente)
Si la réponse est non alors j'ajouterai la commande stop lié à la gestion du level

**Comment by doudz** [comment]
Et aussi si quelqu'un peut me donner le "type" qui apparait, afin que je puisse ajouter une image ça serait top :+1:

**Comment by doudz** [comment]
Y a t il du nouveau ? Sinon je clôturerai le ticket

**Comment by dams74** [comment]
J'aurai pas le temps ces jours, ça peux attendre fin août?

**Comment by doudz** [comment]
Pas de souci

**Comment by Jamo54** [comment]
Bonjour j'ai réussi a inclure un de mes volet et il n'y a pas de commande STOP la commande toggle permet de monter ou descendre le volet une sorte de on/off sinon le level fonctionne bien. ou est ce que  je peux trouver le "type" sous jeedom que je te le redise.
Merci pour  ce que tu as fait en tout cas!!

**Comment by doudz** [comment]
Merci pour ce retour.
Le type (s'il existe) est affiché sur la page de configuration de l'équipement.

Pour la commande STOP, je vois ce qu'il faut ajouter
note pour moi même : pour les équipements supportant les commandes LEVEL, ajouter la commande stop via la fonction action_move_stop

**Comment by llaumgui** [comment]
@doudz > On en est où de ce ticket ? C'est côté lib ?

**Comment by doudz** [comment]
il faudrait voir si @Jamo54 et @dams74  ont toujours des soucis ou pas
côté plugin il fallait ajouter l'image si ce n'est pas déjà fait

**Comment by doudz** [comment]
Et je ne sais plus si j'ai ajouté la commande STOP ou pas...

**Comment by dams74** [comment]
Oui je pense qu'elle est nécessaire.
Qu'en pense les autres utilisateurs?

**Comment by doudz** [comment]
Pour voir si ça fonctionne @dams74 pourrais-tu créer un scénario script et lancer la commande suivante 
zigate::send_data("0x0083", "02**[ADDR]**0101") en remplaçant [ADDR] par l'adresse du module, exemple abcd ?
