### ISSUE TITLE
Objet pluzzy jeedom 

### ISSUE THREAD

**Issue by Breton18** [jeedom-zigate/jeedom-plugin-zigate#241]
Bonjour. 
Je cherche une solution pour des objets pluzzy ijenko avec jeedom. 
Merci

**Comment by pipiche38** [comment]
https://github.com/fairecasoimeme/ZiGate_HA1.2

**Comment by Breton18** [comment]
Bonjour,

Concernant les produits Pluzzy Ijenko, y a t il une possibilité pour les
utiliser avec la zigate et Jeedom .
Merci.
Bien cordialement
pierrick ALLEE
06 06 57 15 56

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
