### ISSUE TITLE
lumi.remote.b1acn01 commandes manquantes ? seulement multiclick

### ISSUE THREAD

**Issue by NVVNETIKA** [jeedom-zigate/jeedom-plugin-zigate#246]
Bonjour,
Avant toute chose merci pour votre travail.

Je viens de faire l'aquisition d'une clé zigate, d'un bouton poussoir xiaomi aqara et une ampoule philips HUE.

Je ne suis pas sur que mon bouton aquara soit bien reconnu car j'ai uniquement la fonction multiclick, enfin je ne sais pas trop ce que je peux faire avec les autres.
Lorsque je crée un scénario pour faire un simple ON/OFF avec un toggle sur, dès que je clique, mon ampoule s'allume et se coupe. J'ai effectivement quand je fais un click deux click qui passent dans les log.

Je me demande si dans les commandes jeedom je ne devrais pas avoir autre chose que simplement un multiclick ?

![](https://user-images.githubusercontent.com/40762697/72211051-a41fc000-34c4-11ea-9be4-4e0942f1f2d0.png)

![](https://user-images.githubusercontent.com/40762697/72211045-966a3a80-34c4-11ea-9afb-aa60a4f70800.png)

- Type de l'équipement : [lumi.remote.b1acn01]
- Version Jeedom : 4.0.38
- Version Plugin : 1.5.2
- Version lib zigate : 0.36.1
- Version du firmware : 3.1.a

Pouvez vous m'aider ?

D'avance merci.

**Comment by pickwick86** [comment]
Multiclick peut prendre 4 valeurs distinctes : 
* 0 : au repos
* 1 : sur un simple clic
* 2 : un un double clic
* 255 (ou 254, je sais plus trop de mémoire) sur un appui long.

(Et non, il ne prend pas la valeur 3 sur un triple-clic, c'est ballot)

Si tu veux des comportements différents en fonction du nombre d'appuis, construit un scenario déclenché par un changement de la valeur de cette commande dans lequel tu testes la valeur.
En gros : 

IF multiclick == 0 THEN { abandon du scenario }
ELSE IF multiclick == 1 THEN { traitement du simple clic }
ELSE IF multiclick == 2 THEN { traitement du double clic }
ELSE IF multiclick == 255 THEN { traitement de l'appui long}

**Comment by NVVNETIKA** [comment]
Bonsoir,
Merci pour la réponse.
C'est une bonne nouvelle, mon équipement est bien reconnu alors.
Il va falloir que j'essaye de comprendre comment mettre cela en place et surtout aussi avoir un peu de temps.
Bonne soirée.
