### ISSUE TITLE
Erreur installation dépendance

### ISSUE THREAD

**Issue by Theandone90** [jeedom-zigate/jeedom-plugin-zigate#247]
Je viens de recevoir ma Zigate est impossible d'installer les dépendances dans Jeedom v4.

Installation des dépendances
Hit:1 http://raspbian.raspberrypi.org/raspbian buster InRelease
Hit:2 http://archive.raspberrypi.org/debian buster InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
python3 is already the newest version (3.7.3-1).
0 upgraded, 0 newly installed, 0 to remove and 12 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
python3-pip is already the newest version (18.1-5+rpt1).
0 upgraded, 0 newly installed, 0 to remove and 12 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
python3-serial is already the newest version (3.4-4).
0 upgraded, 0 newly installed, 0 to remove and 12 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
python3-usb is already the newest version (1.0.2-1).
0 upgraded, 0 newly installed, 0 to remove and 12 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
python3-requests is already the newest version (2.21.0-1).
0 upgraded, 0 newly installed, 0 to remove and 12 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
python3-setuptools is already the newest version (40.8.0-1).
0 upgraded, 0 newly installed, 0 to remove and 12 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
python3-rpi.gpio is already the newest version (0.7.0~buster-1).
0 upgraded, 0 newly installed, 0 to remove and 12 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
python3-dev is already the newest version (3.7.3-1).
0 upgraded, 0 newly installed, 0 to remove and 12 not upgraded.
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: zigate==0.36.1 in /usr/local/lib/python3.7/dist-packages (0.36.1)
Requirement already satisfied: pydispatcher>=2.0.5 in /usr/local/lib/python3.7/dist-packages (from zigate==0.36.1) (2.0.5)
Requirement already satisfied: bottle in /usr/local/lib/python3.7/dist-packages (from zigate==0.36.1) (0.12.18)
Requirement already satisfied: pyserial>=3.2 in /usr/lib/python3/dist-packages (from zigate==0.36.1) (3.4)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from zigate==0.36.1) (2.21.0)
Requirement already satisfied: RPi.GPIO in /usr/lib/python3/dist-packages (from zigate==0.36.1) (0.7.0)
Installation des dépendances terminée !
Vérification de la version installée
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/usr/local/lib/python3.7/dist-packages/zigate/__init__.py", line 9, in <module>
from .core import (ZiGate, ZiGateWiFi, ZiGateGPIO)
File "/usr/local/lib/python3.7/dist-packages/zigate/core.py", line 17, in <module>
from .transport import (ThreadSerialConnection,
File "/usr/local/lib/python3.7/dist-packages/zigate/transport.py", line 12, in <module>
import serial.tools.list_ports
ModuleNotFoundError: No module named 'serial.tools'

**Comment by doudz** [comment]
Serial.tools fait partie du package python3-serial
Je suggère de lancer manuellement la commande suivante
sudo apt-get install python3-serial --reinstall

**Comment by Theandone90** [comment]
je viens de passer la commande mais toujours l'erreur.

**Comment by Theandone90** [comment]
Ma clé est vue comme Silicon_Labs Zigate (/dev/ttyUSB0) dans le plugin Zigate

**Comment by Theandone90** [comment]
la clé fonctionne bien avec le Plugin Abeille mais toujours le problème de dépendance sous Zigate

**Comment by Theandone90** [comment]
Je viens de trouver la source du problème.
Il fallait passer les commandes ci-dessous.
1. sudo apt remove python3-serial
2. sudo pip3 install pyserial

**Comment by doudz** [comment]
J'allais proposer "sudo pip3 uninstall pyserial" dans le cas où il y aurait un résidu d'installation qq part
si ça fonctionne maintenant c'est parfait !
