### ISSUE TITLE
Jeedom v3 me propose une màj du plugin

### ISSUE THREAD

**Issue by Fabsky** [jeedom-zigate/jeedom-plugin-zigate#253]
Hello,

Sorry si ça a déjà été demandé, j'ai cherché si il existait déjà une issue sans la trouver.

D'après le changelog seulement jeedom v4 est supportée maintenant (ce qui est dommage, car les dev de jeedom dise eux même qu'ils attendent que la v4 soit plus peaufinée pour la proposer la mise à jour ... mais c'est un autre sujet!), mais pourtant jeedom me propose une màj du plugin zigate:

![2020-01-31_18h30_38](https://user-images.githubusercontent.com/9216452/73560858-10ed0100-4458-11ea-8b52-cb74754c2ef7.png)

Est-ce que c'est normal ? J'ai pas envie de me retrouver avec un plugin pour v4 qui ne marche pas sur v3 :)

Merci!

**Comment by doudz** [comment]
J'ai fait une petite mise à jour simplement pour ajouter un message indiquant que la V3 n'est plus supporté.
Etant seul, je ne peux pas maintenir plusieurs versions

**Comment by Fabsky** [comment]
Ok, merci ! 👍
