### ISSUE TITLE
Prise courant Cleode ZPLUG

### ISSUE THREAD

**Issue by merlin-marvin** [jeedom-zigate/jeedom-plugin-zigate#255]
Bonjour et merci pour ce plugin,

avec ma PiZigate, je parviens à faire fonctionner mes périphériques Ikea et Xiaomi sans problème.

J'ai également une prise électrique commandée et mesurée que j'aimerais faire fonctionner.
L'inclusion fonctionne, en revanche je n'ai que les remontées d'infos (état de la prise et mesure courant), aucune action possible (sous Abeille avec un modèle de prise Ikea seul l'action on/off fonctionne).

Comment ajouter cette action on/off et ces différents attributs du cluster Metering ?
Plus généralement, est-il possible d'ajouter sois même des infos et actions sur des équipements ?

Voici la doc de la prise : 
Cleode Zplug
http://www.cleode.fr/fr/telecharger.php?fichier=mu_zplug.pdf

**Screenshots**
![image](https://user-images.githubusercontent.com/58307037/75136731-d76d8580-56e5-11ea-8d91-47f3b80a1b0f.png)

Log:
[zigate-cleode-zplug.log](https://github.com/jeedom-zigate/jeedom-plugin-zigate/files/4243558/zigate-cleode-zplug.log)

Merci

**Comment by doudz** [comment]
Il n'est pas possible d'ajouter soit même des info et/ou commandes.
Pourrais-je avoir le fichier zigate.json ou un l'extrait de ce fichier concernant cet équipement afin de comprendre pourquoi les commandes on et off ne sont pas disponible ?

**Comment by merlin-marvin** [comment]
Voici:

       {
            "addr": "e8fb",
            "discovery": "auto-discovered",
            "endpoints": [
                {
                    "clusters": [
                        {
                            "attributes": [
                                {
                                    "attribute": 0,
                                    "name": "zcl_version",
                                    "value": null
                                },
                                {
                                    "attribute": 1,
                                    "name": "application_version",
                                    "value": null
                                },
                                {
                                    "attribute": 2,
                                    "name": "stack_version",
                                    "value": null
                                },
                                {
                                    "attribute": 3,
                                    "name": "hardware_version",
                                    "value": null
                                },
                                {
                                    "attribute": 4,
                                    "data": "CLEODE",
                                    "name": "manufacturer",
                                    "value": "CLEODE"
                                },
                                {
                                    "attribute": 5,
                                    "data": "ZPLUG",
                                    "name": "type",
                                    "type": "str",
                                    "value": "ZPLUG"
                                },
                                {
                                    "attribute": 6,
                                    "name": "datecode",
                                    "value": null
                                },
                                {
                                    "attribute": 7,
                                    "name": "power_source",
                                    "value": null
                                },
                                {
                                    "attribute": 16,
                                    "name": "description",
                                    "value": null
                                },
                                {
                                    "attribute": 17
                                },
                                {
                                    "attribute": 18
                                },
                                {
                                    "attribute": 19
                                }
                            ],
                            "cluster": 0
                        },
                        {
                            "attributes": [
                                {
                                    "attribute": 0,
                                    "data": "\u0000\u0000\u0000\u0000",
                                    "name": "current_delivered",
                                    "type": "float",
                                    "value": "\u0000\u0000\u0000\u0000"
                                },
                                {
                                    "attribute": 512
                                },
                                {
                                    "attribute": 770
                                },
                                {
                                    "attribute": 771
                                },
                                {
                                    "attribute": 772
                                },
                                {
                                    "attribute": 774
                                },
                                {
                                    "attribute": 769
                                },
                                {
                                    "attribute": 768
                                },
                                {
                                    "attribute": 1024,
                                    "data": 0
                                }
                            ],
                            "cluster": 1794
                        },
                        {
                            "attributes": [
                                {
                                    "attribute": 0
                                }
                            ],
                            "cluster": 3
                        },
                        {
                            "attributes": [
                                {
                                    "attribute": 0
                                }
                            ],
                            "cluster": 4
                        },
                        {
                            "attributes": [
                                {
                                    "attribute": 0
                                },
                                {
                                    "attribute": 1
                                },
                                {
                                    "attribute": 2
                                },
                                {
                                    "attribute": 3
                                },
                                {
                                    "attribute": 4
                                }
                            ],
                            "cluster": 5
                        },
                        {
                            "attributes": [
                                {
                                    "attribute": 0,
                                    "data": true,
                                    "name": "onoff",
                                    "type": "bool",
                                    "value": true
                                }
                            ],
                            "cluster": 6
                        }
                    ],
                    "device": 9,
                    "endpoint": 1,
                    "in_clusters": [
                        0,
                        3,
                        4,
                        5,
                        6,
                        1794
                    ],
                    "out_clusters": [],
                    "profile": 260
                }
            ],
            "generictype": "",
            "info": {
                "addr": "e8fb",
                "bit_field": "0100000000010001",
                "descriptor_capability": "00000000",
                "id": 41,
                "ieee": "00124b000122d799",
                "last_seen": "2020-02-24 12:15:29",
                "lqi": 84,
                "mac_capability": "",
                "manufacturer_code": "10b9",
                "max_buffer": 80,
                "max_rx": 160,
                "max_tx": 160,
                "power_type": 1,
                "server_mask": 0
            }
        },

**Comment by doudz** [comment]
Quelle est votre version du plugin ?

**Comment by merlin-marvin** [comment]
1.4.1 sur jeedom 3.3.39

**Comment by doudz** [comment]
ok, le problème vient de là
Il faudrait migrer vers Jeedom v4 afin d'avoir la dernière version du plugin qui contient déjà une correction.
Le plugin pour la version 3 de Jeedom n'évoluera plus

**Comment by merlin-marvin** [comment]
Ok je vais travailler là dessus. Je vous tiens au courant
Merci

**Comment by merlin-marvin** [comment]
passage en V4 ok, le plugin quand à lui est toujours en 1.4.1.
Il faut passer en beta ?

**Comment by merlin-marvin** [comment]
Voilà c'est ok, effectivement je retrouve bien les commandes d'action.
![image](https://user-images.githubusercontent.com/58307037/75157513-90e34f80-5714-11ea-9bd2-c1a27cc3e2bb.png)

Merci
