### ISSUE TITLE
Problème de maillage

### ISSUE THREAD

**Issue by elcaribou12** [jeedom-zigate/jeedom-plugin-zigate#258]
Bonjour,

J'ai un gros problème maillage avec un pizigate et jeedom v4 / plugin v1.6.4 sur rpi4 à savoir que des ampoules Hue qui doivent normalement être des routeurs sont totalement isolés voir non fonctionnels. Je voulais savoir s'il y avait une action a réaliser pour les forcer en routeur et ainsi étendre le réseau.

![image](https://user-images.githubusercontent.com/44969500/79465064-2c00f300-7ffb-11ea-8777-af08502cccd2.png)

Je précise aussi que le maillage n'est pas visible dans l'onglet Santé (rien ne s'affiche) et j'ai une erreur Javascript : 

https://mon serveur/index.php?v=d&m=zigate&p=zigate&id=zigate | 87 | Uncaught TypeError: Cannot read property 'id' of undefined
-- | -- | --

Merci d'avance.

**Comment by llaumgui** [comment]
Ce graphique va être supprimé et remplacé par le panneau Zigate admin
