### ISSUE TITLE
Volet Profalux

### ISSUE THREAD

**Issue by i2a-orta** [jeedom-zigate/jeedom-plugin-zigate#260]
**Description du bug**
Bonjour, je suis sur une installation jeedom fraîche, je voulais migrer de domoticz vers jeedom.
Lorsque je tente d'intégrer mes volet Profalux, j'ai 2 devices (normal de ce que j'avais vu sur domoticz, il y a télécommande et le volet).
A priori mon volet n'est pas reconnu comme étant "profalux", ils ont le type "unsupported".
A chaque relance du plugin zigate, j'obtient une popup m'invitant à "raffraichir l'équipement".
L'appuis sur le bouton, n'a pas l'air de faire grand chose...
Au niveau des logs de la zigate j'ai ce type de message:
`[2020-04-25 13:29:37][ERROR][zigate](ZiGate-Decode data) : Command 0x0140 failed E_ZCL_ERR_ZTRANSMIT_FAIL : b''
[2020-04-25 13:29:37][ERROR][zigate](ZiGate-Decode data) : Command 0x0140 failed E_ZCL_ERR_ZTRANSMIT_FAIL : b''
[2020-04-25 13:29:37][ERROR][zigate](ZiGate-Decode data) : Command 0x0140 failed E_ZCL_ERR_ZTRANSMIT_FAIL : b''
[2020-04-25 13:29:37][ERROR][zigate](ZiGate-Decode data) : Command 0x0140 failed E_ZCL_ERR_ZTRANSMIT_FAIL : b''`

Du coup, il me manque quelques commandes comme on, off, stop, level ect... sur l'insertion d'un autre volet, les commandes arrivent aux comptent goute, mais lorsque j'appuie dessus, il ne se passe rien...

**Pour Reproduire**
Une simple synchro.

**Fonctionnement attendu**
Avoir toutes les commandes lors de l'intégration, et faire en sorte qu'elle fonctionne :)

**Screenshots**
![image](https://user-images.githubusercontent.com/62966868/80280745-48411600-8706-11ea-9107-9b1f7d861775.png)

**Informations:**
- Type de l'équipement : Volet Profalux Zigbee
- Version Jeedom : 4.0.52
- Version Plugin : 1.6.4
- Version lib zigate : 0.38.6
- Version du firmware : 3.1c

**Comment by antfleu** [comment]
Ils sont galère à inclure.
 Il faut fermer ton volet, lancer un découverte sur device volet (pas la télécommande) et ouvrir/fermer 2 fois, à la fin de la 2ème fermeture il doit faire un va et vient. 
Pour le type unsupported pas d’inquiétude par contre suite à la manip précédente tu devrais avoir Profalux d’indiquer sur manufacturer

**Comment by i2a-orta** [comment]
A priori c'est bien ca, super capricieux 👍
Je ne me souvenez pas avoir autant galéré avec c'est volet :o

**Comment by pipiche38** [comment]
Ce n'est pas capricieux, c'est qu'il faut surtout ne pas etre en mode Permit To Join quand est fait le Reset sur la télécommande.
Pour plus d'infos, je maintiens cela pour les profalux et la Zigate
