### ISSUE TITLE
Jeedom-Zigate-NOK

### ISSUE THREAD

**Issue by killerloop23** [jeedom-zigate/jeedom-plugin-zigate#284]
Bonjour,

Le module Zigate ne fonctionne pas. Impossible de lancer le Demon.
J'ai réinstallé L'OS sur le raspberry sans succes
J'ai fait remplacer me module Zigate Pi en pensant qu'il etait HS sans succes
L'installation de Jeedom est vierge , il n'y a que le plugin Zigate

Informations:

    Version Jeedom : 4.0.61
    Version Plugin : 1.7.4
    Version lib zigate :
    Version du firmware :

Voici le log :
[2020-09-19 09:43:57][ERROR] : Attention je pense qu'il y a un soucis avec le démon que j'ai relancé plus de 3 fois consécutivement
[2020-09-19 08:43:59][ERROR][zigate](ZiGate-Listen) : OOPS connection lost, reconnect...
[2020-09-19 08:44:24][ERROR][zigate](MainThread) : Failed to get network state
[2020-09-19 08:44:47][ERROR][zigate](MainThread) : Failed to start network
Traceback (most recent call last):
File "/var/www/html/plugins/zigate/core/class/../../resources/zigated/zigated.py", line 336, in <module>
if version < '3.0d':
TypeError: '<' not supported between instances of 'NoneType' and 'str'

![image](https://user-images.githubusercontent.com/71544589/93662116-c0b1c600-fa5d-11ea-94d9-9a8184762f75.png)
Ciblé ou auto j ai la meme erreur

regards

**Comment by doudz** [comment]
Quel est le type de Zigate ?

**Comment by killerloop23** [comment]
Module Zigate avec ZigBee pour Raspberry Pi - Zigate
REF : ZIG_ZIGATEPI acheté chez espace domotique

en // ce matin j'ai installé le projet « node-zigate« trouvé sur github

voici la log en temps reel : 
pi@raspberrypi:~/zigate $ node /home/pi/zigate
body-parser deprecated undefined extended: provide extended option index.js:17:17
finished loading 10 types from '/home/pi/zigate/node_modules/node-zigate/devices': osram_smart_plus_plug, xiaomi_cube_magic, xiaomi_door_sensor, xiaomi_motion_sensor, xiaomi_remote_wall_switch_double, xiaomi_remote_wall_switch_single, xiaomi_sensor_weather, xiaomi_switch_key, xiaomi_vibration_sensor, xiaomi_water_sensor
starting zigate driver...
Server running on port 3000
[Driver] successfully connected ZiGate port '/dev/ttyAMA0' ; retriveing version.
[Driver] sending command:  version(0x10), timestamp:2020-9-19 9:15:44.727
[Driver] sending frame: 01 00 10 00 00 10 03
[Driver] sending raw frame: 01 02 10 02 00 02 10 02 10 02 00 03
[Driver] received raw frame: 01 00 80 02 10 02 10 02 15 95 02 10 02 10 02 10 10 02 10
[Driver] unescaped frame: 01 00 80 00 00 05 95 00 00 00 10 00
[Driver] ERROR:  Error: [Driver] corrupted frame received: inconsistent frame length attribute (0) vs. payload length (0) + 1 (rssi). 01 00 80 00 00 05 95 00 00 00 10 00
[Driver] received raw frame: 01 80 10 02 10 02 15 8f 02 10 02 13 02 13 1a 02 10
[Driver] unescaped frame: 01 80 10 00 05 8f 00 03 03 1a 00
[Driver] response received:  version(0x8010), major:3, installer:794, rssi:0
version info received. major=3 ; installer=794 ; firmware= 0.NaN
[Driver] sending command:  permit_join(0x49), address:0xfffc, duration:30, significance:0, timestamp:2020-9-19 9:17:23.158
[Driver] sending frame: 01 00 49 00 04 50 ff fc 1e 00 03
[Driver] sending raw frame: 01 02 10 49 02 10 02 14 50 ff fc 1e 02 10 03
[Driver] received raw frame: 01 80 02 10 02 10 02 15 4c 80 02 10 02 10 49 02 10
[Driver] unescaped frame: 01 80 00 00 05 4c 80 00 00 49 00
[Driver] response received:  status(0x8000), status:{"id":"0x80","name":"unknown"}, sequence:0, relatedTo:permit_join(0x49), rssi:0
[Driver] status received & matched with command 'permit_join(0x49)'
inclusion mode started for 30 seconds.
MGR ::: Start Inclusion
MGR ::: Stop Inclusion

**Comment by doudz** [comment]
Pour la pizigate vous devez cocher la case correspondante dans la configuration

**Comment by killerloop23** [comment]
Fait ! effectivement ca fonctionne le daemon reste up.... dsl pour le derangement 
merci
