### ISSUE TITLE
Support du module SONOFF SNZB-01

### ISSUE THREAD

**Issue by tuxgasy** [jeedom-zigate/jeedom-plugin-zigate#285]
Bonjour,

J'ai acquis le module [SONOFF SNZB-01](https://sonoff.tech/product/smart-home-security/snzb-01). J'ai pu l'intégré dans Jeedom mais il me manque la commande permettant de détecter les clics sur le bouton.

Voici l'équipement dans Jeedom :
![image](https://user-images.githubusercontent.com/3997123/96606552-b0f4fe00-12f7-11eb-8a91-53b8b2dcebb5.png)

![image](https://user-images.githubusercontent.com/3997123/96606604-c0744700-12f7-11eb-81be-c36760b76394.png)

Je suis nocif sur Jeedom et Zigate. Comment puis-je faire pour debugger et améliorer éventuellement le module ?

Merci de votre retour.

**Informations:**
- Type de l'équipement : interrupteur
- Version Jeedom : 4.0.61
- Version Plugin : 1.7.5
- Version lib zigate : 0.40.9
- Version du firmware : 3.1a

**Comment by tuxgasy** [comment]
Si ça peut aider, voici le contenu du fichier zigate.json :

```json
{
    "addr": "6e92",
    "discovery": "auto-discovered",
    "endpoints": [
        {
            "clusters": [
                {
                    "attributes": [
                        {
                            "attribute": 4,
                            "data": "eWeLink",
                            "name": "manufacturer",
                            "value": "eWeLink"
                        },
                        {
                            "attribute": 5,
                            "data": "WB01",
                            "name": "type",
                            "type": "str",
                            "value": "WB01"
                        }
                    ],
                    "cluster": 0
                },
                {
                    "attributes": [
                        {
                            "attribute": 32,
                            "data": 39,
                            "name": "battery_voltage",
                            "type": "float",
                            "value": 3.9
                        },
                        {
                            "attribute": 33,
                            "data": 200,
                            "name": "battery_percent",
                            "type": "int",
                            "value": 200
                        }
                    ],
                    "cluster": 1
                }
            ],
            "device": 0,
            "endpoint": 1,
            "in_clusters": [
                0,
                3,
                1
            ],
            "out_clusters": [
                6,
                3
            ],
            "profile": 260
        }
    ],
    "generictype": "",
    "info": {
        "addr": "6e92",
        "bit_field": "0100000000000010",
        "descriptor_capability": "00000000",
        "ieee": "00124b0022285e09",
        "last_seen": "2020-10-20 18:52:19",
        "lqi": 84,
        "mac_capability": "10000000",
        "manufacturer_code": "0000",
        "max_buffer": 80,
        "max_rx": 160,
        "max_tx": 160,
        "server_mask": 0
    },
    "name": ""
}
```

**Comment by doudz** [comment]
> Je suis **nocif** sur Jeedom et Zigate.
J'imagine que vous voulez dire novice, enfin j'espère ;-)

Sinon concernant le problème, il faudrait essayer d'actionner les boutons pour tenter de faire apparaître les commandes.

Je n'ai pas cet équipement donc il faudrait voir avec les informations présentent sur zigate.fr ou sur le forum jeedom.
Pistes possibles :
- faire un bind (commande 0x0030) et configurer le reporting (commande 0x0120)
- placer la zigate et l'équipement dans le même groupe zigbee

**Comment by tuxgasy** [comment]
Oui novice  :smile:

J'ai tenté d'actionner plusieurs fois. Et aussi supprimer et réinclure le module mais sans succès.

J'ai rien trouvé sur ce module sur Jeedom.

J'ai tenté les 2 commandes bind et reporting pas de changement.

Par contre comment mettre dans le même groupe ?

Merci de ton retour.

**Comment by peporl** [comment]
Bonjour,

Avez-vous réussi à l'utiliser?

Merci

**Comment by tuxgasy** [comment]
Malheureusement, non. Si vous avez une piste, je serai intéressé.

**Comment by peporl** [comment]
J'ai acheté le plugin Zigbee (zigbee) - beta les sonoff snzb-xx sont reconnus

**Comment by tuxgasy** [comment]
Vous parlez de ce plugin ou d'un autre?

**Comment by peporl** [comment]
Il s'agit d'un autre plugin

**Comment by tuxgasy** [comment]
Je n'ai pas trouvé sur le market. Avez-vous le lien vers ?

**Comment by peporl** [comment]
voici attention c'est en beta
https://market.jeedom.com/index.php?v=d&p=market_display&id=zigbee

**Comment by tuxgasy** [comment]
J'ai testé. Le module SONOFF fonctionne effectivement. Mais le plugin bugge beaucoup :
- il faut tenter plusieurs fois pour inclure un module (voir impossible pour les modules avec pile)
- perte de lien avec les modules sans raison et obligé de refaire une inclusion

Le module n'est pas encore utilisable. J'ai une [clé zigate](https://zigate.fr/produit/zigate-ttl/).

**Comment by peporl** [comment]
Oui c'est encore en beta.

J'ai réussi à inclure mes capteurs températures, pir et boutons.
J'ai remarqué que lors de l'inclusion une fois l'appareil détecté il y a un message synchro dans 60 s. la il ne faut plus rien toucher et laisser faire.

**Comment by tuxgasy** [comment]
Quel modèle de clé zigbee vous utiliser ?

**Comment by Adrenah** [comment]
Bonjour, 

Avez-vous réussi à faire fonctionner vos bouton sonoff ?
J'ai reçu les miens il y a une semaine, et depuis, impossible d'avoir un meilleur rendu que celui de votre premier post !

Je suis sur Jeedom en V4.1.22
Version plugin 1.7.6
Version lib 0.40.11
Version firmware 3.1d

**Comment by tuxgasy** [comment]
J'utilise le module officiel zigbee qui est en stable maintenant.

**Comment by Adrenah** [comment]
Merci pour le retour !
Je pensais bien au plugin officiel mais je n'ai trouvé nulle part la liste des équipements fonctionnels à l'heure actuelle.
Savez-vous où est-ce que je peux la trouver ?
J'ai plusieurs module Aqara. Je préfère être sûr qu'ils sont opérationnels avec ...

**Comment by Adrenah** [comment]
J'ai trouvé le site tant cherché !
Pour ceux que ça intéresse le voici : https://compatibility.jeedom.com/

**Comment by chameaudesmers** [comment]
Bonjour,
J'utilise une clef zigate et le plugin zigate et j'ai le même problème que le premier post. Je n'ai pas trouvé de solution et l'utilisation du plugin zigbee n'a pas aidé non plus. Est-ce que quelqu'un a trouvé comment ajouter les actions on/off sur le module sonoff?
Par ailleurs, j'ai aussi d'autres modules sonoff de détection présence et ouverture de porte et j'ai exactement le même problème: zigate liste les infos du module mais pas les actions possibles.
Je dois rater quelque-chose...

**Comment by peporl** [comment]
Bonjour, 
Avec le plugin abeille les modules sont bien gèrés
Cordialement

**Comment by chameaudesmers** [comment]
Merci Peporl. J'ai effectivement réussi à utiliser mon interrupteur avec le plugin abeille. Les autres matériels sonoff ont l'air un peu moins immédiats à ajouter, mais ça semble plus prometteur que le plugin zigate. Je progresse...
