### ISSUE TITLE
Pb d'ajout de la zigate à Jeedom

### ISSUE THREAD

**Issue by Samsool** [jeedom-zigate/jeedom-plugin-zigate#286]
Bonsoir, 

Etant débutant, j'ai un soucis pour ajouter ma clé Zigate à Jeedom. Le Daemon passe NOK après un bref passage OK et je ne peux rien ajouter comme capteurs.
J'ai suivi la doc pour l'installation et le paramétrage, je veux bien s'il vous plait un coup de main.

Voici un log en PJ.
[zigate_logSM.txt](https://github.com/jeedom-zigate/jeedom-plugin-zigate/files/5425421/zigate_logSM.txt)

Merci !

**Comment by doudz** [comment]
Quel est le modèle de zigate ?

**Comment by Samsool** [comment]
Merci pour votre retour. J'avais branché la clé à l'envers, le boulet. Tout
marche !

Le ven. 23 oct. 2020 à 16:52, Sébastien RAMAGE <notifications@github.com> a
écrit :
