### ISSUE TITLE
Nouveau logo

### ISSUE THREAD

**Issue by llaumgui** [Jeedom-Zigate/jeedom-plugin-zigate#41]
Le logo actuel ne respecte pas complètement les guidelines Jeedom. Il faudrait le modifier (fond, police, etc...).

**Comment by llaumgui** [comment]
Vous en pensez quoi ?
![zigate_icon](https://user-images.githubusercontent.com/411360/44919162-19aa4680-ad3d-11e8-9b03-0a9b8eb95512.png)

**Comment by llaumgui** [comment]
Ou alors:
![template_icon](https://user-images.githubusercontent.com/411360/44919421-cdabd180-ad3d-11e8-8f62-81ec69c6d39a.png)

**Comment by doudz** [comment]
Pour ma part je dirais trop vert, c'est trop loin du code couleur initiale
Moi je garderais les ondes bleus et la police grise claire, et pour le fond, pourquoi pas blanc et le contour gris clair comme la police

**Comment by Karreg** [comment]
J'aime bien la version verte.
Par contre j'éviterais le logo de zigate pour des raisons de droit. Il est libre de droit ?
Dans l'absolu, c'est la même chose pour le nom du plugin, d'autant plus qu'il bosse lui aussi sur un plugin jeedom...

**Comment by llaumgui** [comment]
@doudz 
> Pour ma part je dirais trop vert, c'est trop loin du code couleur initiale

Je suis parti du kit officiel. C'est les couleurs Jeedom officielles. En fait c'est les couleurs initiales qui n'était pas dans la charte Jeedom.

@Karreg 
> Par contre j'éviterais le logo de zigate pour des raisons de droit. Il est libre de droit ?

Il y a une tolérance je pense. Surtout qu'au final, de bon plugin font de bonnes vente pour lui.

> Dans l'absolu, c'est la même chose pour le nom du plugin, d'autant plus qu'il bosse lui aussi sur un plugin jeedom...

Tes sources ? Car il link les plugins des autres sur sa page.

Pour faire le logo, je suis parti du kit officiel, j'ai collé l'image Zigate que j'ai dé-saturé pour qu'elle soit pas écrasée par le vert.

**Comment by llaumgui** [comment]
Je retrouve plus le kit Jeedom, mais j'ai utilisé le NextDom que j'ai mis en vert (NextDom utilise le bleu) https://www.nextdom.org/creation-dune-icone-plugin-au-standard-nextdom/

**Comment by Karreg** [comment]
C'est sur la page où il liste les plugins justement, à côté du plugin zigate et d'abeille.
Je ne retrouve pas cette page à cet instant. La navigation est vraiment pas top sur le site pour trouver ce qu'on cherche :)

**Comment by llaumgui** [comment]
https://jeedom.github.io/documentation/dev/fr_FR/Icone_de_plugin

**Comment by doudz** [comment]
Après je vous laisse décider, vous êtes l'avenir du plugin ;)

**Comment by Karreg** [comment]
OK, la page en question n'est pas clair sur qui fait le dev. Bon à savoir donc.

**Comment by llaumgui** [comment]
Le dépôts GH avec des ZIP à télécharger est encore moins clair...

**Comment by ioull** [comment]
Je pense qu'il faudrait changer la couleur du fond (genre bleu) car il est écrit "Nous vous remercions par avance de ne pas utiliser le même code couleur que les icones des plugin officiels Jeedom."

**Comment by llaumgui** [comment]
Zut pas vu.. Donc on va partir sur les propositions de @doudz mais il faut que couleur de fond = couleur d'écriture dans la charte. Où alors on prend le bleu NextDom.

**Comment by llaumgui** [comment]
Avec ton outil:
![zigate_icon](https://user-images.githubusercontent.com/411360/45021340-9be28580-b031-11e8-9435-73b738b6c0bd.png)

**Comment by Karreg** [comment]
Un peu gris à mon goût, mais c'est propre ! :smiley:
