### ISSUE TITLE
Mise en place d'Intégration Continue et de QA

### ISSUE THREAD

**Issue by llaumgui** [Jeedom-Zigate/jeedom-plugin-zigate#42]
Afin d'avoir un minimum de QA:

- [x] Travis
- [x] CodeClimate
  - [x] PHP
  - [x] Markdown
  - [x] Python
  - [x] JSON
- [x] Is it maintained?

**Comment by Karreg** [comment]
Le link checking ça peut être bien oui. La correction d'orthographe je reste toujours dubitatif, mais dans du multi-dev ça me semble intéressant. En espérant ne pas avoir trop de faux positifs... :smiley:

**Comment by llaumgui** [comment]
Hier soir j'ai juste mis le MDLint pour commencer petit... C'est un massacre :-)

**Comment by Karreg** [comment]
Alors le MDLint, d'expérience, est très limité, et balance des erreurs dès que la syntaxe est un peu complexe... Là en l'occurrence elle ne l'est pas, à part peut être des liens en titre par exemple.
Tu as un lien vers le résultat ?

**Comment by llaumgui** [comment]
J'ai pas encore mis le badge sur le ReadMe de develop:
https://codeclimate.com/github/Jeedom-Zigate/jeedom-plugin-zigate

Mais je vais l'installer en local et le configurer. Là c'est un premier jet.

**Comment by llaumgui** [comment]
Gros commit pour le phpcs valide côté Travis. On pourra s'assure que les PR respecte les standards.

**Comment by ioull** [comment]
Oh zut je vais plus pouvoir proposer de PR :-)

**Comment by llaumgui** [comment]
Si si, elle seront annalysées par Travis avant.
