### ISSUE TITLE
Update documentation reference to target the new github repo

### ISSUE THREAD

**Issue by Karreg** [Jeedom-Zigate/jeedom-plugin-zigate#43]
documentation is referencing the old repo. The plugin should redirect to this new repo.

**Comment by doudz** [comment]
Petit indication de JEEDOM pour la doc

> Attention pour que le market puisse envoyer la traduction et la doc générée sur votre dépot il faut absolument ajouter le compte github zoic21 à votre dépot (en pull ET push). Une fois cela fait un robot se lance tout les jours à 12h05 pour mettre à jour votre dépôt.

Mais j'ignore ce que ça veut dire ;)

**Comment by Karreg** [comment]
ça n'a pas trop de sens, dans la mesure où la doc n'est pas intégrée, mais juste redirigée depuis cette conf:

https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/blob/71bdf46a4471bf50736559e3e2c4abb8ab725729/plugin_info/info.json#L13

Donc soit on n'est pas bon, et il devrait y avoir une structure de doc par langage, ce qui n'est pas le cas. Soit on passe à côté de quelque chose...

On pourrait imaginer un robot qui fait bêtement du google translate, ça a du sens pour pousser un soft français au niveau international, mais ça ne semble pas être le cas.

**Comment by Karreg** [comment]
Après un [contrôle rapide](https://jeedom.github.io/plugin-template/fr_FR/)...

> doc : doit contenir la doc du plugin au format asciidoc, la racine et le fichier index.asciidoc. Toutes les images sont dans doc/images. La doc elle-même est dans un dossier en fonction de la langue (ex en francais : doc/fr_FR)

Donc on n'est pas bon :smiley: 
En même temps, je ne sais même pas comment est utilisée cette doc, je n'ai jamais vu que des redirections dans les plugins que j'ai utilisés...

**Comment by llaumgui** [comment]
L'idée est d'avoir une doc local: correspondant à la version installée VS doc en ligne qui correspond à la dernière version.

**Comment by Karreg** [comment]
OK, mais asciidoc étant une version compilée, ça nécessite d'avoir une double version, une en asciidoc, et une en markdown...

[Même Jeedom ne suit pas ses propres règles de développement](https://github.com/jeedom/plugin-ifttt)...

**Comment by llaumgui** [comment]
C'est pour ça qu'il y a NextDom... PSR, TU, etc...
