### ISSUE TITLE
Create asciidoc documentation

### ISSUE THREAD

**Issue by Karreg** [Jeedom-Zigate/jeedom-plugin-zigate#45]
D'après [la documentation du dev de plugin](https://jeedom.github.io/plugin-template/fr_FR/):

> doc : doit contenir la doc du plugin au format asciidoc, la racine et le fichier index.asciidoc. Toutes les images sont dans doc/images. La doc elle-même est dans un dossier en fonction de la langue (ex en francais : doc/fr_FR)

Mais vu que jeedom lui même ne pousse pas vraiment cette procédure, je ne mettrait pas ça en priorité très très haute...

**Comment by llaumgui** [comment]
Tu peux pas prendre la doc actuelle et la passer dans une moulinette ?

**Comment by Karreg** [comment]
C'est effectivement une solution, faudrait faire des essais avec pandoc pour voir si ça marche... Mais j'ai souvent vu des problèmes dans le résultat final, on risque de péter la documentation sans s'en rendre compte. 
Mais à tester, et automatiser avec Travis...

**Comment by llaumgui** [comment]
Alors bonne nouvelle !
La doc que tu indique n'est pas à jour je pense. **Asciidoc n'est plus la norme** :
https://www.jeedom.com/blog/3909-mise-a-jour-de-la-documentation/

Un exemple: 
* Documentation officielle : https://jeedom.github.io/documentation/
* De là tu va là : https://zyg0m4t1k.github.io/jeebase/fr_FR/
* Et au final c'est du MarkDown: https://github.com/Zyg0m4t1k/jeebase/tree/master/docs/fr_FR

Donc de ce que je comprends (arrête mois si j'ai faut @Karreg) mais :
* Les sources de la doc sont bonnes.
* On a juste à remodeler les répertoires et configurer le templates.

Du coup je modifie le titre.

**Comment by llaumgui** [comment]
Je ferme du coup et je lance la #48
