### ISSUE TITLE
Date de dernier message pas à jour ?

### ISSUE THREAD

**Issue by llaumgui** [Jeedom-Zigate/jeedom-plugin-zigate#46]
Bonjour,

on y verra plus clair avec la page santé (#33), mais des fois j'ai l'impression que la date de dernière communication n'est pas à jour par rapport à la dernière valeur dans l'historique des commandes.
Je veux bien un peu de feedback.

**Comment by ioull** [comment]
quand on redemarre le daemon, la date de mise à jour se met à jour vu depuis la page santé correspond à la date de redemarrage du plugin ...

**Comment by ioull** [comment]
Je viens de remettre le patch ... Je vous dirais ... j'ai peur que ca perturbe l'inclusion de nouveau peripherique ...

**Comment by doudz** [comment]
Est-ce toujours d'actualité ? sinon je clôture le ticket

**Comment by doudz** [comment]
C'est peut-être lié à https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/issues/53
