### ISSUE TITLE
Mettre la doc dans les standards Jeedom

### ISSUE THREAD

**Issue by llaumgui** [Jeedom-Zigate/jeedom-plugin-zigate#48]
Cf #45 et les standards Jeedom abordés ici:
https://www.jeedom.com/blog/3909-mise-a-jour-de-la-documentation/

Il faut:
- [x] Modifier l'arborescence.
- [x] Mettre un index.md.
- [x] Configurer le template.
- [x] Configurer le Market Jeedom.
- [x] Mettre le Changelog dedans.

**Comment by llaumgui** [comment]
J'ai fait quelques tests hier soir ça rend bien.

**Comment by llaumgui** [comment]
@doudz > Tu peux cocher la case qui génère la doc automatiquement stp ? J'ai fini de la migrer dans le design Jeedom. Une fois que tu aura fait ça je pousse le tout en beta.

**Comment by llaumgui** [comment]
J'ai pas encore mis le badge sur le ReadMe de develop:
https://codeclimate.com/github/Jeedom-Zigate/jeedom-plugin-zigate

**Comment by llaumgui** [comment]
Mais je vais l'installer en local et le configurer. Là c'est un premier jet.

**Comment by doudz** [comment]
J'ai activé l'option

**Comment by llaumgui** [comment]
Merci. Bêta ce soir, donc dispo à 2H du mat'.
