### ISSUE TITLE
Ajout du support du "Xiaomi Aqara vibration sensor"

### ISSUE THREAD

**Issue by llaumgui** [Jeedom-Zigate/jeedom-plugin-zigate#49]
Une fois le support dans le daemon Python: https://github.com/doudz/zigate/issues/26, l'intégrer dans le plugin.

**Comment by doudz** [comment]
J'ai regardé rapidement, l'intégration ressemblera beaucoup à celle du cube XIAOMI

**Comment by llaumgui** [comment]
Et comme le cube est un gros bor**l...
D’ailleurs, pour le rotate, tu as vu ma remarque ?
https://www.jeedom.com/forum/viewtopic.php?f=133&t=34490&start=580#p641742

**Comment by doudz** [comment]
Oui, j'avais fait la même constatation pour la rotation à gauche ou à droite.
Perso chez moi le cube fonctionne assez bien, sauf cette histoire de rotation qui n'est pas géré
