### ISSUE TITLE
Liste les équipements supportés

### ISSUE THREAD

**Issue by llaumgui** [Jeedom-Zigate/jeedom-plugin-zigate#50]
Une fois la doc passée dans MDL et migrée au format Jeedom (#48), mettre à jour les pages de supports équipements.

**Comment by doudz** [comment]
A titre d'info, voici la liste des équipements connus installés par les utilisateurs de Jeedom :
(ya des doublons, j'ai pas pris le temps d'affiner les infos)

122-130-1/2-2
Flex RGBW
LCT001
LCT012
LCT015
LIGHTIFY Indoor Flex RGBW
LLC010
LST002
LTW010
LWB004
LWB006
LWB010
Plug 01
RB 185 C
RWL021
RWL021
SMOKE_CTPG
TH-T_V15
TRADFRI bulb E14 WS opal 400lm
TRADFRI bulb E27 CWS opal 600lm
TRADFRI bulb E27 W opal 1000lm
TRADFRI bulb E27 WS opal 980lm
TRADFRI bulb E27 opal 1000lm
TRADFRI bulb GU10 W 400lm
TRADFRI bulb GU10 WS 400lm
TRADFRI remote control
TRADFRI wireless dimmer
lumi.ctrl_ln1.aq1
lumi.plug
lumi.sens
lumi.sensor_86sw1
lumi.sensor_86sw1
lumi.sensor_86sw2
lumi.sensor_cube
lumi.sensor_cube
lumi.sensor_cube.aqgl01
lumi.sensor_cube.aqgl01
lumi.sensor_ht
lumi.sensor_ht
lumi.sensor_magnet
lumi.sensor_magnet
lumi.sensor_magnet.aq2
lumi.sensor_magnet.aq2
lumi.sensor_motion
lumi.sensor_motion
lumi.sensor_motion.aq2
lumi.sensor_motion.aq2
lumi.sensor_motion.aq2
lumi.sensor_motion.aq2
lumi.sensor_smoke
lumi.sensor_swit
lumi.sensor_switch
lumi.sensor_switch
lumi.sensor_switch.aq2
lumi.sensor_switch.aq2
lumi.sensor_wleak.aq1
lumi.sensor_wleak.aq1
lumi.weather
lumi.weather

**Comment by llaumgui** [comment]
MErci.

**Comment by llaumgui** [comment]
La doc est migrée, je retire le tag standby. Si certain se sente d'aider ?

**Comment by Karreg** [comment]
N'est-ce pas redondant avec la liste de compatibilité de Zigate ? Il me semble que si ZiGate fonctionne avec, alors le plugin aussi non ? Il faudrait dans ce cas plutôt faire un lien vers la doc ZiGate ?

**Comment by llaumgui** [comment]
J'ai pas l'impression qu'elle soit à jour... Rien que pour Ikéa celle de @doudz est plus longue... Et puis on peu mettre des commentaire propre à Jeedom.

**Comment by ioull** [comment]
Un truc comme ca ? 
https://github.com/ioull/jeedom-plugin-zigate/blob/develop/docs/fr_FR/xiaomi.md

**Comment by llaumgui** [comment]
Pas mal... Mais perso:
* Je regrouperais les doublons (2I ds pour 1 même produits (cf mon exemple).
* On a un MarkdownLint en place et je vais mettre travis ASAP, donc : https://gist.github.com/uupaa/f77d2bcf4dc7a294d109
* Manque les nom.

Après, on liste un peu de manière anarchique... Faudrait regrouper ou au moins lcasser ?

**Comment by ioull** [comment]
Oui oui mais c'était pour être sûr de le faire au bon endroit ! 
Pour Travis, je vais regarder du coup, je ne connais pas mais si c'est pour le resize d'image, je vais attendre effectivement

**Comment by ioull** [comment]
J'ai mis HTML car le resize avec =80x ne marchait pas sous GitHub ... Je testerai d'autres trucs pas HTML alors ;-) désolé je suis very noob en MD !

**Comment by llaumgui** [comment]
Je viens de mettre Travis sur develop. Par contre pas de MD pour les thumbnail. Du coup j'autoriserais l'HTML...

**Comment by ioull** [comment]
Ouf ;-)

**Comment by ioull** [comment]
J'ai avancé un petit peu, j'ai mis tout dans une seule page pour l'instant et je répartierai ensuite 
https://github.com/ioull/jeedom-plugin-zigate/blob/develop/docs/fr_FR/compat.md

N'hesitez pas a faire des remarques ! Je suis simplement parti de la liste de @doudz, viré les doublons et essayé de ranger ...

**Comment by Deepcore93** [comment]
Bonjour,

Je suis en train de faire un test sur un "lumi.sensor_wleak.aq1", il me semble pas totalement compatible, il manque l'état "Eau" pour l'inondation.

**Comment by ioull** [comment]
J'ai fait un pull request mais je me suis fait jeté par Travis et je ne comprends pas trop pourquoi ...

**Comment by Karreg** [comment]
Hello,

Concernant les images, l'idée est de redimensionner en amont., ça évite en plus de stocker de trop grosses images...
Certaines implémentations de MD permettent le resize dynamique, mais comme ce n'est pas standard il vaut mieux éviter...

**Comment by llaumgui** [comment]
Oui mais on récupère les images de Jeedom... Faudrait utiliser la taille standard de Jeedom. Du coup c'est pas un soucis de doc mais d'image dans Jeedom. Non ?

**Comment by Karreg** [comment]
On parle bien de cette doc ? https://github.com/ioull/jeedom-plugin-zigate/blob/addCompatibilite/docs/fr_FR/ikea.md

Comment les images viennent de Jeedom? C'est nous qui écrivons la doc non ? J'ai raté quelque chose ?
