### ISSUE TITLE
Equipements considérés comme secteur alors que non

### ISSUE THREAD

**Issue by ioull** [Jeedom-Zigate/jeedom-plugin-zigate#51]
Dans ma config, j'ai deux équipements qui sont considérés comme sur secteur alors que non 
    - xiaomi lumi.sensor_switch première génération
    - Telecommande Philips RWL021

Rien de grave, c'est juste pour le signaler ;-)

**Comment by ioull** [comment]
J'ai pas été très prècsi puisqu'il s'agissait de la page santé :-(
Ca marche en modifiant le fichier 
/var/www/html/plugins/zigate/desktop/modal/health.php

J'ai juste rajouté un test sur power_type 
        } elseif ($eqLogic->getConfiguration('power_type') == 1) {
                $battery_status = '<span class="label label-primary" style="font-size : 1em;" title="{{Secteur}}"><i class="fa fa-plug"></i></span>';
        } else {
                $battery_status = '<span class="label label-success" style="font-size : 1em;"></span>';
        }

**Comment by llaumgui** [comment]
@ioull > Tu veux proposer un PR ?

**Comment by ioull** [comment]
Hum .. je suis pas très doué pour ca ... Je vais essayer ;-)

**Comment by llaumgui** [comment]
Histoire que le fix soit en ton nom :-).

**Comment by ioull** [comment]
D'ailleurs je sais pas si c'est possible mais ce bug devrait être rattaché à celui de la page santé ;-)

**Comment by llaumgui** [comment]
Je viens d'éditer ton poste, en en parlant, ça fait un lien. Je te l'affecte et si tu t'en sort pas alors je le ferais.

**Comment by ioull** [comment]
Tu preferais peut-être un PR sur la branche develop ???

**Comment by llaumgui** [comment]
PAs grave je PR à la main de toute façon ;-).

**Comment by llaumgui** [comment]
Je ferais le merge deamin, là j'ai pas mal taffé sur la syntaxe PHP et il y a encore pas mal de travail.

**Comment by llaumgui** [comment]
Je viens de passer le PR en develop (en fait j'ai fait un cherry-pick car trop de diff après les corrections de checkstyle...
Il y avait encore un bug lorsque 60% que j'ai fixé avec 1dd1d2d.

Si pas de cris, demain en bêta ?
