### ISSUE TITLE
Le demarrage du plugin lance les scenarios sur changement de valeur

### ISSUE THREAD

**Issue by ioull** [Jeedom-Zigate/jeedom-plugin-zigate#53]
Au (re)demarrage du plugin, les scenarios avec trigger(#[Chambre des parents][Xiaobutton][onoff]#) sont déclenchés alors que sur les plugins comme rfxcom ca ne le fait pas ... 
Pas sur que ce soit un bug, ou une mauvaise utilisation de ma part ...

**Comment by llaumgui** [comment]
Pour moi c'est pas forcement un bug... Je pense que l'on peu clore.

**Comment by ioull** [comment]
Ok ... Ce n'est pas le cas des plugins zwave ou rfxcom qui ne déclenchent
pas le scénario associé mais whynot

**Comment by doudz** [comment]
Au démarrage le plugin charge les dernières valeurs connues comme si elles venaient de changer, c'est peut-être pour ça qu'il y a un déclenchement.
Si c'est bien ça le problème, une idée serait de vérifier si la valeur à changer pour ne pas forcer la valeur au démarrage

**Comment by llaumgui** [comment]
Côté Plugin ?
Car pour moi il y a une fonction côté Jeedom pour ça :
![image](https://user-images.githubusercontent.com/411360/48137623-c5729400-e2a2-11e8-86ba-84e800e05d6d.png)
Et tu mets "Jamais répéter".

**Comment by doudz** [comment]
Est-ce toujours d'actualité ? sinon je clôture le ticket

**Comment by lukebr91** [comment]
Oui, toujours d'actualité, effectivement la solution de règler "ne jamais
répéter" fonctionne (merci pour la solution) mais l'idéal serait que les
équipements soit paramétrés comme cela à leur création dans ce cas.

**Comment by doudz** [comment]
Ok, je viens de pousser une correction, à tester
https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/blob/develop/core/class/zigate.class.php#L438-L440

**Comment by doudz** [comment]
Super, merci pour le retour.

Issue à cloturer à la publication de la mise à jour

**Comment by llaumgui** [comment]
Comme j'espère une mise en bête proche, j’essaie de recenser ce qui part.
