### ISSUE TITLE
Dépendance pip3

### ISSUE THREAD

**Issue by llaumgui** [Jeedom-Zigate/jeedom-plugin-zigate#62]
Dans la documentation troubleshoot, rajouter la dépendance à pip3 ou alors la rajouter en dépendance.

**Comment by doudz** [comment]
pip3 est supposé s'intaller tout seul, c'est dans le script d'installation

**Comment by llaumgui** [comment]
Exact: https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/blob/master/resources/install_apt.sh#L15
Mais : https://www.jeedom.com/forum/viewtopic.php?f=133&t=34490&p=646172#p646158

Du coup à voir si le problème est que sur cette personne.

**Comment by doudz** [comment]
c'était un problème ponctuel chez cette personne, son système de package apt était cassé visiblement
