### ISSUE TITLE
Installation des dépendances ne fonctionne pas

### ISSUE THREAD

**Issue by JLSGVA** [Jeedom-Zigate/jeedom-plugin-zigate#65]
Installation des dépendances impossible avec Jeedom 3.3.3 et dernière version Zigate 
Log :
```
Installation des dépendances
Hit:1 http://raspbian.raspberrypi.org/raspbian stretch InRelease
Hit:2 http://archive.raspberrypi.org/debian stretch InRelease
Hit:3 https://deb.nodesource.com/node_8.x stretch InRelease
Reading package lists...

Reading package lists...
Building dependency tree...

Reading state information...
python3 is already the newest version (3.5.3-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...

Reading state information...
Package 'python3-serial' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
python3-pip is already the newest version (9.0.1-2+rpt2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...

Reading state information...
python3-requests is already the newest version (2.12.4-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...

Reading state information...
python3-setuptools is already the newest version (33.1.1-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
sudo: pip3: command not found
sudo: pip3: command not found
Installation des dépendances terminé !
```

**Comment by Karreg** [comment]
Ces logs ne montrent aucune erreur, quel est le souci ?

**Comment by llaumgui** [comment]
Je dirais :
`sudo: pip3: command not found`

**Comment by llaumgui** [comment]
Je me demande si pip3 ne viens que si tu as 2 version de pip.

**Comment by llaumgui** [comment]
@JLSGVA > tu peux nous faire un :
```
whereis pip
whereis pip3
dpkg --list | grep pip
```

**Comment by JLSGVA** [comment]
pi@raspberrypi:~ $ whereis pip
pip: /etc/pip.conf /usr/local/bin/pip /usr/local/bin/pip2.7
pi@raspberrypi:~ $ whereis pip3
pip3: /usr/share/man/man1/pip3.1.gz
pi@raspberrypi:~ $ dpkg --list | grep pip
ii  epiphany-browser                      1:3.8.2.0-0rpi28                  armhf        Intuitive GNOME web browser
ii  epiphany-browser-data                 1:3.8.2.0-0rpi28                  all          Data files for the GNOME web browser
ii  libpipeline1:armhf                    1.4.1-2                           armhf        pipeline manipulation library
ii  pipanel                               20180706~092558                   armhf        Settings panel for Raspberry Pi desktop appearance
ii  python-pip-whl                        9.0.1-2+rpt2                      all          Python package installer
ii  python3-pip                           9.0.1-2+rpt2                      all          Python package installer
pi@raspberrypi:~ $

**Comment by doudz** [comment]
Ce qui pourrait être fait c'est modifier le script d'installation des dépendances de façon à ne pas appeler pip3 (car l'alias semble ne pas fonctionner sur tous les systèmes) mais appelé python3 à la place
au lieu de 
`sudo pip3 install zigate`
on pourrait avoir
`sudo python3 -m pip install zigate`

**Comment by llaumgui** [comment]
A quoi tu vois ça @doudz , il est bien ii.
Moi je pensais à sudo qui va pas chercher comme il faut et il faudrait taper le lien direct.

**Comment by doudz** [comment]
Je pense à ça car whereis ne trouve que la doc, si c'était juste un problème de chemin avec sudo la commande whereis devrait le trouver quand même

**Comment by JLSGVA** [comment]
effectivement la desinstallation complète de python3 et reinstallation a résolu le problème !
Merci infiniment c'est top

**Comment by llaumgui** [comment]
Encore un... On va suivre le préconisation de @doudz:
`sudo python3 -m pip install zigate`
