### ISSUE TITLE
Update des dépendances lors de l'update du plugin

### ISSUE THREAD

**Issue by llaumgui** [Jeedom-Zigate/jeedom-plugin-zigate#66]
Vu les interconnexions avec la librairie Python, il serait bon de faire un update des dépendances lors de l'udate du plugin.

**Comment by doudz** [comment]
Actuellement l'installation du plugin provoque un reset du cache des dépendances dans le but de forcer Jeedom à vérifier la validité des dépendances, justement pour que les dépendances (notamment la lib python) soient mise à jour suite à la mise à jour du plugin.
"En principe ça marche"

**Comment by llaumgui** [comment]
Yes, mais c'est délégué à un cron... L'idée était de le faire dans la foulée.
