### ISSUE TITLE
Amélioration des logs du plugin

### ISSUE THREAD

**Issue by Karreg** [Jeedom-Zigate/jeedom-plugin-zigate#67]
Le plugin a des logs techniques, mais pas de log fonctionnel. Et peu de choses sont loggées.

Il en résulte qu'en cas de problème, on ne sait pas ce qui se passe.

Il faut générer plus de logs de niveau info, et en faire des logs lisibles et compréhensible (une ligne technique, une ligne fonctionnelle, ça ne me choque pas).

Par exemple, j'ai tenté d'ajouter une ampoule ce matin, et je me suis retrouvé avec 3 nouveaux appareils, aucun ne fonctionnant. Les logs ne contenaient aucune ligne.

![capture1](https://user-images.githubusercontent.com/9166144/45479628-4ac84500-b747-11e8-97ba-b73b57460926.PNG)

Je ne sais pas si c'est corrigeable, si la zigate ne renvoie aucune info, il sera compliqué de les remonter au plugin, mais ça vaut le coup de creuser ?

**Comment by llaumgui** [comment]
J'aurais tendance à fermer et traiter au cas par cas en fonction des manques de reporting remontés. Tu en penses quoi @Karreg ? A moins que tu sois en mesure de fixer ?

**Comment by Karreg** [comment]
Désolé du silence radio, c'est compliqué pour moi d'intervenir en ce moment :)
Je suis partisan que des bons logs facilitent l'analyse... Je veux bien faire une passe, un jour, mais le fermer pour l'instant ça me va, je ne suis pas prêt de pouvoir résoudre le problème...

En plus mon usage de la Zigate est pour l'instant nul, je suis passé sur la gateway Ikea suite aux nombreux problèmes entre zigate et les éléments Ikea. Mais j'aurai d'autres éléments ZigBee un jour, comme du Xiaomi, donc je reste éloigné, mais pas parti :)
