### ISSUE TITLE
Utiliser l'adresse IEEE comme LogicalId

### ISSUE THREAD

**Issue by doudz** [Jeedom-Zigate/jeedom-plugin-zigate#71]
Peut-être qu'il faudrait modifier le LogicalId des objects pour l'utiliser l'adresse IEEE à la place de la short address

https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/blob/master/core/class/zigate.class.php#L84

L'IEEE est unique à chaque équipement, la short address change à chaque nouvelle association d'un objet.
L'intérêt serait de ne pas avoir à reconfigurer les objets Jeedom lorsqu'on ré-associe un objet, après un changement de pile par exemple ou après qu'un équipement est quitté le réseau et qu'on veut le remettre

A vérifier :
Est-ce que l'adresse IEEE est toujours disponible ? (en principe oui)

**Comment by doudz** [comment]
Ce point va devenir très important car avec la mise à jour du firmware 3.0e qui arrive, les utilisateurs vont devoir ré-associer leurs équipements et donc sans la modification proposée il va falloir tout refaire (scénario, affichage, etc)

**Comment by llaumgui** [comment]
J'ai un peu de mal à comprendre, tu veux dire juste remplacer $device['info']['addr'] par $device['info']['iee'] ?

**Comment by doudz** [comment]
Actuellement dans Jeedom la référence d'un équipement est la short address , le problème est que cette adresse change à chaque fois qu'on ré-associe un équipement. 
Donc si on ré-associe un équipement, comme il va changer de short address, tout ce qui a été configuré dans Jeedom sera à refaire car le plugin va générer un nouvel objet.

L'idée est donc d'utiliser l'adresse IEEE comme référence ainsi même si la short adress change, l'objet Jeedom restera le même et ainsi il n'y a rien à refaire lorsqu'on ré-associe un appareil.

Il y a potentiellement un problème pour certains équipements qui n'aurait pas d'adresse IEEE (constaté en parcourant les forums) mais je ne sais pas si c'est un défaut de l'équipement, un bug de zigate ou juste un problème de transmission ponctuel (perso je penche pour ce dernier point car je n'ai JAMAIS eu le problème)

**Comment by doudz** [comment]
Naturellement il faudra prévoir une migration de l'ancienne config vers la nouvelle

**Comment by llaumgui** [comment]
J'ai vu que tu avais fait une branch ? tu prend en charge la modification du coup ?

**Comment by Deepcore93** [comment]
@doudz : pour les équipements dans IEEE, j'ai le problème, il me semble que c'est des noeuds fantome qui ont été supprimés mais qui reste dans la mémoire de la zigate (ca rejoint l'issue 30)

**Comment by llaumgui** [comment]
Du coup @doudz, ta branche est candidate au merge ou pas ?

**Comment by doudz** [comment]
Oula non pas du tout, ya plein de modif à faire, j'ai rien fait encore

**Comment by llaumgui** [comment]
Ok, du coup je peux peut être le post-pone en 1.1.3 ? Histoire de pousser la 1.1.2 AZAP ?

**Comment by llaumgui** [comment]
Dis, les ampoules Ikéa qui perdent la synchronisation si on utilise l'interrupteur, ça pourrait pas être ça ? Changement d'addr mais même ieee ?

**Comment by doudz** [comment]
Je ne sais pas quel problème particulier il y a avec les ampoules IKEA mais oui la modif que je propose permettrait de continuer à utiliser un équipement qui aurait changer de short addr de façon transparente pour l'utilisateur

**Comment by doudz** [comment]
Finalement j'ai choisi une autre option dans la lib python
la version 0.21 apporte un nouveau signal ZIGATE_DEVICE_RENAMED qui indique qu'un équipement a changé de short address
ce signal envoie les paramètres old_addr et new_addr
On devrait donc pouvoir simplement changer le logicalId d'un objet Jeedom avec ce signal

**Comment by llaumgui** [comment]
Mais du coup on n'utilise plus le logicalId ? Il y a rien à faire côté plugin ?

**Comment by doudz** [comment]
Si si, côté plugin il faudra gérer le changement d'addr, j'essaierai de proposer qqc la semaine prochaine

**Comment by doudz** [comment]
J'ai mis à jour la branche IEEE, à tester 
Attention pour les équipements mal associés qui n'ont pas de IEEE ça va mal se passer...
Normalement après ça, on peut ré-associer autant qu'on le souhaite un équipement, la short addr changera mais tout restera fonctionnel

**Comment by doudz** [comment]
@llaumgui J'ai apporté des modif à la branche develop
Je pense que la migration devrait fonctionner maintenant.
Désolé pour le délai...

**Comment by llaumgui** [comment]
Nickel !!! Je teste d'ici ce WE.

**Comment by llaumgui** [comment]
Yes, faudrait, je me le note.

**Comment by doudz** [comment]
J'ai testé de mon côté dans ma VM, ça marche bien
