### ISSUE TITLE
current_level à 100 (Hue)

### ISSUE THREAD

**Issue by loic74** [Jeedom-Zigate/jeedom-plugin-zigate#72]
Bonjour à tous,

L'info current_level remonte toujours 100 pour toutes les ampoules Hue (LWB010 et LWB006), quelque soit le niveau actuel, et même si l'ampoule est éteinte. Je n'ai rien dans les logs...

Savez-vous d'où peut venir le problème ?

**Comment by Cactusbone** [comment]
j'avais ça au début, et un resync manuel m'a envoyé la bonne info

**Comment by llaumgui** [comment]
Du coup je ferme.
