### ISSUE TITLE
Griser les équipements désactivés dans la page health

### ISSUE THREAD

**Issue by llaumgui** [Jeedom-Zigate/jeedom-plugin-zigate#76]
Ne pas afficher les équipements désactivés sur la page health.

**Comment by llaumgui** [comment]
@Deepcore93 ou @ioull un volontaire ?

**Comment by Deepcore93** [comment]
Hello,

Je peux prendre le point.

Pour ces équipements, je pense qu'il serait préférable de les griser, avec aucune information

**Comment by llaumgui** [comment]
Faut voir comment fait RFX ou Zwave.

**Comment by Deepcore93** [comment]
C'est pour ca que je le propose :) : sur Zwave ou BLEA c'est grisé, je n'utilise pas RFX

**Comment by Deepcore93** [comment]
Je t'ai envoyé la mise à jour, test et dis moi si ca te va.

**Comment by llaumgui** [comment]
Ok, merci.

**Comment by llaumgui** [comment]
Merci @Deepcore93, c'est validé !
