### ISSUE TITLE
bouton xiaomi aqara v2 mal reconnu lumi.remote.b1acn01

### ISSUE THREAD

**Issue by pixeldesbois** [Jeedom-Zigate/jeedom-plugin-zigate#84]
Bonjour,
J'ai appairré un bouton aqara v2 mais ce dernier est mal reconnu.
En effet, il est noté " lumi.remote.b1acn01" au lieu de "lumi.sensor_switch.aq2"
Est-il possible de l'inclure dans une future mise à jour s'il vous plaît ?

**Comment by llaumgui** [comment]
Bonjour,

pour moi c'est bien un  lumi.remote.b1acn01, c'est une nouvelle référence.

**Comment by llaumgui** [comment]
C'est le carré ? Pas le rond ?
https://jeedom-zigate.github.io/jeedom-plugin-zigate/fr_FR/xiaomi

**Comment by pixeldesbois** [comment]
C'est le carré (lumi.sensor_switch.aq2)

**Comment by llaumgui** [comment]
J'ai poussé quelque chose en beta. Ca rajoute l'image.
Par contre tu as d'autre soucis ?

**Comment by pixeldesbois** [comment]
Super ! je te remercie pour ta réactivité !
Je pense que cela ne suffira. Il faudrait que le bouton remonte comme le lumi.sensor_switch.aq2
Je pense par exemple que la liste des commandes associé actuellement au lumi.remote.b1acn01 est incorrecte (pas de commande sur l'appui ou l'état ou bien encore le multi)

**Comment by rroblik** [comment]
+1 J'ai le même souci, vu comme `lumi.remote.b1acn01` ; comme si c'était un capteur de mouvement :x 

(https://www.jeedom.com/forum/viewtopic.php?f=133&t=34490&p=669864#p669864)

Merci pour le boulot, j'espère que ce petit bug va être résolu :)

**Comment by doudz** [comment]
Etrange la création de l'attribut movement.
Mais il faudrait essayer d'utiliser le bouton pour avoir si cela crée les commandes manquantes

**Comment by doudz** [comment]
@rroblik  ??? ??? 
Si je comprends bien :
On a une commande movement et pas de commande multiclick ou onoff ?
Quand on appuie sur le bouton, il y a des info type "flip_90" qui apparaisse dans movement ??

On est d'accord on parle bien de ce modèle là :
![image](https://user-images.githubusercontent.com/1262548/49076867-44237700-f23a-11e8-8287-2ac7cc40fd58.png)

**Comment by doudz** [comment]
> @doudz > C'est pas la lib Python qui bug ?
@llaumgui oui tout à fait

**Comment by doudz** [comment]
Est-ce qu'il serait possible d'avoir le fichier zigate.json ?

**Comment by rroblik** [comment]
Oui on parle bien de ce bouton. 

Je vais essayer de récupérer le fichier la je suis au boulot ;)

**Comment by rroblik** [comment]
@doudz Tu parles du fichier `/var/www/jeedom/plugins/zigate/resources/zigated/.zigate.json` ?

**Comment by rroblik** [comment]
Ok le voici (j'ai juste un capteur de température en +)

```json
{
    "devices": [
        {
            "addr": "6f75",
            "endpoints": [
                {
                    "clusters": [
                        {
                            "attributes": [
                                {
                                    "attribute": 65281,
                                    "data": "0121770b0421a843052108000624010004000064299a036521c122662b878501000a210000",
                                    "name": "battery",
                                    "unit": "V",
                                    "value": 2.935
                                }
                            ],
                            "cluster": 0
                        },
                        {
                            "attributes": [
                                {
                                    "attribute": 0,
                                    "data": 924,
                                    "name": "temperature",
                                    "unit": "\u00b0C",
                                    "value": 9.24
                                }
                            ],
                            "cluster": 1026
                        },
                        {
                            "attributes": [
                                {
                                    "attribute": 0,
                                    "data": 997,
                                    "name": "pressure",
                                    "unit": "mb",
                                    "value": 997
                                },
                                {
                                    "attribute": 16,
                                    "data": 9972,
                                    "name": "pressure2",
                                    "unit": "mb",
                                    "value": 997.2
                                },
                                {
                                    "attribute": 20,
                                    "data": -1
                                }
                            ],
                            "cluster": 1027
                        },
                        {
                            "attributes": [
                                {
                                    "attribute": 0,
                                    "data": 8747,
                                    "name": "humidity",
                                    "unit": "%",
                                    "value": 87.47
                                }
                            ],
                            "cluster": 1029
                        }
                    ],
                    "device": 0,
                    "endpoint": 1,
                    "in_clusters": [],
                    "out_clusters": [],
                    "profile": 0
                }
            ],
            "info": {
                "addr": "6f75",
                "id": 0,
                "ieee": "00158d000273ca98",
                "last_seen": "2018-11-27 13:37:31",
                "mac_capability": "10000000",
                "power_type": 0,
                "rssi": 57
            }
        },
        {
            "addr": "d62a",
            "endpoints": [
                {
                    "clusters": [
                        {
                            "attributes": [
                                {
                                    "attribute": 1,
                                    "data": 2,
                                    "name": "application_version",
                                    "value": 2
                                },
                                {
                                    "attribute": 5,
                                    "data": "lumi.remote.b1acn01",
                                    "name": "type",
                                    "value": "lumi.remote.b1acn01"
                                },
                                {
                                    "attribute": 65281,
                                    "data": "01215d0c0328190421a81305214400062401000000000a210000",
                                    "name": "battery",
                                    "unit": "V",
                                    "value": 3.165
                                }
                            ],
                            "cluster": 0
                        },
                        {
                            "attributes": [
                                {
                                    "attribute": 85,
                                    "data": "",
                                    "expire": 2,
                                    "expire_value": "",
                                    "name": "movement",
                                    "value": ""
                                }
                            ],
                            "cluster": 18
                        }
                    ],
                    "device": 259,
                    "endpoint": 1,
                    "in_clusters": [
                        0,
                        18,
                        3
                    ],
                    "out_clusters": [
                        0
                    ],
                    "profile": 260
                }
            ],
            "info": {
                "addr": "d62a",
                "bit_field": "0100000000000010",
                "descriptor_capability": "00000000",
                "id": 1,
                "ieee": "00158d00021336ff",
                "last_seen": "2018-11-27 19:08:53",
                "mac_capability": "10000000",
                "manufacturer": "1037",
                "max_buffer": 127,
                "max_rx": 100,
                "max_tx": 100,
                "power_type": 0,
                "rssi": 204,
                "server_mask": 0
            }
        }
    ],
    "groups": {}
}
```

**Comment by doudz** [comment]
Merci beaucoup, effectivement il y a un problème.
Tu me confirmes que tu utilises bien le firmware 3.0d ? (ou 3.0e)

**Comment by rroblik** [comment]
3.0d pour le moment :)

**Comment by rroblik** [comment]
@doudz Non, je n'ai aucun retour si je dépasse 2 appuies (ni dans le log zigate d'ailleurs) :(

**Comment by doudz** [comment]
ok, vraiment étrange, ce bouton ne se comporte pas du tout de la même manière.
Dans tous les cas je pense que c'est résolu pour moi
@llaumgui ça sera inclus dans la prochaine version 0.23 de la lib

**Comment by rroblik** [comment]
J'ai vu ton "fork" mais je ne suis pas sur de bien comprendre... il faut que ton fix soit porté ici et intégré dans la prochaine release c'est sa ?

Merci

**Comment by llaumgui** [comment]
Faut que je merge et pousse en bêta pour ça...

**Comment by pixeldesbois** [comment]
Hello,

Désolé pour le retard. Au cas où voici les infos de mon côté :+1: 
version du firmware 3.0d
le zigate.json :
{
    "devices": [
        {
            "addr": "0f47",
            "endpoints": [
                {
                    "clusters": [
                        {
                            "attributes": [
                                {
                                    "attribute": 1,
                                    "data": 2,
                                    "name": "application_version",
                                    "value": 2
                                },
                                {
                                    "attribute": 5,
                                    "data": "lumi.remote.b1acn01",
                                    "name": "type",
                                    "value": "lumi.remote.b1acn01"
                                },
                                {
                                    "attribute": 65281,
                                    "data": "0121030c0328200421a80105215400062401000000000a210000",
                                    "name": "battery",
                                    "unit": "V",
                                    "value": 3.075
                                }
                            ],
                            "cluster": 0
                        },
                        {
                            "attributes": [
                                {
                                    "attribute": 85,
                                    "data": "",
                                    "expire": 2,
                                    "expire_value": "",
                                    "name": "movement",
                                    "value": ""
                                }
                            ],
                            "cluster": 18
                        }
                    ],
                    "device": 259,
                    "endpoint": 1,
                    "in_clusters": [
                        0,
                        18,
                        3
                    ],
                    "out_clusters": [
                        0
                    ],
                    "profile": 260
                }
            ],
            "info": {
                "addr": "0f47",
                "bit_field": "0100000000000010",
                "descriptor_capability": "00000000",
                "ieee": "00158d0001e79060",
                "last_seen": "2018-11-28 20:02:45",
                "mac_capability": "10000000",
                "manufacturer": "1037",
                "max_buffer": 127,
                "max_rx": 100,
                "max_tx": 100,
                "rssi": 168,
                "server_mask": 0
            }
        }
    ],
    "groups": {}
}

**Comment by llaumgui** [comment]
La branche develop est mise à jour pour supporter l'IEEE et la 0.22.0... Standby le temps que la 0.23.0 arrive.

**Comment by rroblik** [comment]
:( fais signe si tu as besoin de testeur !

**Comment by pixeldesbois** [comment]
+1

**Comment by rroblik** [comment]
Hello. Vu la release récente liée uniquement à la maj de la lib, peut-on espérer une sortie de stand-by rapide ?

Merci

**Comment by pixeldesbois** [comment]
salut
J'ai reçu d'autres équipement xiaomi dont les références ne sont pas connus...
Est-ce que je les liste ici ou bien je crée une issue pour chacun ?

Question purement naïve : est-il possible mettre en place un systeme de gestion de modeles d'équipement que l'on pourraient importer, exporter, modifier (ex format xml ou autre)?
Par exemple on sait que le bouton lumi.remote.b1acn01 correspond au bouton lumi.sensor_switch.aq2, avec ce type de systeme on pourrait dupliquer la definition du lumi.sensor_switch.aq2 pour l'importer en lumi.remote.b1acn01 avec eventuellement des modifications comme le changement de type, l'image, la liste des commandes associées...
Cela permet en plus : 
- de dissocier les versions du plugin par rapport à la liste des équipements.
- de permettre à chacun de tester de nouveaux equipements et de proposer la definition via le forum.
Je ne sais pas si je délire complet ou bien si c'est une idée intéressante...

A plus

**Comment by pixeldesbois** [comment]
J'ai oublié de donner les nouvelles ref : 
lumi.ctrl_neutral1    correspond à un interrupteur mural filaire simple sans neutre comme lumi.ctrl_ln1.aq1
lumi.sensor_86sw2 correspond à un interrupteur mural sans fil double à pile comme lumi.sensor_86sw2

**Comment by rroblik** [comment]
Hello

Dès news sur la release pour avoir la compatibilité sur ces boutons ? Merci

**Comment by yann44** [comment]
Bonjour à Tous,

J'ai cette liste de commandes pour ce switch, comment faire un scenario pour allumer ou éteindre des ampoule?

C'est plutôt bien compliqué, mais je peux aider si nécessaire.
![capture d ecran 2019-01-30 a 07 54 50](https://user-images.githubusercontent.com/26790806/51963582-62893700-2464-11e9-9a93-54716260767f.png)

**Comment by doudz** [comment]
@yann44 Et bien d'après la capture d'écran il n'y a pas de commande, c'est tout le problème
Peux-tu me confirmer le type ? (lumi.....)

**Comment by doudz** [comment]
Le support de lumi.remote.b1acn01 est résolu depuis fin novembre https://github.com/doudz/zigate/issues/49

S'il y a des problèmes avec d'autres types merci de créer d'autres issues sur github afin qu'on s'y retrouve

**Comment by rroblik** [comment]
@doudz concrètement comment en bénéficier parce que je suis à jour côté plugin jeedom et j’ai toujours le soucis ...

**Comment by doudz** [comment]
Il faut attendre malheureusement que le plugin utilise la version 0.26 de la lib python.
Des tests sont en cours, ça devrait être pour bientôt

**Comment by rroblik** [comment]
Ok merci ... sa commence a faire long vivement

**Comment by yann44** [comment]
> Le support de lumi.remote.b1acn01 est résolu depuis fin novembre [doudz/zigate#49](https://github.com/doudz/zigate/issues/49)
> 
> S'il y a des problèmes avec d'autres types merci de créer d'autres issues sur github afin qu'on s'y retrouve

c'est un:

lumi.sensor_switch.aq2

le même que la photo un peu plus haut

**Comment by doudz** [comment]
@yann44 s'il y a un problème avec le lumi.sensor_switch.aq2 merci d'ouvrir un nouvel issue

**Comment by doudz** [comment]
ça sera corrigé dans la prochaine mise à jour (pour ref, lib 0.27, https://github.com/doudz/zigate/commit/2e224352595eeeb557bfce9ab77bde55ceab4537

**Comment by rroblik** [comment]
Super vivement !

**Comment by doudz** [comment]
Déjà corrigé dans la branche develop

**Comment by NVVNETIKA** [comment]
Bonjour,

Avant toute chose merci pour votre travail.

De mon coté j'ai aussi un problème avec mon bouton xiaomi aqara mal reconnu.
Je fais mes test dans une VM Debian.

Jeedom version : 4.0.38
Plugin : 1.5.2
Zigate firmware : 3.1a
Ma librairie python est 0.36.1

Voici comment est reconnu le switch

<img width="938" alt="Screen Shot 2020-01-11 at 22 47 49" src="https://user-images.githubusercontent.com/40762697/72211051-a41fc000-34c4-11ea-9be4-4e0942f1f2d0.png">

Voici les commandes dont je dispose

<img width="1912" alt="Screen Shot 2020-01-11 at 22 48 55" src="https://user-images.githubusercontent.com/40762697/72211045-966a3a80-34c4-11ea-9afb-aa60a4f70800.png">

Je n'ai que le multiclick disponible ce qui ne m'arrange pas.
J'ai bien tenté d'utiliser le bouton pour voir si cela crée les commandes manquantes mais rien à faire.

Avez vous une idée de comment résoudre mon problème.

D'avance merci
