### ISSUE TITLE
Impossible d'associer une prise legrand netatmo

### ISSUE THREAD

**Issue by sebfar9172** [Jeedom-Zigate/jeedom-plugin-zigate#85]
Bonjour
Malgré la lecture des docs, des forums je n'arrive pas à inclure mes prises legrand netatmo (j'ai une jeedom smart avec une clé zigate 3d). Quelle est la procédure à suivre ?
MercI

**Comment by llaumgui** [comment]
Bonjour,

déjà c'est partiel comme support : https://zigate.fr/produits-legrand-compatibles-zigate/

Ensuite c'est supporté mais on a eu 0 retour dessus: https://jeedom-zigate.github.io/jeedom-plugin-zigate/fr_FR/index
Pour moi la discussion doit avoir lieu sur le forum: https://www.jeedom.com/forum/viewtopic.php?f=133&t=34490

Si on nous remonte des infos, on les incorporera à la doc.
