### ISSUE TITLE
Zigate et pont phillips hue

### ISSUE THREAD

**Issue by octera** [Jeedom-Zigate/jeedom-plugin-zigate#89]
Bonjour,
Ce n'est pas vraiment une issue mais plus une question globale sur le zigbee/zigate.

J'ai actuellement 6 luminaire/ampoule phillips HUE relié sur le pont HUE, et 12 capteurs XIAOMI (tempé, porte, ...) relié sur la zigate.

Je souhaite conservé la liaison de mes ampoules HUE avec le pont HUE pour diverses raisons (notamment télé ambilight, et critère WAF de l'application HUE :) )

Mais j'aimerais aussi que mes ampoules servent de répéteur zigbee au réseau de capteur, afin d'avoir un réseau plus maillé, de meilleure qualité et potentiellement moins consommateur de pile. D'après ce que j'ai compris les équipements doivent être dans le même réseau.

Ma question est donc : est t-il possible que HUE et zigate partage le même réseau et si oui comment?

Merci d'avance.

**Comment by llaumgui** [comment]
Bonjour,

ceci est un outil pour tracer les bugs ou demande d'évolution. Pas un forum de support.
Merci d'utiliser le forum de support.

Cordialement.
