### ISSUE TITLE
Ajouter un menu expert style "TestGui"

### ISSUE THREAD

**Issue by doudz** [Jeedom-Zigate/jeedom-plugin-zigate#9]

**Comment by llaumgui** [comment]
Euh ? Tu peux être plus précis ?

**Comment by doudz** [comment]
Le minimum serait de proposer l'envoi de commande RAW directement à la zigate
par exemple en proposant 2 champs : command et data
command étant le code de la commande à envoyer, exemple : 0x0092 (ON OFF)
data étant la trame au format hexa, exemple pour la commande Off : 02ab12010100

voir https://zigate.fr/wiki/commandes-zigate/

Après si on veut être très ambitieux, on pourrait proposer une réplique de l'interface TestGUI

**Comment by Deepcore93** [comment]
Si j'ai un peu de temps je vais regarder ca

**Comment by llaumgui** [comment]
Nickel, merci !

**Comment by Deepcore93** [comment]
Hello,

J'ai fini la partie interface jeedom.

Par contre j'ai besoin d'un petit coup de main pour le dialogue avec la zigate (génération du json). Ma compétence en python est un peu lite encore.

doudz : je pensais appeler la fonction 'send_data' de la lib zigate (bonne idée ?), par contre j'ai du mal avec les arguments de la fonction callZiGate.

**Comment by doudz** [comment]
Effectivement send_data est ce qu'il faut utiliser
il y a 2 paramètres à envoyer, cmd et payload

**Comment by Deepcore93** [comment]
donc je nomme les arguments 'cmd' et 'payload' et le python retrouve ses petits ?

**Comment by Deepcore93** [comment]
Salut, 

Impossible de faire d'avoir un retour sur fonction 'send_data'. Ca marche sur d'autre fonction telle que 'get_version'

Sans log python c'est compliqué...

Quelqu'un a une idée ?

**Comment by doudz** [comment]
C'est "normal", send_data ne renvoie pas la réponse de la zigate.
La réponse est traitée ailleurs, si on veut récupérer la réponse de la zigate je pense qu'il faut s'orienter vers une sorte de console qui afficherai tout ce qu'il vient de la zigate.
Pour faire cela il faut ajouter cette capacité au démon en interceptant le signal ZIGATE_PACKET_RECEIVED et en envoyant le packet vers Jeedom pour l'afficher

**Comment by Deepcore93** [comment]
@douz : tu peux prendre en charge cette partie, j'ai essayé j'arrive pas 😅

J'ai poussé en développement la partie interface Jeedom

**Comment by Deepcore93** [comment]
justement c'est là où je suis bloqué

**Comment by doudz** [comment]
C'est maintenant fonctionnel, il reste juste à améliorer le refresh automatique javascript
j'ai utilisé la fonction setInterval mais ça provoque l'affichage de la roue de chargement de Jeedom, c'est un peu pénible, si qqn à la solution ?
Et il faudrait aussi stopper le timer lorsqu'on ferme le terminal, là j'ai mis un bouton mais c'est pas top, idem si qqn peut améliorer, je suis pas un pro du javascript

**Comment by Deepcore93** [comment]
Cool que cela fonctionne, pour le reste je vais regarder ça

**Comment by doudz** [comment]
ça n'ira pas s'il est déclenché, car on va raté les responses de la zigate qui arriveront après la commande

**Comment by Deepcore93** [comment]
oui mais du coup tu risques d'avoir aussi des retours non liés à la commande

**Comment by Deepcore93** [comment]
Je push une nouvelle mise a jour du terminal, toujours en mode provoqué.

Mes tests sont concluants, si quelqu'un peu aussi tester

**Comment by llaumgui** [comment]
Je ferme. @Deepcore93 il reste ta PR mais on est dans le domaine de l'amélioration. Pour moi la feature est là. Après si tu as des évolution, faut ouvrir de nouveau ticket.
