### ISSUE TITLE
Problème remontée batterie

### ISSUE THREAD

**Issue by ptitpoulet** [Jeedom-Zigate/jeedom-plugin-zigate#94]
J'ai un petit soucis avec les remontées de batterie pour mes détecteurs d'ouverture Xiaomi.
Aucun soucis pour le modèle lumi.sensor_magnet.aq2 qui remonte bien le niveau de batterie.
Par contre rien pour le modèle lumi.sensor_magnet. Dans la partie "Santé" de Zigate les niveaux remontent seulement OK contre xx% pour l'autre.

Une idée ?

**Comment by ptitpoulet** [comment]
Pouvez-vous m'indiquer où je peux trouver ce fichier car je ne l'ai pas vu dans le répertoire du plugin.

**Comment by doudz** [comment]
Le fichier se trouve dans le répertoire du plugin dans le sous-répertoire resources/zigated
Il s'agit d'un fichier caché nommé `.zigate.json`

**Comment by ptitpoulet** [comment]
Autant pour moi je n'avais pas checké les fichiers cachés.
Voici donc le fichier contenant tous les appareils avec l'extension modifiée sinon ça ne passait pas ;)

[zigate.txt](https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/files/2656529/zigate.txt)

**Comment by doudz** [comment]
Ok, je ne vois pas d'information concernant le niveau de batterie, à tout hasard est-ce que vous utilisez le firmware 3.0d ? Si c'est le cas il faudrait passer en 3.0e car le niveau de batterie des XIAOMI V1 ne fonctionne pas en 3.0d

**Comment by ptitpoulet** [comment]
Je suis bien en firmware 3.0d, j'ai vu la version 3.0e il y a 2 jours mais je n'ai pas encore eu le temps de passer dessus. Je testerai cette version afin de voir si l'info remonte. Je reviens vers vous dès le test effectué.

**Comment by doudz** [comment]
Ok n'hésitez pas à rouvrir l'issue en cas de besoin

**Comment by smulle48** [comment]
I got the same issue with an Mijia Door Sensor (MCCGQ01LM)

Plugin: 1.1.7
Lib: 0.24.2
Formware: 3.0e
