### ISSUE TITLE
Problème avec bouton xiaomi WXKG02LM lumi.remote.b286acn01

### ISSUE THREAD

**Issue by sam44850** [Jeedom-Zigate/jeedom-plugin-zigate#95]
Bonjour le bouton WXKG02LM est mal reconnu, type: lumi.remote.b286acn01
merci

**Comment by doudz** [comment]
C'est à dire ? Quel est le problème ?

**Comment by doudz** [comment]
ok merci pour le retour,
est-ce que je pourrais avoir le fichier zigate.json pour voir comment il est défini ?

**Comment by doudz** [comment]
https://github.com/doudz/zigate/issues/84

**Comment by sam44850** [comment]
Je ne sais pas où récupérer le fichier zigate.json mais si vous me dites comment faire je vous fais ça.

**Comment by doudz** [comment]
@sam44850 c'est bon merci, quelqu'un a fourni les fichiers à l'instant

**Comment by sam44850** [comment]
Bonne journée alors et bon courage
