### ISSUE TITLE
Sonde température ronde mal reconnue lumi.sensor_ht

### ISSUE THREAD

**Issue by rroblik** [Jeedom-Zigate/jeedom-plugin-zigate#96]
Bonjour,

Je viens de recevoir mes sondes de température / humidité ronde (WSDCGQ01LM) et elle sont assez bizarrement reconnues dans Jeedom (type `lumi.sensor_ht`). Voici les items que j'ai ; je pense que certains non rien à faire là pour ce genre de capteur ; d'autres me sont inconnues ...

- [ ] application_version
- [x] battery
- [x] datecode
- [ ] description
- [x] hardware_version
- [x] humidity
- [x] manufacturer
- [ ] movement
- [ ] movement2
- [x] power_source
- [x] resync
- [ ] rotation_angle?
- [ ] stack_version
- [x] temperature
- [x] type
- [ ] zcl_version

J'utilise le plugin en version 1.1.4, lib 0.22.0, firmware 3.0e

Des retours de votre côté ?

**Comment by doudz** [comment]
Effectivement, je pense que seul température est intéressant.
Est-ce que je pourrais avoir le fichier zigate.json ?

**Comment by doudz** [comment]
En principe corrigé en 0.27

**Comment by llaumgui** [comment]
Donc je ferme.
