### ISSUE TITLE
Xiaomi Aqara vibration sensor => toutes les valeurs sont en "Autre"

### ISSUE THREAD

**Issue by Cactusbone** [Jeedom-Zigate/jeedom-plugin-zigate#97]
rotation, movement et unknown sont en autre, et si je les met manuellement en numérique, dès la remontée suivante, ça repasse en autre :(

![image](https://user-images.githubusercontent.com/1227612/50383346-0fc49e80-06b2-11e9-9d3c-bad9437013fb.png)

Serait-il possible de les avoir en numérique ? ou de ne pas perdre la configuration manuelle ?

Vu sur http://faire-ca-soi-meme.fr/domotique/2018/09/03/test-xiaomi-aqara-vibration-sensor/#Compatibilite_ZiGate le type est UINT16, donc entier non signé, ça ne tiens pas dans un numérique jeedom ?

**Comment by doudz** [comment]
Rotation est un numérique, mais il y a un bug effectivement, merci de l'avoir signalé, ça sera corrigé pour une prochaine version.
Pour movement, c'est un texte (touched, tilt, drop) le type est donc à "autre"
Enfin concernant unknown, cette commande sera supprimée prochainement, sauf si quelqu'un trouve à quoi elle sert.
